name: "Start Services"
description: "Sets up and starts the required services, including PostgreSQL."

runs:
  using: "composite"
  steps:
    - name: Run PostgreSQL Database
      env:
        TESTS_E2B_API_KEY: "e2b_5ec17bd3933af21f80dc10bba686691c4fcd7057"
        TESTS_E2B_ACCESS_TOKEN: "sk_e2b_acce55acce55acce55acce55acce55acce55acce"
        TESTS_SANDBOX_BUILD_ID_TO_BE_BUILD: "e2b00e2b-e4fe-47af-8ff6-187bca92f3f9"
        TESTS_SANDBOX_TEAM_ID: "834777bd-9956-45ca-b088-9bac9290e2ac"
        TESTS_SANDBOX_USER_ID: "2a5a9fc5-db8d-4af7-ac9e-d0f9272463bc"
        TESTS_RUN_BUILD_TEST: "true"
        # Signed token using "supabasejwtsecretsupabasejwtsecret" with data
        # {
        #  "sub": "2a5a9fc5-db8d-4af7-ac9e-d0f9272463bc",
        #  "exp": 1741780982000
        # }
        TESTS_SUPABASE_TOKEN: "eyJhbGciOiJIUzI1NiIsImtpZCI6ImFDUkNKVXY0bzJVSlRUa08iLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIyYTVhOWZjNS1kYjhkLTRhZjctYWM5ZS1kMGY5MjcyNDYzYmMiLCJleHAiOjE3NDE3ODA5ODIwMDB9.VfkYd6Xn920vtbuDuXnKBPhxpNw6r8PESvJXMD6q8Cs"
      run: |
        docker run -d --name postgres \
                      -e POSTGRES_USER=postgres \
                      -e POSTGRES_PASSWORD=local \
                      -e POSTGRES_DB=mydatabase \
                      -p 5432:5432 \
                      --health-cmd="pg_isready -U postgres" \
                      --health-interval=5s \
                      --health-timeout=2s \
                      --health-retries=5 \
                      postgres:latest
        while [ "$(docker inspect -f '{{.State.Health.Status}}' postgres 2>/dev/null)" != "healthy" ]; do echo "Waiting for PostgreSQL to be healthy..."; sleep 2; done
        echo "PostgreSQL is healthy!"
        
        # Install extensions
        docker exec postgres psql -U postgres -d mydatabase -c "CREATE SCHEMA extensions; CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA extensions;"
        echo "extensions installed"
        
        echo "TESTS_E2B_API_KEY=${TESTS_E2B_API_KEY}" >> .env.test
        echo "TESTS_E2B_ACCESS_TOKEN=${TESTS_E2B_ACCESS_TOKEN}" >> .env.test
        echo "TESTS_SANDBOX_BUILD_ID_TO_BE_BUILD=${TESTS_SANDBOX_BUILD_ID_TO_BE_BUILD}" >> .env.test
        echo "TESTS_SANDBOX_TEAM_ID=${TESTS_SANDBOX_TEAM_ID}" >> .env.test
        echo "TESTS_SANDBOX_USER_ID=${TESTS_SANDBOX_USER_ID}" >> .env.test
        echo "TESTS_SUPABASE_TOKEN=${TESTS_SUPABASE_TOKEN}" >> .env.test
        echo "TESTS_RUN_BUILD_TEST=${TESTS_RUN_BUILD_TEST}" >> .env.test
        set -x
        make migrate
        make -C tests/integration seed
      shell: bash

    - name: Start Services
      env:
        ENVD_TIMEOUT: "60s"
        SUPABASE_JWT_SECRETS: "supabasejwtsecretsupabasejwtsecret"
        TEMPLATE_MANAGER_ADDRESS: "http://127.0.0.1:5009"
        GCP_PROJECT_ID: "e2b-prod"
        GCP_DOCKER_REPOSITORY_NAME: "custom-environments-tests"
        GOOGLE_SERVICE_ACCOUNT_BASE64: ${{ env.GOOGLE_SERVICE_ACCOUNT_BASE64 }}
        TEMPLATE_BUCKET_NAME: "e2b-tests-fc-templates"
      run: |
        echo "ENVD_TIMEOUT=${ENVD_TIMEOUT}" >> .env.test
        echo "SUPABASE_JWT_SECRETS=${SUPABASE_JWT_SECRETS}" >> .env.test
        echo "TEMPLATE_MANAGER_ADDRESS=${TEMPLATE_MANAGER_ADDRESS}" >> .env.test
        echo "GCP_PROJECT_ID=${GCP_PROJECT_ID}" >> .env.test
        echo "GCP_DOCKER_REPOSITORY_NAME=${GCP_DOCKER_REPOSITORY_NAME}" >> .env.test
        echo "GOOGLE_SERVICE_ACCOUNT_BASE64=${GOOGLE_SERVICE_ACCOUNT_BASE64}" >> .env.test
        echo "TEMPLATE_BUCKET_NAME=${TEMPLATE_BUCKET_NAME}" >> .env.test

        mkdir -p ~/logs

        make -C packages/template-manager run-debug 2>&1 | tee ~/logs/template-manager.log &
        make -C packages/orchestrator run-debug 2>&1 | tee ~/logs/orchestrator.log &
        ORCH_PID=$!
        sleep 30
        if ps -p $ORCH_PID > /dev/null; then echo "Orchestrator started, starting API now..."; else exit 1; fi

        make -C packages/api run 2>&1 | tee ~/logs/api.log &
        API_PID=$!
        sleep 30
        if ps -p $API_PID > /dev/null; then echo "API service started"; else exit 1; fi
      shell: bash