// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BalloonReportingStatus Describes the free page reporting pause status.
//
// swagger:model BalloonReportingStatus
type BalloonReportingStatus struct {

	// Whether free-page reporting is currently paused.
	// Required: true
	Paused *bool `json:"paused"`
}

// Validate validates this balloon reporting status
func (m *BalloonReportingStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePaused(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BalloonReportingStatus) validatePaused(formats strfmt.Registry) error {

	if err := validate.Required("paused", "body", m.Paused); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this balloon reporting status based on context it is used
func (m *BalloonReportingStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BalloonReportingStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BalloonReportingStatus) UnmarshalBinary(b []byte) error {
	var res BalloonReportingStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
