// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error
	Message string `json:"message"`
}

// Me defines model for Me.
type Me struct {
	// SandboxID Sandbox ID
	SandboxID string `json:"sandboxID"`
}

// N400 defines model for 400.
type N400 = Error

// N500 defines model for 500.
type N500 = Error
