version: "2"

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/e2b-dev/infra)
linters:
  default: none
run:
  go: 1.24.3