packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      ObjectProvider:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockobjectprovider.go
          pkgname: storagemocks
      SeekableObjectProvider:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockseekableobjectprovider.go
          pkgname: storagemocks

  github.com/e2b-dev/infra/packages/orchestrator/internal/sandbox/network:
    interfaces:
      Storage:
        config:
          dir: packages/orchestrator/internal/sandbox/network
          filename: mocks_test.go
          pkgname: network_test

      Operations:
        config:
          dir: packages/orchestrator/internal/sandbox/network
          filename: mocks_test.go
          pkgname: network_test
