packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      featureFlagsClient:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockfeatureflagsclient.go
          pkgname: storagemocks
          structname: MockFeatureFlagsClient
      Blob:
        config:
<<<<<<< HEAD
          dir: packages/shared/pkg/storage
          filename: mock_objectprovider.go
          inpackage: true # refers to types in the same package
      FramedWriter:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_framedwriter.go
          inpackage: true # refers to types in the same package
      FramedReader:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_framedwriter.go
          inpackage: true # refers to types in the same package
=======
          dir: packages/shared/pkg/storage/mocks
          filename: mockobjectprovider.go
          pkgname: storagemocks
      Seekable:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockseekableobjectprovider.go
          pkgname: storagemocks

  io:
    interfaces:
      Reader:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockioreader.go
          pkgname: storagemocks

  github.com/e2b-dev/infra/packages/shared/pkg/utils:
    interfaces:
      fileOps:
        config:
          dir: packages/shared/pkg/utils
          filename: mocks_test.go
          pkgname: utils
>>>>>>> 8720c9f2160eb7dc458308d3d97f53ac794e109b
