packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      featureFlagsClient:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockfeatureflagsclient.go
          pkgname: storagemocks
          structname: MockFeatureFlagsClient
      Blob:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockobjectprovider.go
          pkgname: storagemocks
      Seekable:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockseekableobjectprovider.go
          pkgname: storagemocks

  github.com/e2b-dev/infra/packages/shared/pkg/utils:
    interfaces:
      fileOps:
        config:
          dir: packages/shared/pkg/utils
          filename: mocks_test.go
          pkgname: utils

  io:
    interfaces:
      Reader:
        config:
          dir: packages/shared/pkg/storage/mocks
          filename: mockioreader.go
          pkgname: storagemocks

  github.com/willscott/go-nfs:
    interfaces:
      Handler:
        config:
          dir: packages/orchestrator/internal/nfs/mocks
          filename: handler.go
          pkgname: mocks

  github.com/go-git/go-billy/v5:
    interfaces:
      Filesystem:
        config:
          dir: packages/orchestrator/internal/nfs/mocks
          filename: billy.go
          pkgname: mocks
