packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      featureFlagsClient:
        config:
          dir: packages/shared/pkg/storage
          inpackage: true
          filename: mock_feature_flags_client.go
          structname: MockFeatureFlagsClient
      StorageProvider:
        config:
          dir: packages/shared/pkg/storage
          inpackage: true
          filename: mock_storage_provider.go

  io:
    interfaces:
      Reader:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_io_reader.go
          inpackage: true
          pkgname: storage

  github.com/e2b-dev/infra/packages/shared/pkg/utils:
    interfaces:
      fileOps:
        config:
          dir: packages/shared/pkg/utils
          filename: mocks_test.go
          pkgname: utils
