packages:
  github.com/e2b-dev/infra/packages/envd/internal/services/spec/filesystem/filesystemconnect:
    interfaces:
      FilesystemHandler:
        config:
          dir: packages/envd/internal/services/spec/filesystem/filesystemconnect/mocks
          filename: mocks.go
          pkgname: filesystemconnectmocks

  github.com/e2b-dev/infra/packages/shared/pkg/storage:
    interfaces:
      ObjectProvider:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_objectprovider.go
          inpackage: true # refers to types in the same package
      SeekableObjectProvider:
        config:
          dir: packages/shared/pkg/storage
          filename: mock_seekableobjectprovider.go
          inpackage: true # refers to types in the same package
