// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_team_api_key.sql

package authqueries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateTeamApiKey = `-- name: UpdateTeamApiKey :one
UPDATE "public"."team_api_keys" SET name = $1 , updated_at = $2 WHERE id = $3 AND team_id = $4
RETURNING id
`

type UpdateTeamApiKeyParams struct {
	Name      string
	UpdatedAt *time.Time
	ID        uuid.UUID
	TeamID    uuid.UUID
}

func (q *Queries) UpdateTeamApiKey(ctx context.Context, arg UpdateTeamApiKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateTeamApiKey,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.TeamID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
