name: "Build Packages"
description: "Compiles and builds Go services."

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.work'
        cache-dependency-path: 'go.work.sum'

    - name: Build Packages
      run: |
        make -C tests/integration build-debug
        make -C packages/db build-debug
        make -C packages/orchestrator build-debug
        make -C packages/api build-debug
        make -C packages/envd build-debug
      shell: bash
