name: "Build Sandbox Template"
description: "Builds the Firecracker sandbox template."

runs:
  using: "composite"
  steps:
    - name: Build Sandbox Template
      env:
        TEMPLATE_ID: "2j6ly824owf4awgai1xo"
        BUILD_ID: "98130b63-ca75-431d-956a-9d829d14d317"
        KERNEL_VERSION: "vmlinux-6.1.102"
        FIRECRACKER_VERSION: "v1.10.1_1fcdaec"
        # Rootfs Docker image repository
        GCP_DOCKER_REPOSITORY_NAME: "custom-environments-tests"
        # Not used, but required to be defined
        GOOGLE_SERVICE_ACCOUNT_BASE64: "required-but-not-needed"
      run: |
        echo "TESTS_SANDBOX_TEMPLATE_ID=${TEMPLATE_ID}" >> .env.test
        
        make -C packages/template-manager build-template \
          TEMPLATE_ID=${TEMPLATE_ID} \
          BUILD_ID=${BUILD_ID} \
          KERNEL_VERSION=${KERNEL_VERSION} \
          FC_VERSION=${FC_VERSION} \
          GCP_DOCKER_REPOSITORY_NAME=${GCP_DOCKER_REPOSITORY_NAME} \
          GOOGLE_SERVICE_ACCOUNT_BASE64=${GOOGLE_SERVICE_ACCOUNT_BASE64}
      shell: bash
