[accessLog]

[api]
  dashboard = true
  insecure = false

[entryPoints]
  [entryPoints.traefik]
    address = ":${control_port}"

  [entryPoints.web]
    address = ":${ingress_port}"
    asDefault = true

    [entryPoints.web.transport.lifecycle]
      # Keep accepting requests (and /ping) until LB detects health failure and stops routing
      # /ping returns 503 while in graceful shutdown
      requestAcceptGraceTimeout = "30s"
      # After the grace window, give active connections up to 24h to finish before forcefully closing them
      graceTimeOut = "24h"

  [entryPoints.internal]
    address = ":${ingress_internal_port}"
    asDefault = false

    [entryPoints.internal.transport.lifecycle]
      # Keep accepting requests (and /ping) until LB detects health failure and stops routing
      # /ping returns 503 while in graceful shutdown
      requestAcceptGraceTimeout = "30s"
      # After the grace window, give active connections up to 24h to finish before forcefully closing them
      graceTimeOut = "24h"

[metrics]
  [metrics.otlp]
    [metrics.otlp.grpc]
      endpoint = "${otel_collector_grpc_endpoint}"
      insecure = true

[ping]
  entryPoint = "web"

[providers]
  [providers.consulCatalog]
    exposedByDefault = false
    [providers.consulCatalog.endpoint]
      address = "${consul_endpoint}"
      token = "${consul_token}"
  [providers.file]
    directory = "/local/config"
    watch = false
  [providers.nomad]
    exposedByDefault = false
    [providers.nomad.endpoint]
      address = "${nomad_endpoint}"
      token = "${nomad_token}"
