// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_team_tier_by_api_key.sql

package queries

import (
	"context"
)

const getTeamWithTierByAPIKeyWithUpdateLastUsed = `-- name: GetTeamWithTierByAPIKeyWithUpdateLastUsed :one
UPDATE "public"."team_api_keys" tak
SET last_used = now()
FROM "public"."teams" t
JOIN "public"."tiers" tier ON t.tier = tier.id
WHERE tak.team_id = t.id
  AND tak.api_key_hash = $1
RETURNING t.id, t.created_at, t.is_blocked, t.name, t.tier, t.email, t.is_banned, t.blocked_reason, t.cluster_id, tier.id, tier.name, tier.disk_mb, tier.concurrent_instances, tier.max_length_hours, tier.max_vcpu, tier.max_ram_mb
`

type GetTeamWithTierByAPIKeyWithUpdateLastUsedRow struct {
	Team Team
	Tier Tier
}

func (q *Queries) GetTeamWithTierByAPIKeyWithUpdateLastUsed(ctx context.Context, apiKeyHash string) (GetTeamWithTierByAPIKeyWithUpdateLastUsedRow, error) {
	row := q.db.QueryRow(ctx, getTeamWithTierByAPIKeyWithUpdateLastUsed, apiKeyHash)
	var i GetTeamWithTierByAPIKeyWithUpdateLastUsedRow
	err := row.Scan(
		&i.Team.ID,
		&i.Team.CreatedAt,
		&i.Team.IsBlocked,
		&i.Team.Name,
		&i.Team.Tier,
		&i.Team.Email,
		&i.Team.IsBanned,
		&i.Team.BlockedReason,
		&i.Team.ClusterID,
		&i.Tier.ID,
		&i.Tier.Name,
		&i.Tier.DiskMb,
		&i.Tier.ConcurrentInstances,
		&i.Tier.MaxLengthHours,
		&i.Tier.MaxVcpu,
		&i.Tier.MaxRamMb,
	)
	return i, err
}
