// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_dashboard_teams_with_users_teams_with_tier.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getDashboardTeamsWithUsersTeamsWithTier = `-- name: GetDashboardTeamsWithUsersTeamsWithTier :many
SELECT t.id, t.created_at, t.is_blocked, t.name, t.tier, t.email, t.is_banned, t.blocked_reason, t.cluster_id, t.sandbox_scheduling_labels, t.slug, t.profile_picture_url, ut.is_default, tl.id, tl.max_length_hours, tl.concurrent_sandboxes, tl.concurrent_template_builds, tl.max_vcpu, tl.max_ram_mb, tl.disk_mb
FROM "public"."teams" t
JOIN "public"."users_teams" ut ON ut.team_id = t.id
JOIN "public"."team_limits" tl ON tl.id = t.id
WHERE ut.user_id = $1::uuid
`

type GetDashboardTeamsWithUsersTeamsWithTierRow struct {
	Team      Team
	IsDefault bool
	TeamLimit TeamLimit
}

func (q *Queries) GetDashboardTeamsWithUsersTeamsWithTier(ctx context.Context, userID uuid.UUID) ([]GetDashboardTeamsWithUsersTeamsWithTierRow, error) {
	rows, err := q.db.Query(ctx, getDashboardTeamsWithUsersTeamsWithTier, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardTeamsWithUsersTeamsWithTierRow
	for rows.Next() {
		var i GetDashboardTeamsWithUsersTeamsWithTierRow
		if err := rows.Scan(
			&i.Team.ID,
			&i.Team.CreatedAt,
			&i.Team.IsBlocked,
			&i.Team.Name,
			&i.Team.Tier,
			&i.Team.Email,
			&i.Team.IsBanned,
			&i.Team.BlockedReason,
			&i.Team.ClusterID,
			&i.Team.SandboxSchedulingLabels,
			&i.Team.Slug,
			&i.Team.ProfilePictureUrl,
			&i.IsDefault,
			&i.TeamLimit.ID,
			&i.TeamLimit.MaxLengthHours,
			&i.TeamLimit.ConcurrentSandboxes,
			&i.TeamLimit.ConcurrentTemplateBuilds,
			&i.TeamLimit.MaxVcpu,
			&i.TeamLimit.MaxRamMb,
			&i.TeamLimit.DiskMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
