// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_api_key_last_used.sql

package queries

import (
	"context"
)

const updateTeamApiKeyLastUsed = `-- name: UpdateTeamApiKeyLastUsed :exec
UPDATE "public"."team_api_keys" tak SET last_used = NOW()
WHERE tak.api_key_hash = $1
`

func (q *Queries) UpdateTeamApiKeyLastUsed(ctx context.Context, apiKeyHash string) error {
	_, err := q.db.Exec(ctx, updateTeamApiKeyLastUsed, apiKeyHash)
	return err
}
