apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2b-kubernetes-orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/component: kubernetes-orchestrator
    app.kubernetes.io/part-of: e2b
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2b-sandbox
  labels:
    app.kubernetes.io/name: sandbox
    app.kubernetes.io/component: sandbox
    app.kubernetes.io/part-of: e2b
automountServiceAccountToken: false
