openapi: 3.0.0
info:
  version: 0.1.0
  title: E2B Hyperloop

components:
  responses:
    "400":
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    "401":
      description: Authentication error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    "404":
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    "409":
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    "500":
      description: Server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Me:
      required:
        - sandboxID
      properties:
        sandboxID:
          type: string
          description: Sandbox ID

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error

paths:
  /me:
    get:
      operationId: me
      description: Returns information about sandbox itself
      responses:
        "200":
          description: Request was successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Me"

  /logs:
    post:
      operationId: logs
      description: Receives JSON based logs messages
      responses:
        "200":
          description: Request was successful
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
