# This is a config for E2B sandbox template.
# You can use template ID (veiohd78xjs3ibuaju57) or template name (test-template-4504da89-35a8-4a40-9d30-d7aa40080c77) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("test-template-4504da89-35a8-4a40-9d30-d7aa40080c77") # Sync sandbox
# sandbox = await AsyncSandbox.create("test-template-4504da89-35a8-4a40-9d30-d7aa40080c77") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('test-template-4504da89-35a8-4a40-9d30-d7aa40080c77')

team_id = "d5b0b29f-c7f7-4dee-92d0-a0a5821e2b0a"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "test-template-4504da89-35a8-4a40-9d30-d7aa40080c77"
template_id = "veiohd78xjs3ibuaju57"
