// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package block

import (
	"context"

	"github.com/e2b-dev/infra/packages/shared/pkg/feature-flags"
	"github.com/launchdarkly/go-sdk-common/v3/ldcontext"
	"github.com/launchdarkly/go-sdk-common/v3/ldvalue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFlagsClient creates a new instance of MockFlagsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagsClient {
	mock := &MockFlagsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlagsClient is an autogenerated mock type for the flagsClient type
type MockFlagsClient struct {
	mock.Mock
}

type MockFlagsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagsClient) EXPECT() *MockFlagsClient_Expecter {
	return &MockFlagsClient_Expecter{mock: &_m.Mock}
}

// JSONFlag provides a mock function for the type MockFlagsClient
func (_mock *MockFlagsClient) JSONFlag(ctx context.Context, flag feature_flags.JSONFlag, ldctx ...ldcontext.Context) ldvalue.Value {
	var tmpRet mock.Arguments
	if len(ldctx) > 0 {
		tmpRet = _mock.Called(ctx, flag, ldctx)
	} else {
		tmpRet = _mock.Called(ctx, flag)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for JSONFlag")
	}

	var r0 ldvalue.Value
	if returnFunc, ok := ret.Get(0).(func(context.Context, feature_flags.JSONFlag, ...ldcontext.Context) ldvalue.Value); ok {
		r0 = returnFunc(ctx, flag, ldctx...)
	} else {
		r0 = ret.Get(0).(ldvalue.Value)
	}
	return r0
}

// MockFlagsClient_JSONFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSONFlag'
type MockFlagsClient_JSONFlag_Call struct {
	*mock.Call
}

// JSONFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - flag feature_flags.JSONFlag
//   - ldctx ...ldcontext.Context
func (_e *MockFlagsClient_Expecter) JSONFlag(ctx interface{}, flag interface{}, ldctx ...interface{}) *MockFlagsClient_JSONFlag_Call {
	return &MockFlagsClient_JSONFlag_Call{Call: _e.mock.On("JSONFlag",
		append([]interface{}{ctx, flag}, ldctx...)...)}
}

func (_c *MockFlagsClient_JSONFlag_Call) Run(run func(ctx context.Context, flag feature_flags.JSONFlag, ldctx ...ldcontext.Context)) *MockFlagsClient_JSONFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 feature_flags.JSONFlag
		if args[1] != nil {
			arg1 = args[1].(feature_flags.JSONFlag)
		}
		var arg2 []ldcontext.Context
		var variadicArgs []ldcontext.Context
		if len(args) > 2 {
			variadicArgs = args[2].([]ldcontext.Context)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFlagsClient_JSONFlag_Call) Return(value ldvalue.Value) *MockFlagsClient_JSONFlag_Call {
	_c.Call.Return(value)
	return _c
}

func (_c *MockFlagsClient_JSONFlag_Call) RunAndReturn(run func(ctx context.Context, flag feature_flags.JSONFlag, ldctx ...ldcontext.Context) ldvalue.Value) *MockFlagsClient_JSONFlag_Call {
	_c.Call.Return(run)
	return _c
}
