// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W2/cOLLwXyH0fQ87gGI7TnZx1sA+OE4y4x3bY7jbmQMkRkBL7G6udRuSst0b+L8f",
	"sEhKlETd2t1tJzHmYeIWr1XFurFY9c0L0jhLE5II7h188zLMcEwEYfAXDgLC+TS9Icnxe/kDTbwDL8Ni",
	"4flegmPiHdTa+B4jf+WUkdA7ECwnvseDBYmx7CyWmezABaPJ3Ht48D2c0d/Jsn1o83ncqNc5jcLWQc3X",
	"cWMmaUhah9Qfx42Y4TlNsKBpckJjKmSjkPCA0Uz+5h14p/iexnmMkjy+JgylM0QFiTkSKWJE5CxBGWEo",
	"w3Pi+WpVf+WELctlRTCuvYqQzHAeCe/g9d6e781SFmPhHXg0EW/2Pd+L1Yz6c0wT/Zdvlk8TQeaE1dZ/",
	"Ru4F4L+5h6Oc8ZTJJXOBmUBiQVBEuUAzlsYty06K4boByHESXqf3rVgpv49DjCA4bh1Ufxw7YpxFWJCO",
	"UYsGY0Z+kI15liacwHF9u7cn/xekiSAJUBTOsogGgKXd//AUMFSO9/8ZmXkH3v/bLXnArvrKdz8wljI1",
	"RxWl73CI5BIJF96D773de735OQ9zsSCJ0KMiotrJyd9sfvKPKbumYUgSNePbzc94lgo0S/MkVDP+c/Mz",
	"HqXJLKIBYPTv26CiCWG3hBlMPhgqBzI+/HNyQeaUC7YEkcTSjDBBFY3jO34IEkdKhrDJcQ7/nCDVAP1O",
	"luj4PZqlDH04ukC4QkSeXz9OvhxbTpwm7mHVN3S3IIwAJ5OjMr1SRDmK0gALErYMPSEBI6JYvHsO1cje",
	"wfDlqx/qo06XGZHCo1hoYyCSSC7/Wa7Ru/Id/KvkSJ/VV7+OBucGbYCW46bX/yGK0A7DmCYTxaV/p1F0",
	"QTgIpzrKZ5hGJDxK88QhJc8K6aj5PeFILLBAqpcUPTc0irymDPM9+WHUwDyHzc3yKFoi1dtzCkcbYvYs",
	"fmUzVxIInNN5MtUCYIrnF5q3NsAgZQV3rFP+LJcpKdIIEilapbLgkBrFejFjeAl/YzYnDghM4fdiTCQX",
	"gGiCvng4opgfCDz/4iGtRfTSjZrE19uQW38nNbGTdP4hcZ70iNySqI/BnKTzE2j34Hsx4VxqQ42NnKRz",
	"pD8iw9Yc54cLkjU7TwTJ5K4leEF3RBlL4XQyIsECJAZ6TTpHBLbiOps0Jlzg2DHB1HwySLQHKnS0EAvy",
	"So7SD+liqhIkvoZmAfaJwCLnFwRrdl4DvUIKNfSmtcbPV74DskS1rIODwwyIqSkseuxCZ5UkHLTaiuNT",
	"jd87KhbN+X0U5IyRRERLxEiWMkGTOUqTSPFXEEO6x0jKsHhNL2bM4iUWjs4vWxjP0fklClJGOCwNtqIY",
	"kOdS2TuUdF+K9YQEQvPYJp4lqaS5cNNkmgtJ95wEaRJy0NhhNRqSSHZGeCYIQ3cLGizspSK+SPMoROQ+",
	"o4x0Lnyvl4GaVbpkyBEjkugOSyO0uctAtxE9Z09ZskjIURB0UvJxyBn0PepQRo5DKWhnVMkRCR97Dnvo",
	"PKdOvSHG/Kbv0JSznGJ+Q5P5eyIwjbjsrwwMl8xoWVGTc7ktu+mCICUHNXh7BqrhFHYLizMz6L36Frqu",
	"SgRPCY4Pz4+13rQafg/Pj9ENWY5HrZ7gHcyNo+iPmXfwuRsncr2XXBLzle8leRTh64goi24wrej1DiGT",
	"G5c+eYHv0C2OctIcsDFAhLm45MSxrhPM9VkXC8oLIN5hjnIOTM8JxOqen4SyW7frokXVUJOgJswqJb6n",
	"/OaUCEYD3qTBkNzSwLGe9/A7MpReB8KMRoQvuSDx1Km8fyy+I9kX/Y3szHd8RO7FWx/dz/gvTp4h5cp5",
	"Sl3C5VR+Q5n8aMAUUtiz4+ALHL1bCpfSOZXfEM9wABrhNbSy6ZQm4h9vnUq3JJqWUSUBrjJoXcyW+/cN",
	"YhqgthdS2atB9YT+l5y+c2CU8hvE6X9JXTzLNZ/Sd2OFne99SG4/Ye1wDUMq58HReY287CV8SG4pS5NY",
	"SuFbzKg8Zy5toUn2H5Lb8BNh3Gnj6g+GLkhyGyKWJ4lUlbQC3Dq27ylTv8mc09BB19AYwTcHuJogalX7",
	"1Kx9J1xPZOtfH1kaH8d4TmxXQ0jl2DFNsFB7iXGWyQGV46GNTdkOC9+bB1lbw1+Pzq2GrJi5pTVJCMNR",
	"0ePBN7Bdnmm/odz1g++lCRkgk+xlPvjdbe2V9ratr1PC1x6gQRScMHkqD4NAHtV/cxc1TlQbpBuhf0/+",
	"OAMa//XofAvOEInFoc4Qx3ZcumodTg2wZJjzu5Q5hPC5/iKNq5yXrIeV1LR2CBRjXzkGzzlhbgl8qb8M",
	"X6obqMUMfgkXF1RbdYQGeKVwJ+EnqRGdMzKj9w44w++g2EiWp3qg2ypjVAZCytp0KWueST5zzqN+f+Q8",
	"WfcmwDKlBjq8MSTSgG6MCzrjCUnmYuFQB+H37iW2CWa94OoMvgMvLhhKpnJCuSBhqzkLbimHX1X+7PCQ",
	"NfX8iJJEqFuakGSMKHeu1mD71HXV2zlulhe2fhcjLXwCD74URZYK0tXLUlYe5OltNYTQ3YJUxDi6o1Hk",
	"sNE7jSFSVSE6vf9WUxDiccqW/Rs6Ne2gj8AhFr0XDZomTk3z+v1gH/I6FBu4uSRjoIo50p0GQ5ULSZPD",
	"NjmBto17xb4tFn5c8OQolw3llZVrg6efRdv3lfY9a3GCbLBZB8AiggqJG7o1gKiSGRx94+h1uOHkphp4",
	"NGIsJNf5HK6aZ6nne3eYgZADvdEl2U7SOX9PGQmEU0kuPlneWn3joH1e10TfzwMgzTJmKbvDTP5yjYMb",
	"+Gdjdt+7fyXbv7rFTHv7P1fX87EYpfLzu2JIvYFJmjOXOap+H7l0ie2UYRDdmUQJBw/68OWrWafWMOWv",
	"59aAD753ioMFTcixRFbTlsjyQxYsqCCByBlxu06x1cJsNFH6v4sxf8QxjZbuoWbwbcAgp2nookw5Riw/",
	"DR3izKlRlcMklnfDPVbd8Ck2aK2zNp/fgKtCxP2U4Fg5PBycj+AYxfBRu9ytW4emk9m6+ugWq43LED3H",
	"mPsQ67blMnEpSJ2TSH1MdlM+r78Z9zenSUAQydJg8UvNZm1xdICS43ac6kCbqndOB1WQ0CxH29xzeksS",
	"JAdmt9i6yFRxQZ3XP1U4mCUBeoOsw9/QuK4/PTpHQZrM6DxnKgaj6W1o8fiVmvqpJf/rlzfyyyoOldf7",
	"/+OC/Rm567wSeKxbvAZzGO5KzduhnUbp3VfAY0LEVzWBS1uN0rsCBCItVrIgyHTeQX9KpYMTIRvMcMSJ",
	"j6hA12SBb4mR6TFBUhPJSEBnS5rMUUiS5R859Nnbgf929wyVJUTcpexGY3mn3PJ1mkYEgwKHc5Ge45yT",
	"yq2gmr4ZsZPGWFqVUbREmexUVTXUxRHoJfp6xzUjKV1jPYomNJMKoyLsTv0yyB6pWmpgDex5plofAWRB",
	"2SOBU3xN4HeEowhpp2+QxnGemLgnYLQNTdUC1ziF0FBwp01UuSI00YN/d7FtSVYRvXX6RTUX3XnsTWC5",
	"P33auu6F1ndDUJ5v7c2s6SVRzgVhw6CuGzvVgDR2RoIewe9mgJQFC8IFAx9l623VR+MD6Ylq0To/XGEP",
	"deGrLhMVDEPGzMKLPsNmGnZR1qZWxVVlspMnWE0VbzD3PF29JDmYK6FKkPB470GSxjhs3YkG44hQJeO4",
	"TxMbRBWYt/jaeWFlQpRE/5y6IZqYyWun3D2L8pkeJ1zgJHByLOMBprpN6czqxbwO5RiAPhUIA/rawHuR",
	"7vNX5xwmNBwuGZub9i3mUSy7hu+SHJtHr3rcW5BX7q3gMdXDYVibcp06GBwOFiSE4BzHaT+hHJiTaqWC",
	"pDiiYY32hgekvfDTF366FX5KOqi5j5UOimerOqwdpP7CBgewQcXnbB7UzwhdHK/goi7eZ4V21KPxQ+Mh",
	"4A3nhjTqgC6Pzi+7zm3RDhXhfQPFcdFTGcktoROHEPRQnUm5WsfGZ9iXFa6gj/I5UhmoOF7JCLL8nLCA",
	"OFULCXA5eA4RnZlqp8JYh4wdUn7DXaE4QoWEa1yqyE8cLCACZjcuI2OGnm47IsgZqyrhP+0No0kUga2C",
	"LNXrsj2k5swa29w2rhxYUyH2FsqsoLa5QMddgAUggztzJicF/2q6/HNe437lvTUOpUkXMkwT5ZcOVBys",
	"+iNPFgRHYrEc6MEuF3KhRy5/eV/OUf54ZM9W/nxZzlvZ3tECJ/P1WZW9sYLjhUKNDPQAchcXhOdx141s",
	"1WPULcTX5DN6Yo/Fg+99dxfUYRpj6hD57zAnSH20nj0VvkmGZzMaIMq1j5JeR4NCP0lyW4/YrgHEjsQG",
	"tgW8OrkNqx6x9d5Pr+vCeHvXsr6ncdAJTfi59PZJUGp8JfNijluKUcbS++VOPwZXuA2uX+fqI9JmcL5E",
	"cjzBodxC4MgzPPUvUSkvUSkrR6XovZ+kc/erQ3WjXL0gRzgJUUQT0jAm4UfnOPJL19PFJ3peCAuuwqHl",
	"MeeMEu07bAtxb/MKlvfHW38Q+lRQhfXbjzc19KqQ5v3vNqs2E8shvCNUcT8NFjPI5K0j2mH2RnppDZA/",
	"fs7mdDUwwty+DQcLZqcW1x720ML06OXHlUmcATOndojJUIbQ7os5a3phhr2kCLJcWuPnQcvL0y6fyyxK",
	"7ZfeJgBF8Uww49tcHCE8mml92dPu4JAd3e/S4B1Oq0uj02XSudQOR0znoO5Vnva4XtqH/DnDpkYEM1ni",
	"2yLqEhcWqi06sonV4g3VGA137M4frpfS5roAWpAQHR2/v0DXURrccJQydHyOcBgy8FErdXbOQMlVavoO",
	"OtT9ylY4usNLjgS+IUhinYREwjC9JUwNbLfeGXWxBos8z68jGkzVAipeEhdlTVT4EKIVDoguL064FTVa",
	"mhrqUT0wuOrLEndIkQ5JaodrSBI6GqyjgBJjfqOTbvyWcsdSDAgWKRfwVEOrqWAEXZPSVIHAHQ0gHc3H",
	"nbKiodpUdOixEc76fgoeysCTXFdYc3E5/ycVi9ZnrJV7sTYZOczikVLwoeE6LMaXZ29KcOw4a5D1zWEe",
	"6pfHxlknZG/XQ3z+3hB0fYg/F0QsSNndWBr6BNSGtMi0P5SobTVlNrF+S8g1QsPG0fnH9NMoDSx71way",
	"L8/lW13gP/1rd009zowLawr7DtJEZwqZtF+2TxfEulAsu1i377XjPkDFtWNgLpwM1ZnbSXkGIKmi0l4G",
	"qb4valqfmuagAweODOUBF2jwLBJrN3Ht9bf82Wwz5+4ooGHcQ/fuYR2us6TWptavPdJufzZp82g/Mn8X",
	"BFz12omAl6rLTXI12VkMO1dWXtU+aEoGa2VL04mz5FFWrxm6fPfXZX6qPo5pAG6ltFrVS98jFUt/agV6",
	"pWvyiUTj6s9EV/WXS9ROMnyXjAYWEMXjpOgKvvoMzJ0+XVAvk3Kk2ksjAywZy7K5Xjr0NEtJ5BIqq57D",
	"Olw6HAPY5V+b4vkjswCu5LZ3EXmehSscJUUdquuKPlTb/1+meR7g5tc0YnMBexv2ua0fgAraK7y4esj8",
	"QgZoDFYZnS0+gJs1ZcgI9gtNhyjCG+WUiumvwia3z9VmNKF8MW5Xps/gba3CvvhjBOHgk1hu6vHHsDx5",
	"RRxn67FyHM3GSfhII3KZRSl2nImMEe6MIbS5+4xGwNlxBKFhSHcyL98gsNTJ0HPm0DkvWWRdu8PYpR8s",
	"h3VCEsxeOJm1Nzbsfvy8wvFv2r1D83rCOtQ9ES/ujdaWxLO8IRqwgFFCjBUJTXsXWMmA+tiDti7hOUyi",
	"FefKfd1VWeNJOucXOkm888LwKUnBdXvX2EFrQuRHBwmtEsyTBjeEyVPvuJEqvllOi/bpV5EGwMCOYodF",
	"C7GpKFiQ4AaiZXACyaLIPQlyQQyvKzSuMpSylVmAQ8Q5F1jta5plzf5RCz9thPRp/3mQ0ir4XzO01LZb",
	"AfWmE1A9wbwu0O2g90U3H7KDQZQ1PG0hONx5StBuLr36Y3FWRw8cPxcVz9Ii6UvX23xbN7pbpJFR/0o1",
	"BgaCk83yBDEyxyyMCC/g0K4yzUxaRcd+5c8mKxzmCKNrzJussp1VzFwpG7vQ28zxqEexHXV1B7dexSPW",
	"+eMxaS5I1psK3rybk2275jOzDFIgDD4mgmRO/aFxlerS0HoekDSWZm5W4W91tXqHqX7RYd6XtKeQMks4",
	"IXMcLF+8wY/xBr/4cl98uT+wL/fF6bodp6ut42r11ljFrWruRjn05jnn9g7Ldr0fBd24cDvpreFTFfam",
	"mE/zYTfr9YwcsnkeS15Vvh+Us48hBUhK/xvmjkS78lcDMmhWBJFaMzV15PEmgBxqLbp/d8Lp9lW78j/b",
	"OJ3i+ePdoQhzngYUHsbrGkGUI4HnQ65JNnLl1iiQVV4K6fxWBgCXwBRb/WDbOui2IfonFYsyH8y2mWdH",
	"2g6dfcbhgBtlb6g7OFdumq3olk+pmL0oWc9byWrIv3YNql9rUtJTMZgVcumRO5WT1hy3kQn1TC5EKpYT",
	"eQDVXNYj0cNc5aC/JpgR9tFATtHYV2FXCQbagmbl7AshsqLSZGVAKMK7IDiE5roM7/++goavptWknzrG",
	"Vo4D/+ob4/z41e82DMr+kzzD15iT10PWYhq3L8e02AfMDR2tchrNYBIVVN87Cioke/A+7L+TCLWS6Rx4",
	"ezuvd/ag5EhGEpxR78B7s7O3swfB52IB+NtV6HkF6FHywRlXr0p7IYwSclfPtyppD6KOj0PvwDtPubCo",
	"gusqyYSLd2m4XFu12lrW2Fr0urbSKxWX99dY/dhRys5VCrlRpI6ElbqkVlFm12zF8ndlo7Lcb3db2cg+",
	"reDpcFHz56uHK6MvffaqhADnvUocu98q5eMfFJFERDhLacnfEU66aUU1s6nlsFah3q5x3+KwKZvsVuvb",
	"y93VKOBtz0t2tZ/HIUmXne5r+/ZJECp55q4U8nz3m7rseNgt4qp3ofpuKw/4nUYRtx/O2IWs4N0NhQS1",
	"wLMcTAEYu5x6ChMXIca/q5q/NVQ7gtlVVrKVCr33xQo3SWV9hbVbaie7Km03axaXsH6edFgX14oGeR7H",
	"GKplyQ07aAYXmqahVjmOodKMvrohS0CEs9oxGBByUHgYpBUZ3qC6X4lQWoASQo9A70B7pNDJmgZkN65N",
	"JQfHpp5YRDg1lxqjMeiS6ukA9cHen5tTWEjbiOZgY+pJFIf6AhzMrvKk65npDeOIwj7Su9+UFjtQf+im",
	"Fa0+KGo51OOOVxpMx2H6QgU537u+MPp0YxE4/J/KJu1D17nsvGZsrZ89NOzrQRxir4dQtKX/kxCKPPEq",
	"gWKrCP8NPqv4CpfgVt+9IYDWzlaVNamA7zjoApJ3kzQkA7QO1cyx6DP9YT26xrB7aihzAGU8V9c41Ia2",
	"JlTcOqNLE4SF7X5TKYkfWjHzKxEqM6suHOZGzJlJbDyO4+h8yA/+mMyeYKX8lRN4KqrNlEra5GdhmVh5",
	"5AfTS5HF9TsyR+qk1aqmQnpXxIuII2wS1jaV1HWQ1IZEWCNf7YOWYb26jcatgQBch8AQ34PkGs5WKqkz",
	"unm9SShvpzdvsBf7tXSnG6NIUgWsQd0SixTNaGTi+kozGerHoy9QXPdf+Dr4ku/t7f8DZ9m/MpaGX7xf",
	"dtAHHCxAvcBJqAqUcRTnXKBrgi4vThBJgjQkEKvrYkhFakSbH62b/4wUZ7Us/I+Ta03kATHuDSHGvS3K",
	"Q+uq4vOVFDQrK2HVpC09xrjJfwPpHGv3aU2GZxP5huzyAu3bNcor0zY5op2Vs90a/0mIqsI+d61aIe1s",
	"1M7hr0KhhjHT07KOQxdPPUrjGL/iRDaSqImqRUHQ8XsIcZ6Tyko83yP3WQQ1wnTYjYtF6kG+0pB3+pfb",
	"gyJifH+sPr7e26sxM9/LE/pXTnQDoPONKnzOzFKPY6kqQicuSyv8pEfhW5HFttOzpfzhVmYwl0urQNPE",
	"yow7TsUsc+oOdGvVGJ25fXj+Wt+mhGerpVkKzuslAputnYdtCIFr5wirWIG8LJX005BF65nf1XVL2q9P",
	"LwB2vCCeUGUM20HH1XSNlKt6GiGUiTWJC5mq3rGDptMT2QTit8i9IIlW8DsUtoIIdbWTR9Pi+pU/vbJR",
	"CuDeUyiAJjGBSeT44D+VKqopYmuq6A96bs2z+lZ2b2CuH/AP4PUnquXKZ8x3vg+UWpdwpDLnSCywsKLC",
	"CyZNExTTKKI6c1yLFwCeJbpdkiZOs7vsb8PJoSuml8kCu1bZsqqIqkJw5arKAkF7UpEeV+lnCyIUsL6K",
	"AFWU9XIa5WnsMyjtA1nW+RtwJluNyUccyyI5ozqS5csSzIqKpVAG/hZHvlWoyoemKjFxmfRxg+fTNSyB",
	"pJn28RqwNZKEq21s3JKvthGuU0t/vKqf0T7IW7CCf9Bzn5nCc27dGerS1VJqD1F4VT27bdvOSn2vKGbg",
	"oQ9wYqnym8T8271/Dmn7z++MShiZMcIXhHdZWdCkciyVmST1Jyq4zhitqgkOJKOLYt6nsZyq7zvCXC3Y",
	"ETalv9TYsIFDqXzdkEwgDPUUS+4NSabvFVd+8w+pY3XLlXo+h4GXjDU2qiC7JY/CM6Bgefar5NudnEeV",
	"7VyB96mOz9DWrxUifb6XPe0W9gvXHkHzVpFXN8+eEGFXiq2XeN1BU3c5Q3RvWJd1hUnLNPuaeHfQEY4i",
	"MJ8XlEslbZGGKM4jQbOI6DeL6S1hd4wK/XxxOj3xVcFpGDDnqjtBJum9VRGKl1q/bAVlqaWAiQnmuc49",
	"abZmePdQj920KJ779HKnUqy3/p5Sbq4UJSU+bHjp9EWtgqlZpHKQbd/Mby9XebUW+cQ1aRYlO/XoP5vW",
	"Dk+Ghr3HcBrkU/1hm6Ek8HrykREkakPbu6msP6ftQmMlukn+ZqGqfN01xKNi39Bbr8DdWFSvt1b1p+i3",
	"Wi/OlB/LmWIVonmUJ0WURWs27EZ5M6Ttm2fDkHsP+G6M7zsPOdCQds27DrxJV6NCdAxFDmMDp/j+hRM8",
	"e07gtxQ6Fak8hIySW1KhEogo1cFSLfGjDLJbtMdFmeyMZWWhr7xZWugrIOMrg+JC2w2BP8X3Nu964VXr",
	"5lUqonSQ7miaOllO+bHGZlyUWbwIbzuIgxP6Xm1bZ9URuI/WWw28njDKbmVttlx9NYq521NWe2TcEcps",
	"U9MmPFzOnPiD/Fz7a1+DTmzb4u4qi4ngICCZMNcSzy6Ecx2kVGFIuyZRnNsndcg5nSdI4Pnf+C9SQuJm",
	"6uEOwpqqDHGbIC61Mivh3igCe712ApviuZO68BxhWOpLjFK7qIT/uyhz95sUZQMfyeO5crjhdranGlfo",
	"80wVFh1wv4nnHS/dXzBpY9KtnlTz1SQG8G1ac0uee0jfRhP0RaWTOxB4/sVD2gZwqC5VqvpWZqYbmnth",
	"IC1VMt6NtAGLrsOv2isJ+9aRgeEZ6jzdqrKVOLMDTbbavCYc+b2tMzynCazhjNwLnRptTLcTCPzbqM3n",
	"SIw60vAzBEjFAmIKdH7G7/FFS03X7kzw0a5Uy24bYQibU86rmXpXzvLRyHXamunj+T+L2rLBdkF0uudk",
	"oLn2fRDW92v1faeWnK3Z7CpWvPtNJ+d+GBNro+rw2OV1BhGjkiHvyqz3G5SvJue4Q0Duu7mTQvYCF2Xz",
	"f1xc9z/mqFUUaHvT0YfklV54rIjo7b4GCXLGweH/PT0HcUWMmEjG1/2BjG4fckgZCYQqTTKM+UqqeF/0",
	"ah04IrckGjPoCXRwgHaS5iwgg7A/Y2ncdhMGo4zapZp4w1cz7bVRV9PWrSP/PJ0Rbm45VNdfB/8sC+sO",
	"5aBtGbf6OOjE1MV9Gh56nITkvix1ohlqQSGtx0iXI6kWq3Cd8XTO/5jNOGlhWqMfsP0wbHVl7rc1VgM1",
	"vVdiMS98RfEVqIG0+22B+aI7aR9OdBl2FNHkxji0MFO12iVqMU2sk4mXRH0bqrV9LIo2PZLTONy4CzXs",
	"UDduo0jUoNvm15uhcatQf4uNaONF19BPzY9A8xpLP8AlwObOx+3+mFxznWmRPu3/yFnmGuLto1psudDr",
	"JUoTglKG4pSpDIUAiUFZnISS1Ku9EJ0Izdrr9aW4WELxFSklvyff+EtKvqcMpb/dr0ZFrT+85dP+UwS4",
	"fNp/7s5ODYkfKn1fj/RZyUk61iVq0dtzcIpumNxNSf/hxP68fLLrIKw3bSxsRYb15kkY1punYljNqsYv",
	"vMsmMRiQ3RpekbNIFwjkB7u7OKM7ZP96B2eZZ43wrYz9LUNfv9XyeFZ/hDhl++9KxSz7gyltYP0G0z5c",
	"PfxfAAAA//+VzMQHlusAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
