// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9bU8cudLoX7H63g+7UochJM/RPUjPBwLJHp6FLGIge6VdtDLdnhkf+m1t98CciP/+",
	"yGW7293tfhtmBpKg/bBh2q9V5apyVbnqqxekcZYmJBHcO/zqZZjhmAjC4C8cBITzq/SOJKcn8geaeIde",
	"hsXC870Ex8Q7rLXxPUb+zikjoXcoWE58jwcLEmPZWawy2YELRpO59/joezijv5JV+9Dm87hRb3Maha2D",
	"mq/jxkzSkLQOqT+OGzHDc5pgQdPkjMZUyEYh4QGjmfzNO/TO8QON8xgleXxLGEpniAoScyRSxIjIWYIy",
	"wlCG58Tz1ar+zglblcuKYFx7FSGZ4TwS3uHb/X3fm6UsxsI79Ggi3h14vherGfXnmCb6L98snyaCzAmr",
	"rf8zeRCA/+YejnPGUyaXzAVmAokFQRHlAs1YGrcsOymG6wYgx0l4mz60YqX8Pg4xguC4dVD9ceyIcRZh",
	"QTpGLRqMG3mZRnncPm7xecyoj7Ixz9KEE2AC7/f35f+CNBEkATrFWRbRAHA/+TdPAe/leP+XkZl36P2f",
	"SclZJuorn3xkLGVqjiqhfMAhkkskXHiPvvd+/+325zzKxYIkQo+KiGonJ3+3/ck/peyWhiFJ1Izvtz/j",
	"51SgWZonoZrxn9uf8ThNZhENAKP/tQsqmhK2JMxg8tFQOZDx0e/TSzKnXLAVCDqWZoQJqmgc3/MjkGNS",
	"3oRNPnb0+xSpBuhXskKnJ2iWMvTx+BLhChF5fv04+XJsOXGauIdV39D9gjAC/FGOyvRKEeUoSgMsSNgy",
	"9JQEjIhi8e45VCN7B8OXr36oj3q1yogUScVCGwORRMqOP+QavRvfwbtKjvSH+urX0eDcoA3Qctz09t9E",
	"EdpRGNNkqnj/rzSKLgkHkVdH+QzTiITHaZ44ZO/nQuZqKUI4EgsskOolBdodjSKvKRl9T34YNTDPYXOz",
	"PIpWSPX2nCLXhpg9i1/ZzI0EAud0nlxpsXKF5/xSM9cGHASecwd+8Rw0DQwDyX9J0jRySkpuqYs4xEex",
	"cMwYXsHfmM2JcE0hfy/GRDRBf4LgOhR4/qeHtHrSSzpqeF9tpNw8Ce3tN/dtaYnVdZ2Gko5nVKFJbhua",
	"SlCkAZVHEd1TsZBfOEEwq6VL5Tl1HlU3mM1SYRgz3RpQbsAEFmW2KIHyQf77LJ1/TJwMMCJLEvXx3bN0",
	"fgbtHn0vJpxL1bOxpbN0jvRHZLi9Ax5ckKzZeSpIJgmhhHrGUmBajEQAek2JUTpHBLbigjWNCRc4dkxw",
	"ZT4ZYNsDFUgMsSBv5Cj91FdMVYLE19AswD4VWOT8kmAt5WqgV0jRfxUq+h83vgOyRLWsg4PDDIipKSy6",
	"6UJnlSQcJ7cVx+cav+YcVOf3UZAzRhIRrRAjWcoETeYoTSIldkA66x4jKcNiwb2YMYuXWDi+uG7hx8cX",
	"1yhIGeGwNNiK4sue637UcSPypbaTkEBo0eNgtDQmaS7cNJnmQtI9J0GahByuR7AaDUkkOyM8E4Sh+wUN",
	"FvZSEV+keRQi8pBRRjoXvt8rV8wqXaL1mBFJdEfljb+5y0C3ET1nT5kNkJCjIOik1IYhZ9D3aDiEb9tz",
	"DOHRMeZ3fYemnOUc8zuazE+IwDTisr+6dTVEPo5Jy4qanMt9jb5aEKTUAw3enoFqOIXdwuLMDHqvvoWu",
	"mxLBVwTHRxenWp1cD79HF6fojqzGo1ZP8AHmxlH028w7/KMbJ3K911wS843vJXkU4duIqIvuYFrR6x1C",
	"JncuNfsS36MljnLSHLAxQIS5uObEsa4zzPVZFwvKCyDeY45yDkzPCcTqnp+Fslu366JF1VCToCbMKiWe",
	"kIgIMkiB7V+bpVAN1MuM+hvCMtZXxMyhM6rpCeV350QwGjg00pAsaeDYygn8jsxY9QXMaET4igsSXzmv",
	"ap+K70j2RT+Rvfmej8iDeO+jhxn/2ckKpbi8SKlLZp7LbyiTHw2EQwqodPAzgaMPK0FcMJbfEM9wALr/",
	"LbSyjx9NxD/eO69Y8iy0jCrP1TqD1rWHcv++QUwD1PZCKns1qJ7S/5DzDw6MUn6HOP0PqWsdcs3n9MNY",
	"Ge57H5PlF6yN9mFI5Tw4uqiRl72Ej8mSsjSJpXKxxIxK9uFSgpqn+WOyDL8Qxp0WDf3B0AVJliFieZJI",
	"DVDr9a1j+54y7DRlTho66BoaI/jmAFcTRK3arJq1j3HpiWy18hNL49MYz4ltWAqpHDumCRZqLzHOMjmg",
	"MjO1cV/bPOV78yBra/jL8YXVkBUzt7QmCWE4Kno8+ga2q8/a9ix3/eh7aUIGiFp7mY9+d1t7pb1t6+uU",
	"8LUHaBAFJ0yeyqMgkEf1f7iLGqeqDdKN0P9Mf/sMNP7L8cUOTF8Si0NNX47tuFTwOpwaYMkw5/cpc+gW",
	"F/qLlGs5L1kPK6lp4xAoxr5xDJ5zwtzC+1p/Gb5UN1CLGfwSLi6otqo+DfBKnYWEX6Sid8HIjD444Ay/",
	"g74mWZ7qgZZVxqjuPSlrUxGteab5zDmP+v2J82Tdm4ALNzXQ4Y0hkQZ0Y1xQhc9IMhcLh5YLv3cvsU0w",
	"6wVXZ/AdeHHBUDKVM8oFCVtv6Tii2GWokz8P0SeDiJJEGLtixogy3mvFvO8Wono7x83ywoTRxUgLU8ej",
	"L0WRpYJ09bKUlUd5elvvd+h+QSpiHN3TKHKYHjrveKSqQnT6eqymIMTjlK36N3Ru2kEfgUMset1KmibO",
	"TfO6j7kPeR2KDXi/yRioYo50p8FQ5ULS5LBNTqFtwzfdt8XCWA8GKmWJoryycn2P62fRts/b9tUXJ8gG",
	"m3UALCKokLihWwOIKpnB0Tf2a4d1UW6qgUcjxkJym88hXGGWer53jxkIOdAbXZLtLJ3zE8pIIJxKcvHJ",
	"MkJr/5I25d0SHeMBgDTLmKXsHjP5yy0O7uCfjdl97+GNbP9miUH0cdmxsp5PxSiVnz8UQ+oNTNOcua6j",
	"6veRS5fYThkG0Z1JlHBwDAxfvpr1yhqm/PXCGvDR985xsKAJOZXIat4lsvyIBQsqSCByRtwWYWy1MBtN",
	"lP7vYsyfcEyjlXuoGXwbMMh5GrooU44Ry09Dh/js1KjKYRLLMOIeq37xKTZorbM2n9+Aq0LEwxXBsTJ4",
	"ODgfwTGK4aP2JFjOlKbt3PLodIvVho9HzzHGzWM5ka4Tl4LUOYnUx2Q3Zcr7yVj1OU0CgkiWBoufa3fW",
	"FkMHKDlue7AO1qoaHXUIDQnNcvSde06XJEFyYLbElttaxZZ1erWqcDBLAvQGWYe9oRGccX58gYI0mdF5",
	"zlTETdPa0GLILDX1c0v+131S8ss6BpW3B//PBfvP5L7T0/FUa7/LVHij5u3QTqP0/i/AY0LEX2oCl7Ya",
	"pfcFCERarGRBkOm8h36XSgcnQjaY4YgTH1GBbskCL4mR6TFBUhPJSEBnK5rMUUiS1W859Nnfg/8m+4bK",
	"EiLuU3ansbxXbvk2TSOCQYHDuUgvcM5Jxdmppm/GZ6UxlrfKKFqhTHaqqhrKHwZ6ifZauWYkpWmsR9GE",
	"ZlJhVITdqV8G2RNVSw2sgT0/q9bHAFlQ9kjgFF9T+B3hKELa6BukcZwnJsoNGG1DU7XANU4hNBTcbWO3",
	"PZ8mAvW/XGxbklVEl067qOaie+ONoyoMEszWQAaDvOMa8F/Kvv1hFyXo9EHu8qRtzqdisw613nVmU1Aa",
	"OJmDNX/WVtqavhXlXBA2jJp0Y6d6k8bOKOlj+N0MkLJgQbhgYHttdS5+MradntgsfZeBiIOhrgnVZapC",
	"usiYWXjRZ9hMw/yabepiXFWSO3md1VTxPOO/6uolycG4uioB9OOtIkka47B1JxqMIwLujEMiTWwQVWDe",
	"4kPgxe0Zglr659QN0dRMXuNe7lmULfg04QIngZMTG8s21W1KI10v5nXkzQD0qbgl4KAD/T3d56/OScyz",
	"CfAJNzftW8yjWHYN3yU5No9e9bi3IK/cW8FjqofjRrM2ZRJ2MDgcLEgIsVSO035GOTAn1UrFtHFEwxrt",
	"DY+mfOWnr/x0J/yUdFBzHysdpGBVDfEOUn9lgwPYoOJzNg/qZ4QujldwURfvs0JW6m9KQmP54A2jjbys",
	"Al0eX1x3nduiHSqiMQeK46Knuvy3hIQcQTBHdSZlQh4bd2I7YVzBLOVTvTKudLySEWT5BWEBcaoWEuBy",
	"8BwCcDPVTkUdDxk7pPyOu0KMhHrYoHGpAnVxsIDInklcRvwMPd12pJMztFjC/6o3PChRBLYOslSv6/ZQ",
	"oc/W2MaLunbAUIXYWyizgtrmAh0+DgtABnfmTE4L/tV0ZeS8xv1KfzwO5X0yZJgmyt4eqLBl9UeeLAiO",
	"xGI10DJfLuRSj1z+clLOUf54bM9W/nxdzlvZ3vECJ/PN3Sp7QzvHC4UaGegB5C4uCc/jLk9z1RLWLcQ3",
	"ZAt7XkuMBNY353gP0xhTh8j/gDlB6qP1eK+wuTI8m9EAUa5tr/Q2GhSpS5JlPcC+BhA7cB7YFvDqZBlW",
	"LX2b9btvyhG+O3ez72kcdEITfi6tmBKUGl/JvJhjSTHKWPqw2uvH4Bpe7rqbWh+Rtgvna4TKMxzKHQTE",
	"vMBT/xpt8xpts3a0jd77WTp3PxJVnvKq4x/hJEQRTUjjMgk/OseRX7pemj7Ta1BYcBUOLW9vZ5Ro22Fb",
	"6H6bVbB0vuz8/e5zQRXWb7+11dCrQpr3P7Ot3plYDmEroYpnarCYMR7Drhe1Uep6bXS2iTl7vZMwt2/D",
	"wYLZucW1hz0gMT16+XFlEmcg0LkdOjOUIbTbYj43rTDDXogEWS5v4xdBy0PhLpvLLErtZAUmsEbxTLjG",
	"t5k4QngM1Ppiqd3AITu6nxHC+6JWk0anyaRzqR2GmM5B3as87zG9tA/5Y4aDjQjSssS3RdQlLixUW3Rk",
	"E6vFG6qxJ+6YpN9cD9uNuwBakBAdn55cotsoDe44Shk6vUA4DBnYqJU6O2eg5Co1fQ8d6X5lKxzd4xVH",
	"At8RJLFOQiJhmC4JUwPbrfdGOdZgkRf5bUSDK7WAipXERVlTFRaFaIUDouvLM25Fw5ZXDZUDARhc9cWM",
	"O1RKh1q1wzUkCR0N1lFAiTG/0w9v/5Vyx1IMCBYpF/AERaupcAm6JeVVBQKSNIB0lCJ3yoqGalPRocdG",
	"bmv/FDwAghfUrnBtR6jPBuNnfJWUzfEeq3wDMyb2Ro930w4qwn+nYtH6zrji4GsT9sOublKcPzZsoMX4",
	"kolcERw7mAakdnTcc/WLd2N1FLK3KwEEPzEnsz7E7wsiFqTsbq5M+ijXhrTO25CH5O7VlCkD+690rhEa",
	"lzWdZFDjWwPL3rWB7GuahlZb/g+fZUFTjzPTx4bi8oM00Rlqpu1RA1cLYnlGyy5WGEHtuA/Q1e1gnkun",
	"ZHCmWlMmDsicqtSwQTr8q77Zp2866MCBI0N5wAUaPIvE2t5de54vfzbbzLk7nGkY99C9e1iH6yyptan1",
	"a9O62zBvDkCPO081fULGN53drfcKDJiqWhMln5OdxbCTNiJRnmS5VjpDncJNHm71AKXLLXFbZkrr46EG",
	"BVZytXUdED1ysjQVV6BXWl2fSViu/7J3XVeARO00w/fJaGABUTxNrq7hhtAhCi5h2jh26CdoneGATOAQ",
	"69yTakPFt/DnUeczg7tkn35qkl9ypNrLGxxcE61r4+3KoTtaiiuXeFmXE9Qx02F1Wct54ToPeRauceoU",
	"Iamua1qSbS9ImQh+gLNDI9NmGPY27CNePysV/FTYdvU8+oUAMdRbZYq28AH5camzdDuSgOyM9DZFE12I",
	"0rux9w+c/+k5XYdcI7YqVZSAXEek7F4CzGhC+WLcrkyfwdtah9XzpygNg1lRuamn86GS9RThvK18xcGb",
	"GifhE43IdRal2HEmMka4M5TUZgYzGgEjwBFECCLdyTzshPhi5/nPmUNjv2aRFX0BY5fm0BzWCalre+Fk",
	"1t7YsPtt/xrHv2k1GJqNF9ah3IW8cB9uLPVu6SgcsIBRagkr0hD3LrCSt/ipB20XksJxrtxez8oaz9J5",
	"hywdhYnNk4LLidvYQWtuzCfHiq0T05UGd4TJU+9wTBbfLJNP+/TrSANgYMexwx4AIcooWJDgDoKmcAK5",
	"0MgDCXKVf76iF5URta3MAsxJzrnA5rGhWTZsXbbw00ZIXw5eBimtg38bWmODGwfBTwGiFXTvOkE3wCxU",
	"B+YeOim6+ZAOD1K40IQLgsO954T18NS7e+gYJ4gmQZSHBGEk8FzZloM0ShPESYbhtZTKTov+9OLVG9P3",
	"T0/eTCo/HS7f/un9vIdOZzAS5WboEHJYGO+jMNmyufHRwryYo4ylSxqqwAP9O0fAcvfGZwl2F8koDvSI",
	"Uhmbp906mQJjcp3vWVpke+pKymFrjfeLNDKKcangwUDA81ieIEbmmIUR4QVdtyuTM5NP1cHr5M8mHSTm",
	"CKNbzJtCpJ2Jzly5WrvovJncVY9iG4DrjhO9iies8/sTX1yQrLe0hXlYKtt2zdc4U0M00akgmVOzajjQ",
	"XbprzwurxtJM6AH8rWIP7jHVT57MA6z23HFmCWdkjoNVj5fh1aewcZ3j1SPwnXoEXu3xr/b49ezxtq6v",
	"1XxjL2hV93fsB94+Lx3jUHuhfrIOLR4Xhdg2oMTv0tBVHISm86ioOlLRgzprrlW3bYqvNTM7sF6b2BGb",
	"57HkxeUDYjn7GEBCtY1/Ye6InZS/GghCsyKK3JqpeQcYf8WRQ23kbtOdSb991a7E9jZOr4HntRoAd3W4",
	"7Hvm71QsynxIz88bOxLZ6HxMDlvkqAuGcke6sjXtRJl8Tk3sNc7iVa8b5L53Sag25a1fYVOCTTG/NZJs",
	"kntlRDUHf3SmTTXz8yXbbJvZGQd50v9EYWMrLiOPm8s2aWupWE0lB1VLtt69H+XqocQtwYywT4bw1BH9",
	"y+RRBu4LRxOalUtaCJEVJaArA0Jt/AXBITTX1fH//xto+Oaqmp9ZR9vLceBffWNcnL751Sadsv80z/At",
	"5uTtkLWYxu3LMS0OgOCHjlZhZmYwiQqqfeiCCsnfvY8HH+Q5sPKDHXr7e2/39qE6VEYSnFHv0Hu3t7+3",
	"rx+hAP4mCj1vAD1K5DufCqnikgijhNzXU2NLEob3B6ehd+hdpFxYVME9RWKEiw9puNpYGflagu/aOxZt",
	"V2H6ogcbO9h/u7HZHcVUHRXtjxplUklYKRiuivm/bZutWP5ENirr8He3lY3s0wq2KRc1/3HzeGPuVX94",
	"VUK4kSNUiWPyFZfbPT15VEQCJRYdKcnk7wgn3bSimtnUcmRPAYTKcEwEYbzVxFY2mVQWCKa2GgW870nO",
	"ofbzNCS9V7P0tX3/LAiVPHMidSQ++aocVo+T4oXFBMrit/KAX2kUcfstoF1zEJ4SUsglDjzLwRSAscup",
	"r2Di4rHBr6oYfw3VjmctKtGi/BMe0RUcs3hyVWUAvnWY+14NNEllf2PMAjaudyv3ekm4vL86GMbUIjsk",
	"kSFJsXiT8SLpsC6uFQ3yPI4xFDaUG3bQDC4UdUOtchxDpRl9c0dWgIg5aXtDKweFJ4Ja/+MNqvuFCKUF",
	"KCH0BPQOvFAWqmzTX9WNa1N0x7GpZxYRTs2lxmgMuqRuPUB9sPfn5hQW0raiOdiYehbFob4AB7OrPO58",
	"YXrDOKKwj/Tkq9JiB+oP3bSi1QdFLUd63PFKg+k4TF+oIOdb1xdGn24sAodFV12o+9B1ITtvGFubZw8N",
	"s8QgDrHfQyjaQPKDEIo88SonbKsI/xd8VhExLsGtvntDAK3t5yoRXAHfcdAFJE+SNCQDtA7VzLHoz/rD",
	"ZnSNYZEFULkFKi6vr3GoDe1MqLh1RpcmCAubfFVZ1h9bMfMLESrZtK7x6EbMZ5OrfRzH0SneH/0xyYrh",
	"lvJ3TuDRuL6mVDLBv4ibiVUaYzC9FImpv6HrSJ20WtVUyFiNeBEjhk0O7qaSugmS2pIIa6TgftQyrFe3",
	"0bg1EAB/FgzxLUiu4WylkkSnm9ebGhl2xYYGe7HzJnSaMYq8e8AalN9bpGhGIxOJWV6TTTB1zgn7b3wb",
	"/Jnv7x/8A2fZf2csDSGC+iMOFqBe4CRUtSQ5inMu0C1B15dniCRBGhIIM3cxpCLbq82PNs1/RoqzWmGR",
	"p8m1JvKAGPeHEOP+DuWh5ar440YKmrWVsGr6pp7LuEnpBRlqa+7IJsOziXxL9/IC7bu9lFembXJEO9Fw",
	"+238ByGqCvucWOWP2tmoXZZEhaoNY6bnZWmaLp56nMYxfqMfoZAQRdU6R+j0BILS56SyEs/3yEMWQdlD",
	"HUjkYpF6kL9oyDvty+0RDzF+OFUf3+7v15iZ7+UJ/TsnugHQ+VYVPmeOuaexVPUSKC6rxfygR+FrkZi7",
	"07Kl7OFWskOXSatA09RK9j1OxSzThA80a9UYnfE+vHytb1vCs/WmWQrO2xWCO1s7D9sSAjfOEda5BfKy",
	"+tsPQxatZ36iSzG1u08vAXa8IJ5Q5Q5U7yDtGj1clQiqvoZkqiDRHrq6OpNNIPyNPAiSaAW/Q2EriFAX",
	"cHoyLW5e+dMrG6UA7j+HAmiSbJjctI/+c6mimiJ2pop+p+fWpIhoZfcG5joZxQBef6Zarn3GfOeLTql1",
	"CUd1Bo7EAgsrzr1g0jRBMY0iqnNItlgB4CGp2yRpwlw764I1VnuOH2RrK21o1ypbVhVRVduyXFVZ82xf",
	"KtLjipftQIQC1tcRoIqyXk+jPI19F0r7QJalSwecydbL5BOOZZGmVR3J8q0MZkURZkmCbIkj36q950NT",
	"lWu9TP+6xfPpGpZA+lz7eA3YGknC9TY2bsk3uwjXqSVCX9fOaB/kHdyCv9Nzn5lamm7dGUpt1qoEDFF4",
	"VYnOXd+dlfpeUczAQh/gxFLlt4n59/v/HNL2n98YlTAyY4QvCO+6ZUGTyrFU1ySpP1HBde54VSB1IBld",
	"FvM+z82p+kwkzNWCHWFT+kuNDRs4lMrXHckEwlAituTekG7+QXHld/+QOla3XGm8EBnmZKyxUQXZHVkU",
	"XgAFc/P0pyDf7peUqhLxGrxPdXyBd/1abeWX6+xpv2G/cu0RNG/VrXbz7CkRdvHretXqPXTlrtCKHgzr",
	"slyYtHz1pol3Dx3jKILr84JyqaQt0hDFeSRoFhH95DNdEnbPqNCvP6+uznxVQx8GzLnqTpApf2EVueOl",
	"1i9bQaV9KWBignmu86iarRnePdRid1XUA39+uVOpP15/jio3V4qSEh82vHTCqVbB1Ky7O+hu36x0IVd5",
	"sxH5xDVpFlWI9eg/mtYOT4aGvcdwXsiv9IddhpLA68knRpCoDe3OU1l/TtuFxkp0k/zNQlX5umuIRcX2",
	"0FuP6N1YVK+31rWn6Ldar8aU78uYYpWkepIlRZTlq7ZsRnk3pO27F8OQew/4JMYPnYccaEib5l0H3iTg",
	"USE6hiKHsYFz/PDKCV48J/BbajeLVB5CRsmSVKgEIkp1sFRL/CiD5CDtcVEmn2ZZY+wv3iwy9hcg4y8G",
	"ZcZ2GwJ/jh9s3vXKqzbNq1RE6SDd0TR1spzyY43NuCizeBHedhAHp2C+2bXOqiNwn6y3Gng9Y5TdKG12",
	"AF2Vm6oGN3cb0GpvjzsinG0i24bhy1n2YZD562Dja9AZilusYGW9HBwEJBPGW/HiIju3SGEV9jXR+a8m",
	"X+Ef7U/RjiHFN51ZWbmoWGilSuVNIw9U1c9u53I6fR78r4XjVVNgYN2yXRK3ZDs3HXcpc92F0Pr4m2Tx",
	"KsGISXO50qsfTZrD5ek3Z7hpp+AygWrnm/vSLornxo7XKplVn4Jsr/B8W7yzOpOcaBQDfd+SOrb9Af+r",
	"+17Rk8lD6zbdH+nqGXj+E/8Zymk0s+92CNotEoxa2doE83bDCyGhvRSn3MXzMpPxKz1202OVtX0tc1YO",
	"TSvSogbWGVolF+ZI80bRdXgUSSWV5yaSi3w76nz35dDK9duBPVuF2hDq/N7WGZ7TBNbwmTwInQxwTLcz",
	"CHXdicZlZXceaeqwlVkquEbIN/mGq3aNLFPadN8jdZKb9hukHGgrnGN7N9FqAvK1M9000iW3Zrt5+U8D",
	"X4bR4pKoKzhOBposvg16+3YtH9+XNcNWmCaKlU++6roUj2Oi01StMbuE2CAaVTLoQ1kIY4vy2ZTbcAjY",
	"AzcvUzSwwFz5nH5AEuh/FVUrNtL2OKoP92s9lVoT/7t9VhXkjIPn7Ft6V+UKvTIhwW/7I4LdzpiQMhII",
	"VZVpGKuWVHFS9GodOCJLEo0Z9Aw6OEA7TXMWkEHYn7E0bnMpwyijdqkm3pG9tVkwe71LgHXkX6a5wc1E",
	"d2Jl7WarZRH2oYy1LaNdH2Odmhrqz8NaT5OQPJTFkTSfLQin9XTB/bJezcd19NM5/20246SFl41+IPrd",
	"cNu1meLOONCpJOm1OM8ru+lkN1BMbfJ1gfmiO1cmTlCeRSkOUUSTO2NVwwzKsSGJcUwT68DiFVHfhup4",
	"n4rqb09kQA5X50INO9TT2ag2N8jZ+XY7pC/hcg2Qb7t/2ni5XxCm6lGrH1Wtc4WJ78ApsPNjszwYk/mx",
	"M0nZl4PvOedjQxh+UostF3q7QmlCUMpQnDKVLxQgMSinmlByfb332lOhBUG9lBwXKyiFJGXqt2S3f02Q",
	"+ZwPW5YH1RjFzUeVfTl4jriyLwcv3b6qIfGjJdN0CKV2R3Z3vYVuV5RFd6/OqFdn1Dji63EKjHUBOGnx",
	"+ZwAW2bBAJFRDPhl+SC2yOzetUnbNWXru2eRre+eS7bqBRj7rVnIq5jtpzyogDu0pJxp7br5FZ+2/6pS",
	"Fwoeq+JHcEVo7mabeDRwN3ONqQVXVCd2HHAL2ltJOW9AvNuYUHvWDkSabPNNWL2U49tEu3XYJl/VP/pK",
	"91gba/V3aEL4ogccrS6YlWw3zm4gXs1ry9CUTLOx+gLsdM7D3HMV6UGhupJsFonbKv42hifsnHbMdeZb",
	"oRwl5NnSoDhnka72zg8nE5zRPXJwu4ezzLPE99fyIWf5jvFrrShD9Ud4dGr/XSl/bH8wdeqs32Ba6+9C",
	"Yt48/m8AAAD//9dUOs1lAQEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
