// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W1McOdLoX1HUOQ87EWUaY38bZ4nYB4ztWXaAIehm5kTYhENUqbu11G0kFdBL8N+/",
	"UEqqUlWpbk3TYJuYhzFdumam8qZU5r0XpHGWJiQR3Nu/9zLMcEwEYfAXDgLC+Sy9JsnRR/kDTbx9L8Ni",
	"6flegmPi7dfa+B4jf+WUkdDbFywnvseDJYmx7CxWmezABaPJwnt48D2c0d/Iqn1o83ncqFc5jcLWQc3X",
	"cWMmaUhah9Qfx42Y4QVNsKBpckxjKmSjkPCA0Uz+5u17J/iOxnmMkjy+Igylc0QFiTkSKWJE5CxBGWEo",
	"wwvi+WpVf+WErcplRTCuvYqQzHEeCW//7e6u781TFmPh7Xs0Ee/2PN+L1Yz6c0wT/Zdvlk8TQRaE1dZ/",
	"Su4E4L+5h8Oc8ZTJJXOBmUBiSVBEuUBzlsYty06K4boByHESXqV3rVgpv49DjCA4bh1Ufxw7YpxFWJCO",
	"UYsGY0Z+kI15liacwHF9v7sr/xekiSAJUBTOsogGgKXJf3gKGCrH+7+MzL197/9MSh4wUV/55BNjKVNz",
	"VFH6AYdILpFw4T343vvdt08/50EuliQRelREVDs5+bunn/xzyq5oGJJEzfj+6Wc8TQWap3kSqhn/8fQz",
	"HqbJPKIBYPR/tkFFU8JuCDOYfDBUDmR88Of0nCwoF2wFIomlGWGCKhrHt/wAJI6UDGGT4xz8OUWqAfqN",
	"rNDRRzRPGfp0eI5whYg8v36cfDm2nDhN3MOqb+h2SRgBTiZHZXqliHIUpQEWJGwZekoCRkSxePccqpG9",
	"g+HLVz/UR52tMiKFR7HQxkAkkVz+i1yjd+k7+FfJkb6or34dDc4N2gAtx02v/kMUoR2EMU2mikv/RqPo",
	"nHAQTnWUzzGNSHiY5olDSp4W0lHze8KRWGKBVC8peq5pFHlNGeZ78sOogXkOm5vnUbRCqrfnFI42xOxZ",
	"/MpmLiUQOKeLZKYFwAwvzjVvbYBBygruWKf8WS5TUqQRJFK0SmXBITWK9WLG8Ar+xmxBHBCYwe/FmEgu",
	"ANEEffVwRDHfF3jx1UNai+ilGzWJr7cht/5BamLH6eJT4jzpEbkhUR+DOU4Xx9DuwfdiwrnUhhobOU4X",
	"SH9Ehq05zg8XJGt2ngqSyV1L8ILuiDKWwulkRIIFSAz0mnSBCGzFdTZpTLjAsWOCmflkkGgPVOhoIRbk",
	"jRylH9LFVCVIfA3NAuxTgUXOzwnW7LwGeoUUauhNa41fLn0HZIlqWQcHhxkQU1NY9NiFzipJOGi1Fccn",
	"Gr+3VCyb8/soyBkjiYhWiJEsZYImC5QmkeKvIIZ0j5GUYfGaXsyYxUssHJ5dtDCew7MLFKSMcFgabEUx",
	"IM+lsnco6b4U6wkJhOaxTTxLUklz4abJNBeS7jkJ0iTkoLHDajQkkeyM8FwQhm6XNFjaS0V8meZRiMhd",
	"RhnpXPhuLwM1q3TJkENGJNEdlEZoc5eBbiN6zp6yZJGQoyDopOTjkDPoe9ShjByFUtDOqZIjEj72HPbQ",
	"eU6dekOM+XXfoSlnOcH8miaLj0RgGnHZXxkYLpnRsqIm53JbdrMlQUoOavD2DFTDKewWFmdm0Hv1LXRd",
	"lgieERwfnB1pvWk9/B6cHaFrshqPWj3BB5gbR9Hvc2//SzdO5HovuCTmS99L8ijCVxFRFt1gWtHrHUIm",
	"1y598hzfohsc5aQ5YGOACHNxwYljXceY67MulpQXQLzFHOUcmJ4TiNU9Pwtlt27XRYuqoSZBTZhVSvxI",
	"+fUJEYwGvEmDIbmhgWM9H+F3ZCi9DoQ5jQhfcUHimVN5/1x8R7Iv+hvZWez4iNyJ9z66m/NfnDxDypWz",
	"lLqEy4n8hjL50YAppLBnx8EXOPqwEi6lcya/IZ7hADTCK2hl0ylNxN/fO5VuSTQto0oCXGfQupgt9+8b",
	"xDRAbS+ksleD6in9Lzn54MAo5deI0/+SuniWaz6hH8YKO9/7lNz8gbXDNQypnAdHZzXyspfwKbmhLE1i",
	"KYVvMKPynLm0hSbZf0puwj8I404bV38wdEGSmxCxPEmkqqQV4NaxfU+Z+k3mnIYOuobGCL45wNUEUava",
	"p2btO+F6Ilv/+szS+CjGC2K7GkIqx45pgoXaS4yzTA6oHA9tbMp2WPjeIsjaGv56eGY1ZMXMLa1JQhiO",
	"ih4PvoHt6lT7DeWuH3wvTcgAmWQv88HvbmuvtLdtfZ0SvvYADaLghMlTeRAE8qj+m7uocaraIN0I/Xv6",
	"+ynQ+K+HZ1twhkgsDnWGOLbj0lXrcGqAJcOc36bMIYTP9BdpXOW8ZD2spKaNQ6AY+9IxeM4Jc0vgC/1l",
	"+FLdQC1m8Eu4uKDaqiM0wCuFOwn/kBrRGSNzeueAM/wOio1keaoHuqkyRmUgpKxNl7LmmeZz5zzq90fO",
	"k3VvAixTaqDDG0MiDejGuKAzHpNkIZYOdRB+715im2DWC67O4Dvw4oKhZCrHlAsStpqz4JZy+FXlzw4P",
	"WVPPjyhJhLqlCUnGiHLnag22T11XvZ3jZnlh63cx0sIn8OBLUWSpIF29LGXlQZ7eVkMI3S5JRYyjWxpF",
	"Dhu90xgiVRWi0/tvNQUhHqds1b+hE9MO+ggcYtF70aBp4sQ0r98P9iGvQ7GBm0syBqqYI91pMFS5kDQ5",
	"bJNTaNu4V+zbYuHHBU+OctlQXlm5Nnj6WbR9X2nfsxYnyAabdQAsIqiQuKFbA4gqmcHRN45ehxtObqqB",
	"RyPGQnKVL+CqeZ56vneLGQg50Btdku04XfCPlJFAOJXk4pPlrdU3DtrndUX0/TwA0ixjnrJbzOQvVzi4",
	"hn82Zve9uzey/ZsbzLS3/0t1PZ+LUSo/fyiG1BuYpjlzmaPq95FLl9hOGQbRnUmUcPCgD1++mnVmDVP+",
	"emYN+OB7JzhY0oQcSWQ1bYksP2DBkgoSiJwRt+sUWy3MRhOl/7sY82cc02jlHmoO3wYMcpKGLsqUY8Ty",
	"09AhTp0aVTlMYnk33GPVDZ9ig9Y6a/P5DbgqRNzNCI6Vw8PB+QiOUQwftcvdunVoOpmtq49usdq4DNFz",
	"jLkPsW5bLhKXgtQ5idTHZDfl8/qbcX9zmgQEkSwNlr/UbNYWRwcoOW7HqQ60qXrndFAFCc1ytM29oDck",
	"QXJgdoOti0wVF9R5/VOFg1kSoDfIOvwNjev6k8MzFKTJnC5ypmIwmt6GFo9fqamfWPK/fnkjv6zjUHm7",
	"9/9csD8lt51XAo91i9dgDsNdqnk7tNMovf0GeEyI+KYmcGmrUXpbgECkxUqWBJnOO+hPqXRwImSDOY44",
	"8REV6Ios8Q0xMj0mSGoiGQnofEWTBQpJsvo9hz67O/DfZNdQWULEbcquNZZ3yi1fpWlEMChwOBfpGc45",
	"qdwKqumbETtpjKVVGUUrlMlOVVVDXRyBXqKvd1wzktI11qNoQjOpMCrC7tQvg+yRqqUG1sCep6r1IUAW",
	"lD0SOMXXFH5HOIqQdvoGaRzniYl7Akbb0FQtcI1TCA0Fd9pElStCEz34Py62LckqojdOv6jmojuPvQks",
	"96dPW9e90OZuCMrzrb2ZNb0kyrkgbBjUdWOnGpDGzkjQQ/jdDJCyYEm4YOCjbL2t+mx8ID1RLVrnhyvs",
	"oS581WWqgmHImFl40WfYTMMuytrUqriqTHbyBKup4g3mnqerlyQHcyVUCRIe7z1I0hiHrTvRYBwRqmQc",
	"92lig6gC8xZfOy+sTIiS6J9TN0RTM3ntlLtnUT7To4QLnAROjmU8wFS3KZ1ZvZjXoRwD0KcCYUBfG3gv",
	"0n3+6pzDhIbDJWNz077FPIpl1/BdkmPz6FWPewvyyr0VPKZ6OAxrU65TB4PDwZKEEJzjOO3HlANzUq1U",
	"kBRHNKzR3vCAtFd++spPt8JPSQc197HSQfFsVYe1g9Rf2eAANqj4nM2D+hmhi+MVXNTF+6zQjno0fmg8",
	"BLzh3JBGHdDl4dlF17kt2qEivG+gOC56KiO5JXTiAIIeqjMpV+vY+Az7ssIV9FE+RyoDFccrGUGWnxEW",
	"EKdqIQEuB88hojNT7VQY65CxQ8qvuSsUR6iQcI1LFfmJgyVEwEziMjJm6Om2I4KcsaoS/rPeMJpEEdg6",
	"yFK9LtpDak6tsc1t49qBNRVib6HMCmqbC3TcBVgAMrgzZ3Ja8K+myz/nNe5X3lvjUJp0IcM0UX7pQMXB",
	"qj/yZElwJJargR7sciHneuTyl4/lHOWPh/Zs5c8X5byV7R0ucbLYnFXZGys4XijUyEAPIHdxTnged93I",
	"Vj1G3UJ8Qz6jZ/ZYPPjed3dBHaYxpg6R/wFzgtRH69lT4ZtkeD6nAaJc+yjpVTQo9JMkN/WI7RpA7Ehs",
	"YFvAq5ObsOoR2+z99KYujLd3Let7Gged0ISfS2+fBKXGV7Io5rihGGUsvVvt9GNwjdvg+nWuPiJtBudr",
	"JMczHMotBI68wFP/GpXyGpWydlSK3vtxunC/OlQ3ytULcoSTEEU0IQ1jEn50jiO/dD1dfKbnhbDgKhxa",
	"HnPOKdG+w7YQ9zavYHl/vPUHoc8FVVi//XhTQ68Kad7/brNqM7EcwjtCFffTYDGDTN46oh1mb6SX1gD5",
	"4+dsTlcDI8zt23CwYHZice1hDy1Mj15+XJnEGTBzYoeYDGUI7b6Y06YXZthLiiDLpTV+FrS8PO3yucyj",
	"1H7pbQJQFM8EM77NxRHCo5nWlz3tDg7Z0f0uDd7htLo0Ol0mnUvtcMR0Dupe5UmP66V9yJ8zbGpEMJMl",
	"vi2iLnFhodqiI5tYLd5QjdFwx+787nopba4LoAUJ0eHRx3N0FaXBNUcpQ0dnCIchAx+1UmcXDJRcpabv",
	"oAPdr2yFo1u84kjga4Ik1klIJAzTG8LUwHbrnVEXa7DIs/wqosFMLaDiJXFR1lSFDyFa4YDo4vyYW1Gj",
	"pamhHtUDg6u+LHGHFOmQpHa4hiSho8E6Cigx5tc66ca/Uu5YigHBMuUCnmpoNRWMoCtSmioQuKMBpKP5",
	"uFNWNFSbig49NsJZ30/BQxl4kusKay4u5/+kYtn6jLVyL9YmI4dZPFIKPjRch8X48uzNCI4dZw2yvjnM",
	"Q/3y2DjrhOzteojPPxqCrg/x55KIJSm7G0tDn4DakBaZ9ocSta2mzCbWbwm5RmjYODr/mH4apYFl79pA",
	"9vW5fKsL/Kd/7a6px5lxYUNh30Ga6Ewh0/bL9tmSWBeKZRfr9r123AeouHYMzLmToTpzOynPACRVVNrL",
	"INX3VU3rU9McdODAkaE84AINnkVi7Sauvf6WP5tt5twdBTSMe+jePazDdZbU2tT6tUfa7c8mbR7tR+bv",
	"goCrXjsR8FJ1uUmuJjuLYefKyqvaB03JYK1saTpxljzK6jVDl+/+qsxP1ccxDcCtlFbreul7pGLpT61A",
	"r3RNPpNoXP+Z6Lr+conaaYZvk9HAAqJ4nBRdw1efgbnTpwvqZVKOVHtpZIAlY1k2VyuHnmYpiVxCZd1z",
	"WIdLh2NgLf+6ixrzLFyD5hUaVdc1nZ22o77MxzzAH6+RaR9Xexv2AatTagU/FaZZPQ1+wayrrMhm8MC1",
	"z3XqXUceh62R3KZooQtBejf2/oHfNvc9QkBA0yGq+pPyciWW1mHk2+e7c5pQvhy3K9Nn8LbWYbD8MaJ6",
	"MAsqN/V4/lOynCLStJWfOHhS4yR8phG5yKIUO85Exgh3RjnazGBOI2AEOILgNaQ7mbd5EPrqPP85c2jF",
	"FyyyAgNg7NJTl8M6IU1nL5zM2hsbdj/PXuP4Ny3zoZlHYR3qJosXN1sbSzNa3mENWMAoZZ0VKVd7F1jJ",
	"0frYg7YNSeE4V+4Lucoaj9NFhywdhYnNk4LrfrGxg9aUzY8OY1on3CgNrgmTp95xZ1Z8s9wq7dOvIw2A",
	"gR3GDpsbomdRsCTBNcTz4ATSWZE7EuSCGF5X6EVlsGcrswCXjXMu8CtsaJYNe3At/LQR0h97L4OU1sG/",
	"Da2xcXeD4KcA0Qq6d52g6wlAdgFzB30suvmQ0Qwiw+E5DsHhznMC++lSwm8ei3WEwRF1Ufo8LVLXdGUY",
	"sPWn22UaGRWxVHVgIDj9LE8QIwvMwojwAjLtatXcJId0nHr5s8lthznC6ArzJjttZydzV+LJLoQ3M1Xq",
	"UWx3Y91Nr1fxiHX+eIycC5L1JrQ3r/9k2675zCyDlAyDj6kgmVPHaFwIu7S4nmcwjaWZ+2H4W10Q32Kq",
	"36WYVzLtibDMEo7JAgerV5/2Y3zarx7pV4/0q0f61SP9SI+0rfVqhddYzq2K75Ny6KfnnD+WL70krYJu",
	"XLid9lYiqgp7U5Ko+Tyd9XpPDtgijyWvKl9BytnHkAKk1v8X5o50wfJXAzJoVoTCWjM1deTxJoAcaiO6",
	"f3fa7PZVu7JY2zid4cXjXaYIc54GFJ7360pHlCOBF0OuUlqsRVWBjITarl2fJziSZnGL5m1gXACDbPWb",
	"bevQ20bpn1Qsyww322akHYlIdD4dh8NulO2h7uxc2Xa2omc+p5L2qnC9bIWrIQvbtal+DUpJUsVg1sgO",
	"SG5Vll1z3EamCDTZHalYTeUBVHNZz14PcpVV/4pgRthnAzlFY9+EXfcYaAualbMvhciK2pmVAaGs8JLg",
	"EJrrwsL//w00fDOrpjHVUcNyHPhX3xhnR29+s2FQ9p/mGb7CnLwdshbTuH05psUeYG7oaJXTaAaTqKD6",
	"nlJQIdmD92nvg0SolR5o39vdebuzC0VUMpLgjHr73rud3Z1dCKcXS8DfRKHnDaBHyQfnSwFVrAxhlJDb",
	"egZZSXsQR30UevveWcqFRRVc130mXHxIw9XG6u/W8uDW4vG1xV6pIb23wXrOjuJ8ruLOjbJ7JKxUWrXK",
	"TLtmK5Y/kY3KAsbdbWUj+7SC18NFzV8uHy59T+AFJIOpEgKc9ypxTO4rBfEfFJFERDiLg8nfEU66aUU1",
	"s6nloFZz367a3+K8KZtMqhX75e5qFPC+522+2s/jkKQLafe1ff8sCJU8cyKFPJ/cq6uQh0kRKT6BesKt",
	"POA3GkXcfgpkl+aCl0QUUu4Cz3IwBWDscuoZTFwETf+mqhjXUO0Iz1d51tYqXd8X/dwklc2VCm+pBu2q",
	"Hd6swlzC+mXSYV1cKxrkeRxjqP8lN+ygGVxomoZa5TiGSjP65pqsABHO+s1gQMhB4amTVmR4g+p+JUJp",
	"AUoIPQK9A+2RQidrWpDduDa1KRybemYR4dRcaozGoEuqpwPUB3t/bk5hIe1JNAcbU8+iONQX4GB2lUdq",
	"L0xvGEcU9pGe3CstdqD+0E0rWn1Q1HKgxx2vNJiOw/SFCnK+d31h9OnGInD4QpVN2oeuM9l5w9jaPHto",
	"2NeDOMRuD6FoS/8nIRR54lVKyFYR/i/4rGItXIJbffeGAFo7W1UeqAK+46ALSJ4kaUgGaB2qmWPRp/rD",
	"ZnSNYXfWULgBCpOur3GoDW1NqLh1RpcmCAub3Kskyw+tmPmVCJVrVpdCcyPm1KRqHsdxdIbnB39MrlKw",
	"Uv7KCTx+1WZKJRH0i7BMrMz4g+mlyEv7HZkjddJqVVMhYS3iRfQRNil4m0rqJkjqiURYIwPvg5ZhvbqN",
	"xq2BAFyHwBDfg+QazlYqyUC6eb1JkW8nbG+wF/v9d6cbo0i7BaxB3RiLFM1pZGL8SjMZKuKjr1Au+J/4",
	"Kvia7+7u/R1n2T8zloZfvV920CccLEG9wEmoSq5xFOdcoCuCLs6PEUmCNCQQyetiSEWyR5sfbZr/jBRn",
	"tboCj5NrTeQBMe4OIcbdLcpD66riy6UUNGsrYdU0ND3GuMnoAwkqa/dpTYZnE/kT2eUF2rdrlFembXJE",
	"O89ouzX+kxBVhX1OrOon7WzUrkqgwqKGMdOTsjJFF089TOMYv+FENpKoiaplTtDRRwh3XpDKSjzfI3dZ",
	"BFXPdAiOi0XqQb7RkHf6l9uDImJ8d6Q+vt3drTEz38sT+ldOdAOg8ydV+Jy5sh7HUlW0TlwWi/hJj8J9",
	"kZe307Ol/OFWrjOXS6tA09TK9TtOxSyzBA90a9UYnbl9ePla31MJz1ZLsxScVysENls7D3siBG6cI6xj",
	"BfKy+NNPQxatZ36iK7G0X5+eA+x4QTyhyoG2g46qCSgpVxVCQih8a1IxMlWPZAfNZseyCcRvkTtBEq3g",
	"dyhsBRHq+i2PpsXNK396ZaMUwN3nUABNIgOTmvLBfy5VVFPE1lTRH/Tcmmf4rezewFw/+B/A649Vy7XP",
	"mO98Kyi1LuFIzs6RWGJhRYgXTJomKKZRRHUuvBYvADxRdLskTZxmdyHjhpND14Av0x92rbJlVRFVpe3K",
	"VZUlj3alIj2udtEWRChgfR0Bqijr9TTK09hnUNoHsqxcOOBMthqTjziWRbpJdSTLVyaYFTVYobD9DY58",
	"q/SWD01VquUyjeUTnk/XsATSgNrHa8DWSBKut7FxS77cRrhOLaHzun5G+yBvwQr+Qc99ZkrpuXVnqLRX",
	"SxI+ROFVFfq2bTsr9b2imIGHPsCJpco/Jebf7/5jSNt/fGdUwsicEb4kvMvKgiaVY6nMJKk/UcF1DmxV",
	"H3EgGZ0X8z6P5VR93xHmasGOsCn9pcaGDRxK5euaZAJhqBBZcm9Im32nuPK7v0sdq1uu1HM7DLxkrLFR",
	"BdkteRReAAXLs18l3+40NKoQ6Rq8T3V8gbZ+rbTqy73sabewX7n2CJq3yta6efaUCLv2bb1o7Q6auQs0",
	"ojvDuqwrTFoWDtDEu4MOcRSB+bykXCppyzREcR4JmkVEv1lMbwi7ZVTo54uz2bGvSmjDgDlX3Qkyafyt",
	"Gle81PplKyi0LQVMTDDPda5KszXDu4d67GZFOeDnlzuV8sP195Ryc6UoKfFhw0unMmoVTM2ym4Ns+2bG",
	"frnKy43IJ65JsyhCqkf/2bR2eDI07D2G0yCf6Q/bDCWB15OPjCBRG9reTWX9OW0XGivRTfI3C1Xl664h",
	"HhX7ht56Be7Gonq9ta4/Rb/VenWm/FjOFKu0zqM8KaIsw/PEbpR3Q9q+ezEMufeAT2J813nIgYa0a951",
	"4E3qGhWiYyhyGBs4wXevnODFcwK/pXSrSOUhZJTckAqVQESpDpZqiR9lkN2iPS7KZGosayV9481iSd8A",
	"Gd8YlEvabgj8Cb6zedcrr9o0r1IRpYN0R9PUyXLKjzU246LM4kV420EcnNz3cts6q47AfbTeauD1jFF2",
	"o7TZAXRVbqoa3NztQKu9Pe6IcLaJ7CkcX87U+oPcX3sbX4POfdviBStrkuAgIJkwtxUvLrLzCSmswr4m",
	"OoHT5B7+0f4U7RCSR9O5lVaKiqVWqqAvIndUlc9t53I6+xr8r4XjVVNgYN2yXRK35NE2Hbcpc93Fpvr4",
	"m2TxKsGISRC50qsfTZrD5el357hpp2DVos0Hq3IlIoEXf+O/SI0QN9Nud3DMGV48FddUK7OSTY7inG83",
	"TrUzvHCyTbxA2CScfI3JayNPvHBT5uRecrKBSSHwQjmYcbs8V40r9HmqSgMPuM/Hi47MDq+YtDE5RDgl",
	"BvAjZROkK6QJ+qrE277Ai68e0javQ2RVqeq+zMQ4NNfIQFqqZHgc6fMoug4PLakkqNxExpHvR8fvthit",
	"/LEd2LP1qg2hzu9tneEFTWANp+RO6AyBY7odQ/zrVtQwKz/wSP+HreFSwTVCvsuHXTXbsjPPTbsRKbs9",
	"CZ94OmO0mrB67WQ3jZS/rQlvXv7rwJfhtzgnOjF6MtBr8X3Q2/fr/PixHBq2ejRRjHtyrzPaP4wJUFOF",
	"rOz6VINoVEmcD2XZiCeUxiZRv0Oc7rl5maKBJebq2uknJIH+h1G1Sh1t76P6cL/Wa6k18b/dl1VBzjhc",
	"nn1PT6tc0VcmKvhtf1Cw+z4mpIwEQpX8GcaqJVV8LHq1DhyRGxKNGfQYOjhAO01zFpBB2J+zNG67VYZR",
	"Ru1STbwll2uzLvF6Kr915F+mo8PNRLfiaO1mq2Wt66GMtS2pXR9jnZpS1c/DWo+SkNyVlYU0ny0Ip/V0",
	"6eo/1XowrqOfLvjv8zknLbxs9BvRH4bbrs0Ut8aBoMz+Wpznld10shuoRDa5X2K+7E6XiROUZ1GKQxTR",
	"5Nr40DCDWmZIYhzTxDqweEXUt6E63ueidNojGZDDobxUww51KDdKtQ2673z7NKQv4XIBkG+zP2283C4J",
	"U8WO1Y9wFDSWfoDriK0fm5u9MckfO/OU/bH3I6d9bAjDz2qx5UKvVihNCEoZilOmUoYCJAalVRNKrq/3",
	"ZHsqtCCoF3zjYgXVkKRM/Z689K85Mp/zbcvNXjVMcfOBZX/sPUdo2R97L92/qiHxs+XTdAiltfyyY72w",
	"Fhm+BD/sE58CgMioM/Cy3MBPSG/v2hjemuzt3bOwt3fPxd6aBcpfOd0AyoN52I3hLDmLdNlPvj+Z4Izu",
	"kL2rHZxlnjXCfRnRXwa039ey81Z/hNcH9t+VOnj2B1OwxPoNpn24fPjfAAAA//+FNF5kPvAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
