// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/e2b-dev/infra/packages/shared/pkg/fc/models"
)

// PutGuestPmemByIDReader is a Reader for the PutGuestPmemByID structure.
type PutGuestPmemByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutGuestPmemByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPutGuestPmemByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutGuestPmemByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPutGuestPmemByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutGuestPmemByIDNoContent creates a PutGuestPmemByIDNoContent with default headers values
func NewPutGuestPmemByIDNoContent() *PutGuestPmemByIDNoContent {
	return &PutGuestPmemByIDNoContent{}
}

/*
PutGuestPmemByIDNoContent describes a response with status code 204, with default header values.

Pmem device is created/updated
*/
type PutGuestPmemByIDNoContent struct {
}

// IsSuccess returns true when this put guest pmem by Id no content response has a 2xx status code
func (o *PutGuestPmemByIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put guest pmem by Id no content response has a 3xx status code
func (o *PutGuestPmemByIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put guest pmem by Id no content response has a 4xx status code
func (o *PutGuestPmemByIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this put guest pmem by Id no content response has a 5xx status code
func (o *PutGuestPmemByIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this put guest pmem by Id no content response a status code equal to that given
func (o *PutGuestPmemByIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the put guest pmem by Id no content response
func (o *PutGuestPmemByIDNoContent) Code() int {
	return 204
}

func (o *PutGuestPmemByIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByIdNoContent", 204)
}

func (o *PutGuestPmemByIDNoContent) String() string {
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByIdNoContent", 204)
}

func (o *PutGuestPmemByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutGuestPmemByIDBadRequest creates a PutGuestPmemByIDBadRequest with default headers values
func NewPutGuestPmemByIDBadRequest() *PutGuestPmemByIDBadRequest {
	return &PutGuestPmemByIDBadRequest{}
}

/*
PutGuestPmemByIDBadRequest describes a response with status code 400, with default header values.

Pmem device cannot be created/updated due to bad input
*/
type PutGuestPmemByIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this put guest pmem by Id bad request response has a 2xx status code
func (o *PutGuestPmemByIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put guest pmem by Id bad request response has a 3xx status code
func (o *PutGuestPmemByIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put guest pmem by Id bad request response has a 4xx status code
func (o *PutGuestPmemByIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put guest pmem by Id bad request response has a 5xx status code
func (o *PutGuestPmemByIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put guest pmem by Id bad request response a status code equal to that given
func (o *PutGuestPmemByIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put guest pmem by Id bad request response
func (o *PutGuestPmemByIDBadRequest) Code() int {
	return 400
}

func (o *PutGuestPmemByIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByIdBadRequest %s", 400, payload)
}

func (o *PutGuestPmemByIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByIdBadRequest %s", 400, payload)
}

func (o *PutGuestPmemByIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutGuestPmemByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutGuestPmemByIDDefault creates a PutGuestPmemByIDDefault with default headers values
func NewPutGuestPmemByIDDefault(code int) *PutGuestPmemByIDDefault {
	return &PutGuestPmemByIDDefault{
		_statusCode: code,
	}
}

/*
PutGuestPmemByIDDefault describes a response with status code -1, with default header values.

Internal server error.
*/
type PutGuestPmemByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this put guest pmem by ID default response has a 2xx status code
func (o *PutGuestPmemByIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put guest pmem by ID default response has a 3xx status code
func (o *PutGuestPmemByIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put guest pmem by ID default response has a 4xx status code
func (o *PutGuestPmemByIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put guest pmem by ID default response has a 5xx status code
func (o *PutGuestPmemByIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put guest pmem by ID default response a status code equal to that given
func (o *PutGuestPmemByIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put guest pmem by ID default response
func (o *PutGuestPmemByIDDefault) Code() int {
	return o._statusCode
}

func (o *PutGuestPmemByIDDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByID default %s", o._statusCode, payload)
}

func (o *PutGuestPmemByIDDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /pmem/{id}][%d] putGuestPmemByID default %s", o._statusCode, payload)
}

func (o *PutGuestPmemByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutGuestPmemByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
