receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service.name: "service_name"
        service.instance.id: "service_instance_id"
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write

processors:
  batch:
    timeout: 1s
  resource:
    attributes:
      - key: environment
        value: local
        action: upsert

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, loki] 