// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package blockmocks

import (
	"context"

	"github.com/e2b-dev/infra/packages/shared/pkg/storage/header"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadonlyDevice creates a new instance of MockReadonlyDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadonlyDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadonlyDevice {
	mock := &MockReadonlyDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadonlyDevice is an autogenerated mock type for the ReadonlyDevice type
type MockReadonlyDevice struct {
	mock.Mock
}

type MockReadonlyDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadonlyDevice) EXPECT() *MockReadonlyDevice_Expecter {
	return &MockReadonlyDevice_Expecter{mock: &_m.Mock}
}

// BlockSize provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) BlockSize() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BlockSize")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockReadonlyDevice_BlockSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockSize'
type MockReadonlyDevice_BlockSize_Call struct {
	*mock.Call
}

// BlockSize is a helper method to define mock.On call
func (_e *MockReadonlyDevice_Expecter) BlockSize() *MockReadonlyDevice_BlockSize_Call {
	return &MockReadonlyDevice_BlockSize_Call{Call: _e.mock.On("BlockSize")}
}

func (_c *MockReadonlyDevice_BlockSize_Call) Run(run func()) *MockReadonlyDevice_BlockSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadonlyDevice_BlockSize_Call) Return(n int64) *MockReadonlyDevice_BlockSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReadonlyDevice_BlockSize_Call) RunAndReturn(run func() int64) *MockReadonlyDevice_BlockSize_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReadonlyDevice_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReadonlyDevice_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockReadonlyDevice_Expecter) Close() *MockReadonlyDevice_Close_Call {
	return &MockReadonlyDevice_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockReadonlyDevice_Close_Call) Run(run func()) *MockReadonlyDevice_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadonlyDevice_Close_Call) Return(err error) *MockReadonlyDevice_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadonlyDevice_Close_Call) RunAndReturn(run func() error) *MockReadonlyDevice_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) Header() *header.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 *header.Header
	if returnFunc, ok := ret.Get(0).(func() *header.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*header.Header)
		}
	}
	return r0
}

// MockReadonlyDevice_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockReadonlyDevice_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockReadonlyDevice_Expecter) Header() *MockReadonlyDevice_Header_Call {
	return &MockReadonlyDevice_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockReadonlyDevice_Header_Call) Run(run func()) *MockReadonlyDevice_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadonlyDevice_Header_Call) Return(header1 *header.Header) *MockReadonlyDevice_Header_Call {
	_c.Call.Return(header1)
	return _c
}

func (_c *MockReadonlyDevice_Header_Call) RunAndReturn(run func() *header.Header) *MockReadonlyDevice_Header_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) ReadAt(ctx context.Context, p []byte, off int64) (int, error) {
	ret := _mock.Called(ctx, p, off)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int64) (int, error)); ok {
		return returnFunc(ctx, p, off)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, int64) int); ok {
		r0 = returnFunc(ctx, p, off)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, int64) error); ok {
		r1 = returnFunc(ctx, p, off)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadonlyDevice_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockReadonlyDevice_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - ctx context.Context
//   - p []byte
//   - off int64
func (_e *MockReadonlyDevice_Expecter) ReadAt(ctx interface{}, p interface{}, off interface{}) *MockReadonlyDevice_ReadAt_Call {
	return &MockReadonlyDevice_ReadAt_Call{Call: _e.mock.On("ReadAt", ctx, p, off)}
}

func (_c *MockReadonlyDevice_ReadAt_Call) Run(run func(ctx context.Context, p []byte, off int64)) *MockReadonlyDevice_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReadonlyDevice_ReadAt_Call) Return(n int, err error) *MockReadonlyDevice_ReadAt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReadonlyDevice_ReadAt_Call) RunAndReturn(run func(ctx context.Context, p []byte, off int64) (int, error)) *MockReadonlyDevice_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) Size(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadonlyDevice_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockReadonlyDevice_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReadonlyDevice_Expecter) Size(ctx interface{}) *MockReadonlyDevice_Size_Call {
	return &MockReadonlyDevice_Size_Call{Call: _e.mock.On("Size", ctx)}
}

func (_c *MockReadonlyDevice_Size_Call) Run(run func(ctx context.Context)) *MockReadonlyDevice_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReadonlyDevice_Size_Call) Return(n int64, err error) *MockReadonlyDevice_Size_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockReadonlyDevice_Size_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockReadonlyDevice_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Slice provides a mock function for the type MockReadonlyDevice
func (_mock *MockReadonlyDevice) Slice(ctx context.Context, off int64, length int64) ([]byte, error) {
	ret := _mock.Called(ctx, off, length)

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]byte, error)); ok {
		return returnFunc(ctx, off, length)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []byte); ok {
		r0 = returnFunc(ctx, off, length)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, off, length)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReadonlyDevice_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type MockReadonlyDevice_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
//   - ctx context.Context
//   - off int64
//   - length int64
func (_e *MockReadonlyDevice_Expecter) Slice(ctx interface{}, off interface{}, length interface{}) *MockReadonlyDevice_Slice_Call {
	return &MockReadonlyDevice_Slice_Call{Call: _e.mock.On("Slice", ctx, off, length)}
}

func (_c *MockReadonlyDevice_Slice_Call) Run(run func(ctx context.Context, off int64, length int64)) *MockReadonlyDevice_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReadonlyDevice_Slice_Call) Return(bytes []byte, err error) *MockReadonlyDevice_Slice_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReadonlyDevice_Slice_Call) RunAndReturn(run func(ctx context.Context, off int64, length int64) ([]byte, error)) *MockReadonlyDevice_Slice_Call {
	_c.Call.Return(run)
	return _c
}
