package userfaultfd

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os/exec"
	"sync"
	"testing"
	"time"
	"unsafe"

	"github.com/RoaringBitmap/roaring/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/sys/unix"

	"github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/uffd/testutils"
)

type testConfig struct {
	name string
	// Page size of the memory area.
	pagesize uint64
	// Number of pages in the memory area.
	numberOfPages uint64
	// Operations to trigger on the memory area.
	operations []operation
	// alwaysWP makes the handler copy with UFFDIO_COPY_MODE_WP for all faults.
	alwaysWP bool
	// gated enables pause/resume control over the handler's serve loop.
	gated bool
	// sourcePatcher, if non-nil, is invoked on the random source data
	// AFTER it's generated but BEFORE it's written to the on-disk
	// content file the child reads. Tests can use this to plant
	// deterministic sentinel bytes in the source so the post-test
	// assertion can distinguish "post-fix zero-fault" from "pre-fix
	// UFFDIO_COPY of stale src bytes" without depending on the
	// happenstance value of randomly-generated bytes.
	sourcePatcher func([]byte)
}

type operationMode uint32

const (
	operationModeRead operationMode = 1 << iota
	operationModeWrite
	operationModeRemove
	operationModeServePause
	operationModeServeResume
	// operationModeSleep pauses for a short duration to let async goroutines
	// enter their blocking syscalls before proceeding.
	operationModeSleep
)

type operation struct {
	// Offset in bytes. Must be smaller than the (numberOfPages-1) * pagesize as it reads a page and it must be aligned to the pagesize from the testConfig.
	offset int64
	mode   operationMode
	// async runs the operation in a background goroutine.
	async bool
}

// handlerPageStates is a snapshot of the pageTracker grouped by state. It
// lets tests assert on the set of pages that the handler observed in each
// state, rather than a flat list of "accessed" offsets.
type handlerPageStates struct {
	faulted []uint
	removed []uint
}

// allAccessed returns the sorted union of offsets that the handler touched
// in any non-missing state.
//
// pageStatesOnce returns each per-state slice already sorted, and a page
// has exactly one state at a time in pageTracker, so the per-state slices
// are disjoint. We merge them with a simple sorted merge instead of a
// bitset — byte offsets make poor bit indices (a single hugepage offset
// would force ~1.8 MB of backing storage).
func (s handlerPageStates) allAccessed() []uint {
	out := make([]uint, 0, len(s.faulted)+len(s.removed))
	i, j := 0, 0
	for i < len(s.faulted) && j < len(s.removed) {
		if s.faulted[i] <= s.removed[j] {
			out = append(out, s.faulted[i])
			i++
		} else {
			out = append(out, s.removed[j])
			j++
		}
	}
	out = append(out, s.faulted[i:]...)
	out = append(out, s.removed[j:]...)

	return out
}

type testHandler struct {
	memoryArea *[]byte
	pagesize   uint64
	data       *MemorySlicer
	// pageStatesOnce returns a per-state snapshot of the handler's pageTracker.
	// Backed by the PageStates RPC; callable any number of times.
	// The "Once" suffix is kept for source-stability with the existing
	// test sites.
	pageStatesOnce func() (handlerPageStates, error)
	// servePause and serveResume gate the UFFD event loop in the child process.
	// Tests use them to deterministically drain a batch of REMOVE events
	// before more faults are processed.
	servePause  func() error
	serveResume func() error

	// client is the RPC channel to the child helper process. nil for
	// any future in-process testHandler — every method that uses it
	// must guard accordingly.
	client *rpcClient
	conn   io.Closer
	cmd    *exec.Cmd

	mutex sync.Mutex
}

// installFaultBarrier asks the child to park the next worker that
// hits `point` for `addr`. Returns a token that must be passed to
// waitFaultHeld and releaseFault.
func (h *testHandler) installFaultBarrier(ctx context.Context, addr uintptr, point barrierPoint) (uint64, error) {
	var resp installFaultBarrierResp
	err := h.client.Call(ctx, "InstallFaultBarrier", installFaultBarrierArgs{Addr: uint64(addr), Point: uint8(point)}, &resp)

	return resp.Token, err
}

// waitFaultHeld blocks until the child reports that a worker has
// reached the barrier identified by token.
func (h *testHandler) waitFaultHeld(ctx context.Context, token uint64) error {
	return h.client.Call(ctx, "WaitFaultHeld", tokenArgs{Token: token}, nil)
}

// releaseFault releases a parked worker so it proceeds past the
// barrier.
func (h *testHandler) releaseFault(ctx context.Context, token uint64) error {
	return h.client.Call(ctx, "ReleaseFault", tokenArgs{Token: token}, nil)
}

func (h *testHandler) executeAll(t *testing.T, operations []operation) {
	t.Helper()

	var asyncErrors []chan error

	for i, op := range operations {
		if op.async {
			errCh := make(chan error, 1)
			asyncErrors = append(asyncErrors, errCh)

			go func() {
				errCh <- h.executeOperation(t.Context(), op)
			}()

			continue
		}

		err := h.executeOperation(t.Context(), op)
		require.NoError(t, err, "step %d: %v at offset %d", i, op.mode, op.offset)
	}

	for _, errCh := range asyncErrors {
		select {
		case err := <-errCh:
			require.NoError(t, err, "async operation")
		case <-t.Context().Done():
			t.Fatal("timed out waiting for async operation")
		}
	}
}

type pageExpectation uint8

const (
	expectClean   pageExpectation = iota // read-only: present + WP set
	expectDirty                          // written: present + WP cleared
	expectRemoved                        // removed: not present
)

func (h *testHandler) checkDirtiness(t *testing.T, operations []operation) {
	t.Helper()

	pagemap, err := testutils.NewPagemapReader()
	require.NoError(t, err)
	defer pagemap.Close()

	memStart := uintptr(unsafe.Pointer(&(*h.memoryArea)[0]))

	// Track the final expected state per offset by replaying operations in order.
	// A remove after a read/write makes the page not present.
	// A read/write after a remove makes it present again.
	expected := make(map[uint]pageExpectation)

	for _, op := range operations {
		off := uint(op.offset)
		switch op.mode {
		case operationModeRead:
			curr, seen := expected[off]
			// If we haven't seen this page before or the page
			// has previously been removed then the page should be clean
			// after this read operation.
			if !seen || curr == expectRemoved {
				expected[off] = expectClean
			}
		case operationModeWrite:
			expected[off] = expectDirty
		case operationModeRemove:
			expected[off] = expectRemoved
		}
	}

	for off, expect := range expected {
		entry, err := pagemap.ReadEntry(memStart + uintptr(off))
		require.NoError(t, err, "pagemap read at offset %d", off)

		switch expect {
		case expectRemoved:
			assert.False(t, entry.IsPresent(), "removed page at offset %d should not be present", off)
		case expectDirty:
			assert.True(t, entry.IsPresent(), "written page at offset %d should be present", off)
			assert.False(t, entry.IsWriteProtected(), "written page at offset %d should be dirty", off)
		case expectClean:
			assert.True(t, entry.IsPresent(), "read-only page at offset %d should be present", off)
			assert.True(t, entry.IsWriteProtected(), "read-only page at offset %d should be clean", off)
		}
	}
}

func (h *testHandler) executeOperation(ctx context.Context, op operation) error {
	switch op.mode {
	case operationModeRead:
		return h.executeRead(ctx, op)
	case operationModeWrite:
		return h.executeWrite(ctx, op)
	case operationModeRemove:
		return h.executeRemove(op)
	case operationModeServePause:
		return h.servePause()
	case operationModeServeResume:
		return h.serveResume()
	case operationModeSleep:
		time.Sleep(50 * time.Millisecond)

		return nil
	default:
		return fmt.Errorf("invalid operation mode: %d", op.mode)
	}
}

func (h *testHandler) executeRemove(op operation) error {
	page := (*h.memoryArea)[op.offset : op.offset+int64(h.pagesize)]

	return unix.Madvise(page, unix.MADV_DONTNEED)
}

func (h *testHandler) executeRead(ctx context.Context, op operation) error {
	readBytes := (*h.memoryArea)[op.offset : op.offset+int64(h.pagesize)]

	expectedBytes, err := h.data.Slice(ctx, op.offset, int64(h.pagesize))
	if err != nil {
		return err
	}

	// The bytes.Equal is the first place in this flow that actually touches the uffd managed memory and triggers the pagefault, so any deadlocks will manifest here.
	if !bytes.Equal(readBytes, expectedBytes) {
		idx, want, got := testutils.FirstDifferentByte(readBytes, expectedBytes)

		return fmt.Errorf("content mismatch: want '%x, got %x at index %d", want, got, idx)
	}

	return nil
}

func (h *testHandler) executeWrite(ctx context.Context, op operation) error {
	bytesToWrite, err := h.data.Slice(ctx, op.offset, int64(h.pagesize))
	if err != nil {
		return err
	}

	// An unprotected parallel write to map might result in an undefined behavior.
	h.mutex.Lock()
	defer h.mutex.Unlock()

	n := copy((*h.memoryArea)[op.offset:op.offset+int64(h.pagesize)], bytesToWrite)
	if n != int(h.pagesize) {
		return fmt.Errorf("copy length mismatch: want %d, got %d", h.pagesize, n)
	}

	return nil
}

func getOperationsOffsets(ops []operation, m operationMode) []uint {
	b := roaring.New()

	for _, operation := range ops {
		if operation.mode&m != 0 {
			b.Add(uint32(operation.offset))
		}
	}

	result := make([]uint, 0, b.GetCardinality())
	b.Iterate(func(x uint32) bool {
		result = append(result, uint(x))

		return true
	})

	return result
}
