name: "Go Setup"
description: |
  Sets up go and gets modules from the cache. A complete cache is over 1 GB, so we want this to cache only what is 
  necessary for each job.

inputs:
  job_key:
    description: A unique key that describes your job.
    required: true

runs:
  using: "composite"
  steps:
    - name: Go Build Cache
      uses: actions/cache@v4
      id: go-build-cache
      with:
        fail-on-cache-miss: false
        path: /home/runner/.cache/go-build
        key: |
          ${{ runner.os }}-go-build-${{ inputs.job_key }}-${{ hashFiles(
            'go.work',
            'packages/*/go.mod',
            'packages/*/go.mod.sum',
            'tests/*/go.mod',
            'tests/*/go.mod.sum'
          ) }}
        restore-keys: |
          ${{ runner.os }}-go-build-${{ inputs.job_key }}-
          ${{ runner.os }}-go-build-

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version-file: go.work
