packages:
  github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/build:
    interfaces:
      Diff:
        config:
          dir: internal/sandbox/build/mocks
          filename: mockdiff.go
          pkgname: buildmocks

  github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/block:
    interfaces:
      ReadonlyDevice:
        config:
          dir: internal/sandbox/block/mocks
          filename: mockreadonlydevice.go
          pkgname: blockmocks

  github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/template/peerserver:
    interfaces:
      Cache:
        config:
          dir: internal/sandbox/template/peerserver/mocks
          filename: mockcache.go
          pkgname: peerservermocks

  github.com/e2b-dev/infra/packages/orchestrator/pkg/sandbox/template:
    interfaces:
      Template:
        config:
          dir: internal/sandbox/template/mocks
          filename: mocktemplate.go
          pkgname: templatemocks
      File:
        config:
          dir: internal/sandbox/template/mocks
          filename: mockfile.go
          pkgname: templatemocks

  github.com/willscott/go-nfs:
    interfaces:
      Handler:
        config:
          dir: internal/nfsproxy/mocks
          filename: nfshandler.go
          pkgname: nfsproxymocks

  github.com/go-git/go-billy/v5:
    interfaces:
      Change:
        config:
          dir: internal/nfsproxy/mocks
          filename: billychange.go
          pkgname: nfsproxymocks
      File:
        config:
          dir: internal/nfsproxy/mocks
          filename: billyfile.go
          pkgname: nfsproxymocks
      Filesystem:
        config:
          dir: internal/nfsproxy/mocks
          filename: billyfs.go
          pkgname: nfsproxymocks
