// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminApiKeyAuthScopes        adminApiKeyAuthContextKey        = "AdminApiKeyAuth.Scopes"
	AdminJWTAuthScopes           adminJWTAuthContextKey           = "AdminJWTAuth.Scopes"
	AuthProviderBearerAuthScopes authProviderBearerAuthContextKey = "AuthProviderBearerAuth.Scopes"
	AuthProviderTeamAuthScopes   authProviderTeamAuthContextKey   = "AuthProviderTeamAuth.Scopes"
)

// Defines values for AdminControlPlaneProjectType.
const (
	Development AdminControlPlaneProjectType = "development"
	Production  AdminControlPlaneProjectType = "production"
	Staging     AdminControlPlaneProjectType = "staging"
)

// Valid indicates whether the value is a known member of the AdminControlPlaneProjectType enum.
func (e AdminControlPlaneProjectType) Valid() bool {
	switch e {
	case Development:
		return true
	case Production:
		return true
	case Staging:
		return true
	default:
		return false
	}
}

// Defines values for BuildStatus.
const (
	Building BuildStatus = "building"
	Failed   BuildStatus = "failed"
	Success  BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case Building:
		return true
	case Failed:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for TagGroupsSort.
const (
	TagGroupsSortLatestAsc  TagGroupsSort = "latest_asc"
	TagGroupsSortLatestDesc TagGroupsSort = "latest_desc"
	TagGroupsSortNameAsc    TagGroupsSort = "name_asc"
	TagGroupsSortNameDesc   TagGroupsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the TagGroupsSort enum.
func (e TagGroupsSort) Valid() bool {
	switch e {
	case TagGroupsSortLatestAsc:
		return true
	case TagGroupsSortLatestDesc:
		return true
	case TagGroupsSortNameAsc:
		return true
	case TagGroupsSortNameDesc:
		return true
	default:
		return false
	}
}

// Defines values for TemplatesSort.
const (
	TemplatesSortCreatedAtAsc  TemplatesSort = "created_at_asc"
	TemplatesSortCreatedAtDesc TemplatesSort = "created_at_desc"
	TemplatesSortUpdatedAtAsc  TemplatesSort = "updated_at_asc"
	TemplatesSortUpdatedAtDesc TemplatesSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the TemplatesSort enum.
func (e TemplatesSort) Valid() bool {
	switch e {
	case TemplatesSortCreatedAtAsc:
		return true
	case TemplatesSortCreatedAtDesc:
		return true
	case TemplatesSortUpdatedAtAsc:
		return true
	case TemplatesSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesParamsSort.
const (
	GetTemplatesParamsSortCreatedAtAsc  GetTemplatesParamsSort = "created_at_asc"
	GetTemplatesParamsSortCreatedAtDesc GetTemplatesParamsSort = "created_at_desc"
	GetTemplatesParamsSortUpdatedAtAsc  GetTemplatesParamsSort = "updated_at_asc"
	GetTemplatesParamsSortUpdatedAtDesc GetTemplatesParamsSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesParamsSort enum.
func (e GetTemplatesParamsSort) Valid() bool {
	switch e {
	case GetTemplatesParamsSortCreatedAtAsc:
		return true
	case GetTemplatesParamsSortCreatedAtDesc:
		return true
	case GetTemplatesParamsSortUpdatedAtAsc:
		return true
	case GetTemplatesParamsSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesTemplateIDTagsGroupsParamsSort.
const (
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc  GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_desc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc    GetTemplatesTemplateIDTagsGroupsParamsSort = "name_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc   GetTemplatesTemplateIDTagsGroupsParamsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesTemplateIDTagsGroupsParamsSort enum.
func (e GetTemplatesTemplateIDTagsGroupsParamsSort) Valid() bool {
	switch e {
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc:
		return true
	default:
		return false
	}
}

// AddTeamMemberRequest defines model for AddTeamMemberRequest.
type AddTeamMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfile defines model for AdminAuthProviderProfile.
type AdminAuthProviderProfile struct {
	// Email Email address from the configured auth provider.
	Email *string `json:"email"`

	// UserId Internal E2B user identifier.
	UserId openapi_types.UUID `json:"userId"`
}

// AdminAuthProviderProfilesLookupEmailRequest defines model for AdminAuthProviderProfilesLookupEmailRequest.
type AdminAuthProviderProfilesLookupEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfilesResolveRequest defines model for AdminAuthProviderProfilesResolveRequest.
type AdminAuthProviderProfilesResolveRequest struct {
	UserIds []openapi_types.UUID `json:"userIds"`
}

// AdminAuthProviderProfilesResponse defines model for AdminAuthProviderProfilesResponse.
type AdminAuthProviderProfilesResponse struct {
	Profiles []AdminAuthProviderProfile `json:"profiles"`
}

// AdminAuthProviderUserBootstrapRequest defines model for AdminAuthProviderUserBootstrapRequest.
type AdminAuthProviderUserBootstrapRequest struct {
	OidcIssuer      string              `json:"oidc_issuer"`
	OidcUserEmail   openapi_types.Email `json:"oidc_user_email"`
	OidcUserId      string              `json:"oidc_user_id"`
	OidcUserName    *string             `json:"oidc_user_name,omitempty"`
	SignupIp        *string             `json:"signup_ip,omitempty"`
	SignupUserAgent *string             `json:"signup_user_agent,omitempty"`
}

// AdminControlPlaneMemberUpsertRequest defines model for AdminControlPlaneMemberUpsertRequest.
type AdminControlPlaneMemberUpsertRequest struct {
	AddedBy *openapi_types.UUID `json:"added_by,omitempty"`
}

// AdminControlPlaneProject defines model for AdminControlPlaneProject.
type AdminControlPlaneProject struct {
	Id          openapi_types.UUID           `json:"id"`
	Name        string                       `json:"name"`
	ProjectType AdminControlPlaneProjectType `json:"project_type"`
	Slug        string                       `json:"slug"`
}

// AdminControlPlaneProjectLimits defines model for AdminControlPlaneProjectLimits.
type AdminControlPlaneProjectLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrent_sandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrent_template_builds"`
	DiskMb                   int64 `json:"disk_mb"`
	EventsTtlDays            int32 `json:"events_ttl_days"`
	MaxRamMb                 int64 `json:"max_ram_mb"`
	MaxSandboxLengthHours    int32 `json:"max_sandbox_length_hours"`
	MaxVcpu                  int32 `json:"max_vcpu"`
}

// AdminControlPlaneProjectType defines model for AdminControlPlaneProjectType.
type AdminControlPlaneProjectType string

// AdminControlPlaneProjectUpsertRequest defines model for AdminControlPlaneProjectUpsertRequest.
type AdminControlPlaneProjectUpsertRequest struct {
	Name        string                       `json:"name"`
	ProjectType AdminControlPlaneProjectType `json:"project_type"`
	Slug        string                       `json:"slug"`
}

// AdminTeamBootstrapRequest defines model for AdminTeamBootstrapRequest.
type AdminTeamBootstrapRequest struct {
	// Email Billing/contact email for the team.
	Email openapi_types.Email `json:"email"`

	// Name Team name.
	Name string `json:"name"`
}

// AdminUserBootstrapResponse defines model for AdminUserBootstrapResponse.
type AdminUserBootstrapResponse struct {
	// Id The team ID for the bootstrapped user.
	Id openapi_types.UUID `json:"id"`

	// Slug The team slug for the bootstrapped user.
	Slug string `json:"slug"`

	// UserId The internal user ID assigned to the bootstrapped identity.
	UserId openapi_types.UUID `json:"user_id"`
}

// BuildInfo defines model for BuildInfo.
type BuildInfo struct {
	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Names Template names related to this build, if available.
	Names *[]string `json:"names,omitempty"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildStatus Build status mapped for dashboard clients.
type BuildStatus string

// BuildStatusItem defines model for BuildStatusItem.
type BuildStatusItem struct {
	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildsListResponse defines model for BuildsListResponse.
type BuildsListResponse struct {
	Data []ListedBuild `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// BuildsStatusesResponse defines model for BuildsStatusesResponse.
type BuildsStatusesResponse struct {
	// BuildStatuses List of build statuses
	BuildStatuses []BuildStatusItem `json:"buildStatuses"`
}

// CPUCount CPU cores for the sandbox
type CPUCount = int64

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// DefaultTemplate defines model for DefaultTemplate.
type DefaultTemplate struct {
	Aliases         []DefaultTemplateAlias `json:"aliases"`
	BuildCount      int32                  `json:"buildCount"`
	BuildId         openapi_types.UUID     `json:"buildId"`
	CreatedAt       time.Time              `json:"createdAt"`
	EnvdVersion     *string                `json:"envdVersion,omitempty"`
	Id              string                 `json:"id"`
	Public          bool                   `json:"public"`
	RamMb           int64                  `json:"ramMb"`
	SpawnCount      int64                  `json:"spawnCount"`
	TotalDiskSizeMb *int64                 `json:"totalDiskSizeMb"`
	Vcpu            int64                  `json:"vcpu"`
}

// DefaultTemplateAlias defines model for DefaultTemplateAlias.
type DefaultTemplateAlias struct {
	Alias     string  `json:"alias"`
	Namespace *string `json:"namespace,omitempty"`
}

// DefaultTemplatesResponse defines model for DefaultTemplatesResponse.
type DefaultTemplatesResponse struct {
	Templates []DefaultTemplate `json:"templates"`
}

// DiskSizeMB Disk size for the sandbox in MiB
type DiskSizeMB = int64

// Error defines model for Error.
type Error struct {
	// Code Error code.
	Code int32 `json:"code"`

	// Message Error message.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Message Human-readable health check result.
	Message string `json:"message"`
}

// ListedBuild defines model for ListedBuild.
type ListedBuild struct {
	// CpuCount CPU cores configured for the build.
	CpuCount int64 `json:"cpuCount"`

	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB configured for the build, if recorded.
	DiskSizeMB *int64 `json:"diskSizeMB"`

	// EnvdVersion envd version the build was created with, if recorded.
	EnvdVersion *string `json:"envdVersion"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// MemoryMB Memory in MiB configured for the build.
	MemoryMB int64 `json:"memoryMB"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`

	// Template Template alias when present, otherwise template ID.
	Template string `json:"template"`

	// TemplateId Identifier of the template.
	TemplateId string `json:"templateId"`
}

// MemoryMB Memory for the sandbox in MiB
type MemoryMB = int64

// SandboxRecord defines model for SandboxRecord.
type SandboxRecord struct {
	// Alias Alias of the template
	Alias *string `json:"alias,omitempty"`

	// CpuCount CPU cores for the sandbox
	CpuCount CPUCount `json:"cpuCount"`

	// DiskSizeMB Disk size for the sandbox in MiB
	DiskSizeMB DiskSizeMB `json:"diskSizeMB"`

	// Domain Base domain where the sandbox traffic is accessible
	Domain *string `json:"domain,omitempty"`

	// EventsRetentionExpired Whether the sandbox ended more than the team's events retention window ago, so its events data is no longer available
	EventsRetentionExpired bool `json:"eventsRetentionExpired"`

	// MemoryMB Memory for the sandbox in MiB
	MemoryMB MemoryMB `json:"memoryMB"`

	// RetentionExpired Whether the sandbox ended more than the fixed retention window ago, so its monitoring and logs data is no longer available
	RetentionExpired bool `json:"retentionExpired"`

	// SandboxID Identifier of the sandbox
	SandboxID string `json:"sandboxID"`

	// StartedAt Time when the sandbox was started
	StartedAt time.Time `json:"startedAt"`

	// StoppedAt Time when the sandbox was stopped
	StoppedAt *time.Time `json:"stoppedAt,omitempty"`

	// TemplateID Identifier of the template from which is the sandbox created
	TemplateID string `json:"templateID"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	AddedBy           *openapi_types.UUID `json:"addedBy,omitempty"`
	CreatedAt         *time.Time          `json:"createdAt"`
	Email             string              `json:"email"`
	Id                openapi_types.UUID  `json:"id"`
	IsDefault         bool                `json:"isDefault"`
	Name              *string             `json:"name,omitempty"`
	ProfilePictureUrl *string             `json:"profilePictureUrl,omitempty"`
	Providers         []string            `json:"providers"`
}

// TeamMembersResponse defines model for TeamMembersResponse.
type TeamMembersResponse struct {
	Members []TeamMember `json:"members"`
}

// TeamResolveResponse defines model for TeamResolveResponse.
type TeamResolveResponse struct {
	Id   openapi_types.UUID `json:"id"`
	Slug string             `json:"slug"`
}

// TeamTemplate defines model for TeamTemplate.
type TeamTemplate struct {
	Aliases    []string           `json:"aliases"`
	BuildCount int32              `json:"buildCount"`
	BuildID    openapi_types.UUID `json:"buildID"`
	CpuCount   int64              `json:"cpuCount"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  *struct {
		Email *string            `json:"email,omitempty"`
		Id    openapi_types.UUID `json:"id"`
	} `json:"createdBy"`
	DefaultDescription *string    `json:"defaultDescription,omitempty"`
	DiskSizeMB         *int64     `json:"diskSizeMB"`
	EnvdVersion        *string    `json:"envdVersion"`
	IsDefault          bool       `json:"isDefault"`
	LastSpawnedAt      *time.Time `json:"lastSpawnedAt"`
	MemoryMB           int64      `json:"memoryMB"`
	Names              []string   `json:"names"`
	Public             bool       `json:"public"`
	SpawnCount         int64      `json:"spawnCount"`
	TemplateID         string     `json:"templateID"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

// TeamTemplatesResponse defines model for TeamTemplatesResponse.
type TeamTemplatesResponse struct {
	Data []TeamTemplate `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateDetail Dashboard-shaped single-template read. Mirrors the infra-api `Template` schema fields the dashboard renders.
type TemplateDetail struct {
	// Aliases Aliases of the template.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Aliases []string `json:"aliases"`

	// BuildCount Number of times the template was built.
	BuildCount int32 `json:"buildCount"`

	// BuildID Identifier of the latest ready build for the template, or the zero UUID when none.
	BuildID string `json:"buildID"`

	// CpuCount vCPU count of the latest ready default build, or `null` when none.
	CpuCount *CPUCount `json:"cpuCount"`

	// CreatedAt Time when the template was created.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB of the latest ready default build, or `null` when none.
	DiskSizeMB *DiskSizeMB `json:"diskSizeMB"`

	// EnvdVersion envd version of the latest ready default build, or `null` when none.
	EnvdVersion *string `json:"envdVersion"`

	// LastSpawnedAt Time when the template was last used.
	LastSpawnedAt *time.Time `json:"lastSpawnedAt"`

	// MemoryMB Memory in MiB of the latest ready default build, or `null` when none.
	MemoryMB *MemoryMB `json:"memoryMB"`

	// Names Names of the template (namespace/alias format when namespaced).
	Names []string `json:"names"`

	// Public Whether the template is public or only accessible by the team.
	Public bool `json:"public"`

	// SpawnCount Number of times the template was used.
	SpawnCount int64 `json:"spawnCount"`

	// TemplateID Identifier of the template.
	TemplateID string `json:"templateID"`

	// UpdatedAt Time when the template was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// TemplateTagAssignment defines model for TemplateTagAssignment.
type TemplateTagAssignment struct {
	// AssignedAt Time when the tag was assigned to the build.
	AssignedAt time.Time `json:"assignedAt"`

	// AssignmentId Identifier of the tag assignment event.
	AssignmentId openapi_types.UUID `json:"assignmentId"`

	// BuildCreatedAt Time when the assigned build was created.
	BuildCreatedAt time.Time `json:"buildCreatedAt"`

	// BuildFinishedAt Time when the assigned build finished.
	BuildFinishedAt *time.Time `json:"buildFinishedAt"`

	// BuildId Identifier of the assigned build.
	BuildId openapi_types.UUID `json:"buildId"`
}

// TemplateTagAssignmentsResponse defines model for TemplateTagAssignmentsResponse.
type TemplateTagAssignmentsResponse struct {
	// Data Ready assignment events for the tag, sorted latest first.
	Data []TemplateTagAssignment `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateTagExistsResponse defines model for TemplateTagExistsResponse.
type TemplateTagExistsResponse struct {
	// Exists Whether the template tag has at least one ready assignment.
	Exists bool `json:"exists"`

	// NormalizedTag Normalized template tag name.
	NormalizedTag string `json:"normalizedTag"`
}

// TemplateTagGroup defines model for TemplateTagGroup.
type TemplateTagGroup struct {
	// Assignments Ready assignment events for this tag, sorted latest first.
	Assignments []TemplateTagAssignment `json:"assignments"`

	// HasMore Whether more ready assignment events exist beyond the requested assignment limit.
	HasMore bool `json:"hasMore"`

	// Tag Template tag name.
	Tag string `json:"tag"`
}

// TemplateTagGroupsResponse defines model for TemplateTagGroupsResponse.
type TemplateTagGroupsResponse struct {
	// NextCursor Cursor to pass as `tagsCursor` for the next page, or `null` if there is no next page.
	NextCursor *string            `json:"nextCursor"`
	Tags       []TemplateTagGroup `json:"tags"`
}

// TemplateTagsCountResponse defines model for TemplateTagsCountResponse.
type TemplateTagsCountResponse struct {
	// Total Total distinct ready tags for the template.
	Total int64 `json:"total"`
}

// UpdateTeamRequest defines model for UpdateTeamRequest.
type UpdateTeamRequest struct {
	Name              *string `json:"name,omitempty"`
	ProfilePictureUrl *string `json:"profilePictureUrl,omitempty"`
}

// UpdateTeamResponse defines model for UpdateTeamResponse.
type UpdateTeamResponse struct {
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl,omitempty"`
}

// UserTeam defines model for UserTeam.
type UserTeam struct {
	BlockedReason     *string            `json:"blockedReason"`
	CreatedAt         time.Time          `json:"createdAt"`
	Email             string             `json:"email"`
	Id                openapi_types.UUID `json:"id"`
	IsBanned          bool               `json:"isBanned"`
	IsBlocked         bool               `json:"isBlocked"`
	IsDefault         bool               `json:"isDefault"`
	Limits            UserTeamLimits     `json:"limits"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl"`
	Slug              string             `json:"slug"`
	Tier              string             `json:"tier"`
}

// UserTeamLimits defines model for UserTeamLimits.
type UserTeamLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrentSandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrentTemplateBuilds"`
	DiskMb                   int32 `json:"diskMb"`
	EventsTtlDays            int32 `json:"eventsTtlDays"`
	MaxLengthHours           int64 `json:"maxLengthHours"`
	MaxRamMb                 int32 `json:"maxRamMb"`
	MaxVcpu                  int32 `json:"maxVcpu"`
}

// UserTeamsResponse defines model for UserTeamsResponse.
type UserTeamsResponse struct {
	Teams []UserTeam `json:"teams"`
}

// BuildId defines model for build_id.
type BuildId = openapi_types.UUID

// BuildIdOrTemplate defines model for build_id_or_template.
type BuildIdOrTemplate = string

// BuildIds defines model for build_ids.
type BuildIds = []openapi_types.UUID

// BuildStatuses defines model for build_statuses.
type BuildStatuses = []BuildStatus

// BuildsCursor defines model for builds_cursor.
type BuildsCursor = string

// BuildsLimit defines model for builds_limit.
type BuildsLimit = int32

// SandboxID defines model for sandboxID.
type SandboxID = string

// Tag defines model for tag.
type Tag = string

// TagAssignmentLimit defines model for tag_assignment_limit.
type TagAssignmentLimit = int32

// TagAssignmentsCursor defines model for tag_assignments_cursor.
type TagAssignmentsCursor = string

// TagAssignmentsLimit defines model for tag_assignments_limit.
type TagAssignmentsLimit = int32

// TagGroupsCursor defines model for tag_groups_cursor.
type TagGroupsCursor = string

// TagGroupsLimit defines model for tag_groups_limit.
type TagGroupsLimit = int32

// TagGroupsSearch defines model for tag_groups_search.
type TagGroupsSearch = string

// TagGroupsSort defines model for tag_groups_sort.
type TagGroupsSort string

// TagPath defines model for tag_path.
type TagPath = string

// TeamID defines model for teamID.
type TeamID = openapi_types.UUID

// TeamSlug defines model for teamSlug.
type TeamSlug = string

// TemplateID defines model for templateID.
type TemplateID = string

// TemplatesCursor defines model for templates_cursor.
type TemplatesCursor = string

// TemplatesLimit defines model for templates_limit.
type TemplatesLimit = int32

// TemplatesPublic defines model for templates_public.
type TemplatesPublic = bool

// TemplatesSearch defines model for templates_search.
type TemplatesSearch = string

// TemplatesSort defines model for templates_sort.
type TemplatesSort string

// UserId defines model for userId.
type UserId = openapi_types.UUID

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N409 defines model for 409.
type N409 = Error

// N500 defines model for 500.
type N500 = Error

// N501 defines model for 501.
type N501 = Error

// N502 defines model for 502.
type N502 = Error

// adminApiKeyAuthContextKey is the context key for AdminApiKeyAuth security scheme
type adminApiKeyAuthContextKey string

// adminJWTAuthContextKey is the context key for AdminJWTAuth security scheme
type adminJWTAuthContextKey string

// authProviderBearerAuthContextKey is the context key for AuthProviderBearerAuth security scheme
type authProviderBearerAuthContextKey string

// authProviderTeamAuthContextKey is the context key for AuthProviderTeamAuth security scheme
type authProviderTeamAuthContextKey string

// GetBuildsParams defines parameters for GetBuilds.
type GetBuildsParams struct {
	// BuildIdOrTemplate Optional filter by build identifier, template identifier, or template alias.
	BuildIdOrTemplate *BuildIdOrTemplate `form:"build_id_or_template,omitempty" json:"build_id_or_template,omitempty"`

	// Statuses Comma-separated list of build statuses to include.
	Statuses *BuildStatuses `form:"statuses,omitempty" json:"statuses,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *BuildsLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `created_at|build_id` format.
	Cursor *BuildsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetBuildsStatusesParams defines parameters for GetBuildsStatuses.
type GetBuildsStatusesParams struct {
	// BuildIds Comma-separated list of build IDs to get statuses for.
	BuildIds BuildIds `form:"build_ids" json:"build_ids"`
}

// GetTeamsResolveParams defines parameters for GetTeamsResolve.
type GetTeamsResolveParams struct {
	// Slug Team slug to resolve.
	Slug TeamSlug `form:"slug" json:"slug"`
}

// GetTemplatesParams defines parameters for GetTemplates.
type GetTemplatesParams struct {
	// Public Filter templates by visibility (true = public, false = internal).
	Public *TemplatesPublic `form:"public,omitempty" json:"public,omitempty"`

	// Search Case-insensitive substring match on template names, aliases, and template id.
	Search *TemplatesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort column and direction.
	Sort *GetTemplatesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *TemplatesLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `{sort}|{value}|{templateID}` format. Rejected if its sort does not match the request.
	Cursor *TemplatesCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetTemplatesParamsSort defines parameters for GetTemplates.
type GetTemplatesParamsSort string

// GetTemplatesTemplateIDTagsExistsParams defines parameters for GetTemplatesTemplateIDTagsExists.
type GetTemplatesTemplateIDTagsExistsParams struct {
	// Tag Template tag name to check.
	Tag Tag `form:"tag" json:"tag"`
}

// GetTemplatesTemplateIDTagsGroupsParams defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParams struct {
	// AssignmentLimit Maximum number of ready assignment rows to return per tag.
	AssignmentLimit *TagAssignmentLimit `form:"assignmentLimit,omitempty" json:"assignmentLimit,omitempty"`

	// TagsLimit Maximum number of distinct tags to return per page.
	TagsLimit *TagGroupsLimit `form:"tagsLimit,omitempty" json:"tagsLimit,omitempty"`

	// TagsCursor Cursor returned by the previous list response in `{sort}|{latest_assigned_at}|{tag}` format (sort-tagged, RFC3339Nano).
	TagsCursor *TagGroupsCursor `form:"tagsCursor,omitempty" json:"tagsCursor,omitempty"`

	// Search Case-insensitive substring filter on tag name. Allowed characters are `a-z`, `0-9`, `.`, `_`, `-`.
	Search *TagGroupsSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort order for the returned tag groups.
	Sort *GetTemplatesTemplateIDTagsGroupsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetTemplatesTemplateIDTagsGroupsParamsSort defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParamsSort string

// GetTemplatesTemplateIDTagsTagAssignmentsParams defines parameters for GetTemplatesTemplateIDTagsTagAssignments.
type GetTemplatesTemplateIDTagsTagAssignmentsParams struct {
	// Cursor Cursor returned by the previous list response in `assigned_at|assignment_id` format.
	Cursor *TagAssignmentsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of assignment rows to return per page.
	Limit *TagAssignmentsLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAdminTeamsBootstrapJSONRequestBody defines body for PostAdminTeamsBootstrap for application/json ContentType.
type PostAdminTeamsBootstrapJSONRequestBody = AdminTeamBootstrapRequest

// PostAdminUserProfilesByEmailJSONRequestBody defines body for PostAdminUserProfilesByEmail for application/json ContentType.
type PostAdminUserProfilesByEmailJSONRequestBody = AdminAuthProviderProfilesLookupEmailRequest

// PostAdminUserProfilesResolveJSONRequestBody defines body for PostAdminUserProfilesResolve for application/json ContentType.
type PostAdminUserProfilesResolveJSONRequestBody = AdminAuthProviderProfilesResolveRequest

// PostAdminUsersBootstrapJSONRequestBody defines body for PostAdminUsersBootstrap for application/json ContentType.
type PostAdminUsersBootstrapJSONRequestBody = AdminAuthProviderUserBootstrapRequest

// UpsertProjectJSONRequestBody defines body for UpsertProject for application/json ContentType.
type UpsertProjectJSONRequestBody = AdminControlPlaneProjectUpsertRequest

// UpsertProjectLimitsJSONRequestBody defines body for UpsertProjectLimits for application/json ContentType.
type UpsertProjectLimitsJSONRequestBody = AdminControlPlaneProjectLimits

// UpsertProjectMemberJSONRequestBody defines body for UpsertProjectMember for application/json ContentType.
type UpsertProjectMemberJSONRequestBody = AdminControlPlaneMemberUpsertRequest

// PostTeamsJSONRequestBody defines body for PostTeams for application/json ContentType.
type PostTeamsJSONRequestBody = CreateTeamRequest

// PatchTeamsTeamIDJSONRequestBody defines body for PatchTeamsTeamID for application/json ContentType.
type PatchTeamsTeamIDJSONRequestBody = UpdateTeamRequest

// PostTeamsTeamIDMembersJSONRequestBody defines body for PostTeamsTeamIDMembers for application/json ContentType.
type PostTeamsTeamIDMembersJSONRequestBody = AddTeamMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bootstrap team
	// (POST /admin/teams/bootstrap)
	PostAdminTeamsBootstrap(c *gin.Context)
	// Lookup user profiles by email
	// (POST /admin/user-profiles/by-email)
	PostAdminUserProfilesByEmail(c *gin.Context)
	// Resolve user profiles
	// (POST /admin/user-profiles/resolve)
	PostAdminUserProfilesResolve(c *gin.Context)
	// User profile
	// (GET /admin/user-profiles/{userId})
	GetAdminUserProfilesUserId(c *gin.Context, userId UserId)
	// Bootstrap auth provider user
	// (POST /admin/users/bootstrap)
	PostAdminUsersBootstrap(c *gin.Context)
	// Delete user
	// (DELETE /admin/users/{userId})
	DeleteAdminUsersUserId(c *gin.Context, userId UserId)
	// Delete a project and its control-plane state.
	// (DELETE /admin/v1/projects/{teamID})
	DeleteProject(c *gin.Context, teamID TeamID)
	// Create or reconcile a project.
	// (PUT /admin/v1/projects/{teamID})
	UpsertProject(c *gin.Context, teamID TeamID)
	// Reconcile effective limits for a project.
	// (PUT /admin/v1/projects/{teamID}/limits)
	UpsertProjectLimits(c *gin.Context, teamID TeamID)
	// Remove a project member.
	// (DELETE /admin/v1/projects/{teamID}/members/{userId})
	DeleteProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Reconcile an opaque user UUID as a project member.
	// (PUT /admin/v1/projects/{teamID}/members/{userId})
	UpsertProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Purge shard-local membership and access-token state for an opaque user UUID.
	// (DELETE /admin/v1/users/{userId})
	PurgeUser(c *gin.Context, userId UserId)
	// List team builds
	// (GET /builds)
	GetBuilds(c *gin.Context, params GetBuildsParams)
	// Build statuses
	// (GET /builds/statuses)
	GetBuildsStatuses(c *gin.Context, params GetBuildsStatusesParams)
	// Build details
	// (GET /builds/{build_id})
	GetBuildsBuildId(c *gin.Context, buildId BuildId)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Sandbox record
	// (GET /sandboxes/{sandboxID}/record)
	GetSandboxesSandboxIDRecord(c *gin.Context, sandboxID SandboxID)
	// List user teams
	// (GET /teams)
	GetTeams(c *gin.Context)
	// Create team
	// (POST /teams)
	PostTeams(c *gin.Context)
	// Resolve team identity
	// (GET /teams/resolve)
	GetTeamsResolve(c *gin.Context, params GetTeamsResolveParams)
	// Update team
	// (PATCH /teams/{teamID})
	PatchTeamsTeamID(c *gin.Context, teamID TeamID)
	// List team members
	// (GET /teams/{teamID}/members)
	GetTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Add team member
	// (POST /teams/{teamID}/members)
	PostTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Remove team member
	// (DELETE /teams/{teamID}/members/{userId})
	DeleteTeamsTeamIDMembersUserId(c *gin.Context, teamID TeamID, userId UserId)
	// List team templates
	// (GET /templates)
	GetTemplates(c *gin.Context, params GetTemplatesParams)
	// List default templates
	// (GET /templates/defaults)
	GetTemplatesDefaults(c *gin.Context)
	// Template
	// (GET /templates/{templateID})
	GetTemplatesTemplateID(c *gin.Context, templateID TemplateID)
	// Count template tags
	// (GET /templates/{templateID}/tags/count)
	GetTemplatesTemplateIDTagsCount(c *gin.Context, templateID TemplateID)
	// Check ready template tag existence
	// (GET /templates/{templateID}/tags/exists)
	GetTemplatesTemplateIDTagsExists(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsExistsParams)
	// List template tag groups
	// (GET /templates/{templateID}/tags/groups)
	GetTemplatesTemplateIDTagsGroups(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsGroupsParams)
	// List ready assignments for a single template tag
	// (GET /templates/{templateID}/tags/{tag}/assignments)
	GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context, templateID TemplateID, tag TagPath, params GetTemplatesTemplateIDTagsTagAssignmentsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAdminTeamsBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminTeamsBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminTeamsBootstrap(c)
}

// PostAdminUserProfilesByEmail operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesByEmail(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesByEmail(c)
}

// PostAdminUserProfilesResolve operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesResolve(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesResolve(c)
}

// GetAdminUserProfilesUserId operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUserProfilesUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUserProfilesUserId(c, userId)
}

// PostAdminUsersBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUsersBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUsersBootstrap(c)
}

// DeleteAdminUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminUsersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminUsersUserId(c, userId)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProject(c, teamID)
}

// UpsertProject operation middleware
func (siw *ServerInterfaceWrapper) UpsertProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProject(c, teamID)
}

// UpsertProjectLimits operation middleware
func (siw *ServerInterfaceWrapper) UpsertProjectLimits(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProjectLimits(c, teamID)
}

// DeleteProjectMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProjectMember(c, teamID, userId)
}

// UpsertProjectMember operation middleware
func (siw *ServerInterfaceWrapper) UpsertProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProjectMember(c, teamID, userId)
}

// PurgeUser operation middleware
func (siw *ServerInterfaceWrapper) PurgeUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PurgeUser(c, userId)
}

// GetBuilds operation middleware
func (siw *ServerInterfaceWrapper) GetBuilds(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsParams

	// ------------- Optional query parameter "build_id_or_template" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "build_id_or_template", c.Request.URL.Query(), &params.BuildIdOrTemplate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id_or_template: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "statuses", c.Request.URL.Query(), &params.Statuses, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statuses: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuilds(c, params)
}

// GetBuildsStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsStatuses(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsStatusesParams

	// ------------- Required query parameter "build_ids" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "build_ids", c.Request.URL.Query(), &params.BuildIds, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_ids: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsStatuses(c, params)
}

// GetBuildsBuildId operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsBuildId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "build_id" -------------
	var buildId BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "build_id", c.Param("build_id"), &buildId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsBuildId(c, buildId)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetSandboxesSandboxIDRecord operation middleware
func (siw *ServerInterfaceWrapper) GetSandboxesSandboxIDRecord(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "sandboxID" -------------
	var sandboxID SandboxID

	err = runtime.BindStyledParameterWithOptions("simple", "sandboxID", c.Param("sandboxID"), &sandboxID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sandboxID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSandboxesSandboxIDRecord(c, sandboxID)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeams(c)
}

// PostTeams operation middleware
func (siw *ServerInterfaceWrapper) PostTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeams(c)
}

// GetTeamsResolve operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsResolve(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamsResolveParams

	// ------------- Required query parameter "slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "slug", c.Request.URL.Query(), &params.Slug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsResolve(c, params)
}

// PatchTeamsTeamID operation middleware
func (siw *ServerInterfaceWrapper) PatchTeamsTeamID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTeamsTeamID(c, teamID)
}

// GetTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsTeamIDMembers(c, teamID)
}

// PostTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamsTeamIDMembers(c, teamID)
}

// DeleteTeamsTeamIDMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamsTeamIDMembersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTeamsTeamIDMembersUserId(c, teamID, userId)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesParams

	// ------------- Optional query parameter "public" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "public", c.Request.URL.Query(), &params.Public, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter public: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplates(c, params)
}

// GetTemplatesDefaults operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesDefaults(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesDefaults(c)
}

// GetTemplatesTemplateID operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateID(c, templateID)
}

// GetTemplatesTemplateIDTagsCount operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsCount(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsCount(c, templateID)
}

// GetTemplatesTemplateIDTagsExists operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsExists(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsExistsParams

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", c.Request.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsExists(c, templateID, params)
}

// GetTemplatesTemplateIDTagsGroups operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsGroups(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsGroupsParams

	// ------------- Optional query parameter "assignmentLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignmentLimit", c.Request.URL.Query(), &params.AssignmentLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter assignmentLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsLimit", c.Request.URL.Query(), &params.TagsLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsCursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsCursor", c.Request.URL.Query(), &params.TagsCursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsCursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsGroups(c, templateID, params)
}

// GetTemplatesTemplateIDTagsTagAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag TagPath

	err = runtime.BindStyledParameterWithOptions("simple", "tag", c.Param("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsTagAssignmentsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsTagAssignments(c, templateID, tag, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/admin/teams/bootstrap", wrapper.PostAdminTeamsBootstrap)
	router.POST(options.BaseURL+"/admin/user-profiles/by-email", wrapper.PostAdminUserProfilesByEmail)
	router.POST(options.BaseURL+"/admin/user-profiles/resolve", wrapper.PostAdminUserProfilesResolve)
	router.GET(options.BaseURL+"/admin/user-profiles/:userId", wrapper.GetAdminUserProfilesUserId)
	router.POST(options.BaseURL+"/admin/users/bootstrap", wrapper.PostAdminUsersBootstrap)
	router.DELETE(options.BaseURL+"/admin/users/:userId", wrapper.DeleteAdminUsersUserId)
	router.DELETE(options.BaseURL+"/admin/v1/projects/:teamID", wrapper.DeleteProject)
	router.PUT(options.BaseURL+"/admin/v1/projects/:teamID", wrapper.UpsertProject)
	router.PUT(options.BaseURL+"/admin/v1/projects/:teamID/limits", wrapper.UpsertProjectLimits)
	router.DELETE(options.BaseURL+"/admin/v1/projects/:teamID/members/:userId", wrapper.DeleteProjectMember)
	router.PUT(options.BaseURL+"/admin/v1/projects/:teamID/members/:userId", wrapper.UpsertProjectMember)
	router.DELETE(options.BaseURL+"/admin/v1/users/:userId", wrapper.PurgeUser)
	router.GET(options.BaseURL+"/builds", wrapper.GetBuilds)
	router.GET(options.BaseURL+"/builds/statuses", wrapper.GetBuildsStatuses)
	router.GET(options.BaseURL+"/builds/:build_id", wrapper.GetBuildsBuildId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/sandboxes/:sandboxID/record", wrapper.GetSandboxesSandboxIDRecord)
	router.GET(options.BaseURL+"/teams", wrapper.GetTeams)
	router.POST(options.BaseURL+"/teams", wrapper.PostTeams)
	router.GET(options.BaseURL+"/teams/resolve", wrapper.GetTeamsResolve)
	router.PATCH(options.BaseURL+"/teams/:teamID", wrapper.PatchTeamsTeamID)
	router.GET(options.BaseURL+"/teams/:teamID/members", wrapper.GetTeamsTeamIDMembers)
	router.POST(options.BaseURL+"/teams/:teamID/members", wrapper.PostTeamsTeamIDMembers)
	router.DELETE(options.BaseURL+"/teams/:teamID/members/:userId", wrapper.DeleteTeamsTeamIDMembersUserId)
	router.GET(options.BaseURL+"/templates", wrapper.GetTemplates)
	router.GET(options.BaseURL+"/templates/defaults", wrapper.GetTemplatesDefaults)
	router.GET(options.BaseURL+"/templates/:templateID", wrapper.GetTemplatesTemplateID)
	router.GET(options.BaseURL+"/templates/:templateID/tags/count", wrapper.GetTemplatesTemplateIDTagsCount)
	router.GET(options.BaseURL+"/templates/:templateID/tags/exists", wrapper.GetTemplatesTemplateIDTagsExists)
	router.GET(options.BaseURL+"/templates/:templateID/tags/groups", wrapper.GetTemplatesTemplateIDTagsGroups)
	router.GET(options.BaseURL+"/templates/:templateID/tags/:tag/assignments", wrapper.GetTemplatesTemplateIDTagsTagAssignments)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rc9w2lvZfQfGdqjezxZbkS6Y2qpoPluVMPBtnXJY02SqXtwWRp7sxJgEGAHWxRv99CxeSIAmSYEut",
	"WFl/SawmiMs5Dw7ODYe3UcLyglGgUkSHt1GBOc5BAtd/XZQkS5ckVf9OQSScFJIwGh1Gb1OgkqwIcMRW",
	"SG4A6bZ7URwR9bzAchPFEcU5RIdNP3HE4beScEijQ8lLiCORbCDHaoAV4zmW0WFUlrqlvCnUu0JyQtfR",
	"3V1cd7NkfCkhLzIsoT+1f+h/4AytSCaBo4sbMzdE6jnHqHq99SPjze84I1jUy/mtBH7TX09rIu5ahucu",
	"+hN+zfIcLwQo2ktIUUaEVFQ1s357LJBkaA0SCYllKUCgFeNqanBdZCyF6HCFMwHjUxWjtCcSchHAhDjK",
	"8fVb0/jZwUH9HHOO1aAlJb+VYBuoQe7iSMibTLVRXUc1Jaq1zCVHTQPJEKFJVqYQSop6SO/K/8RhFR1G",
	"/2+/2RD7ppnYP1JDn+jX1Qpaix5aoVgmJReMexaof0ccZMkppAqgagMVHC4JK4VZMAdRMCoAEYrOEw6K",
	"FEss/13x8xwZVg1B1A4eAEqxzEhOZH+e7/A1ycsc0TK/MPtcE0tR3swdFcBRgdcwNAnTsTuHFFa4zGR0",
	"+P1B3ICNUPnieaTBpUa02MoJtX/VJCdUwhq4nrzANL1g12+PQ6STbTwgn5quxjZJn34Sr/uDn1YiROI1",
	"UgMogiUbSD4PkUl1MzZwTujPQNdy45KiPY0lFoKsaQ5UhrOTA05vUPMm4uyqy16J10PTbl78eZjPfxlj",
	"8/PvJ7ncXttDbirTq9lVDvUeaGt15x3MlHF2/G67Ta1nzVlZPCQLbgXj8u7ft2q7CLl0OHL371uJ13cV",
	"K9B3quVC4vUa0hh9+PH1ixcvfvgFU/bnkU0lXodyyq4smEkpEZLQRKrtMYdFqvnIZlH74cHYJADzZONh",
	"ExawIFQAFUSSS0CivDDkqDQmRmvZtYdeZRm7ghQlG8xxojRDhDmgc7z4ch6j84PFD+p/e+o/S/WfxfnQ",
	"4u2EWpINX1eS7S8vYyWVJXD16v98xIsvB4sf9paLT//xpyge55sCR3+hJ4xLxHgKXKFIY7HGplqfeXlw",
	"tqpPL5ciC1c1mlI9qGLHx86vNaQT26X7T93m09Ci9Nk0fawMnGX3PkwA52Fnqmo5NAnTyf3UfdXJSVZ6",
	"j1icI5GVa7P1BMsuB7ecajb3WLekDiWDaT1Iirqz7WaxC4F7ibMSlIytJ1eL2j30Af4FidK8idL4BFLv",
	"oJSBQJRJlGOZbOxm+q0Ecc9jsl7k01RCm/kX5UVGkv4CfjQytW6ouHRJBLkgGZE36DsFBPRXZF6PkbZf",
	"0F+RGoRTnA2eb3Y8D3kvGMsA0878tjgODKvVaVDJHjW2iI1xrP9BU9eUniH5x6AwIs4TlpU51eOmhEOi",
	"nm0hwRuDqivFnSdGYPeblkXabuL8MCzZSwH8bZAnRbUcECa2k/vI1Tv1shEJ2u59eXCg/pcwKoFqsuOi",
	"yEiC1fz2/yXUJG+d/sfs5DecM27GaC/yCKeVuFAG8suDZ7sf81UpN4q0plcEpp0a/MXuB/+R8QuSpkDN",
	"iC93P+IvTKIVK2lqRvxh9yO+ZnSVkURz9PvHQNEJ8EvgDSe/fwwY/aMAbhBEzAFI8iIDZZ9BaibxfPeT",
	"OCuE5ErpsWu/q3a83sKv0lRpRO9AHZEf7DY7vI0KzgrgkpiNDjkmWUtCmF98wqoRLx9tq0amsQulHqil",
	"v0pzQtU2e8/ZJUmBv+dsRTIYGbu9rDfqZ4TTlIMQaMVZrgVgwuiKrEsOKcKl3KDCdq+EIi2zDF+oMYzg",
	"6zkoB+WsPVDRm+dHWsQ6rl/V8bQ+6hKlFsTzqSN+ZuxzWei1fwXMEh+M/jw4FbNUcS83cU5o9WeAz9hL",
	"azF7VfqM66+nsC2Cvb+DMO+5gjsTr0cKmvmZAH7EmBSS42KQG4ykyZIIUQKftOZi01rRbxkMKPclE/kJ",
	"HsMoKbfTe1SQNS2LJSk8mmD9VHeJ11aojsPepUpnAX0iDHLjNaOSs+x9hikYYXpWCOBykBk4TSFdXtwE",
	"2rOTg77nTD9TXWfZP1bR4ccAaHp6aM/7Lu5O3DB2nsgjqYdyn0aWoR1dok+1hNGk5ByoXFrHO7SFSm2J",
	"jdhesdtNZTosTUBji85SIj4v84vum395OfkmXGr/rpTZMsU324yd4+slx/l2w6uXLRWXmd6lyw0r+bbz",
	"uEyKcvarHaB4+TsyU2fkFjEarowyu8+CTzP22qlueFvbfylcQsYKpd8p21HitdoLsYJwWmpz02PeDXc/",
	"IUAqien4QZ9/b4IiYyK3MJ0vpZ38NiJCL1xJW+thc12xL+JJN6HLcL2KuPK0tSY3yAqlsE6fdgN64xHJ",
	"MkLX+0rpxolEulnt5K38ktMnXUV+j3ex8rBuQYfhU0bHkd/SFfMIReNmeOVxfOi3kG6gzBBJchAS5wUi",
	"tIqEOBGretUplrBQjX0rXxFKxGZ0PKbsnKkRY0RWqOpscPhJhUD7lUZ83vo54pDpjADJkNwQYTIC9Azw",
	"JSZ6BO03qZS6/jD+eTiBfB3in5cNYF56B0LgtQdNP2KSlRxQbhqgqw1Qm8WgLMrzFSYZpOcxYnID/IoI",
	"QOdqnucB1k5X8NYYajG4Xld3roMQPanp4EOGnXyOiwJSvetSLDYXDPMUJRlRtNpzPGqaS0aImrWqeZRJ",
	"AkJ4RakzA2UU9LfKV4bdmelRk6bTEwehXlQNOA8MJ9EnfiZCDttvKZbhmTuqK0h1t77MHQrX8vV4dEUy",
	"VGAhjNABpN6oAiv60NJpY4ZYCk+KfmBcRaZtFZqYR0W9yNb8hsl1YvOahkl20YDFJ2Z/9mZYuZI0EIl6",
	"v05Zxe3J+Jb1+v3Za1ZSz/Z+/f4MJYybFDg3sSeK5yrOr7WwVGf9w2pnPp3At8hjE4w4dfIYO8alCbIE",
	"Q73T4Sv1ug/zmv41fXuKfp9S+oW3aZDfp6XGhKkiQC/TfwIXxHhKA+VtXyeu42/dMFgccZy/8xtX/dWK",
	"Al9RL3kGXpBM4uyYiM8n5AsMDDOwKKcXn+HlHdAnbiuoNLyq1mw77s8ybmkLdTDRAUeLFAEINoDzw9iv",
	"jSmlrsBJiM+os2rTacCkRoRiHW/cdodNSrpmBO9MK2Yc9eWceoYE+QJdOae0mHfkaFTcHfjwZUILHl9M",
	"6lEXdGOknu1FcYiIyIcUD9OTfbw36WPS02m685HtJ8CZ3AyzdXAqP5U5pgsOOFU4Qxvdj0nMRBxEmcnp",
	"+Y1NzFU1+nQuyskjzQl7VFzva43DcuiRLcg0CL4GroNL0yo4h4TxFPzrnJacnfOjPRP1EF2ap82w6AoL",
	"ZOmFrojc9OYxeQr9wY2QHHLGb3y8faefTDE2ELNPzdZpslRGnBX6cDLDFhwEUOmOVafLvD3ei0YGCMsV",
	"cZPPAuwy57KKM86ggyAedinUAs3BSksotDemT2C+m8LYFmffs+f/6cPZienhg97hIzpKJ4NEM7JDaa/W",
	"60j3MSDXhk1Pfo6qHU1L9R7LMfFIuiMsAJmHCnscWqSTHK9WJFEbAGvXC1EgD8C78a1/AKmQx+ib68IA",
	"qjv8rxtQEG8NCjSFFOVMzwXT2jn7/wUy3SJe9YuuCE3ZFcJrFiPBdN6hbaNMYWtQZ4yugTfevoYXjrLv",
	"iq4xstbw0xvloda3IteQjq8rZ5RIpjPsME1RxtbzF7nN5ZcBZxMfUBpOSW6Fp7tmdXLal4JVBSFZUcwf",
	"RL+09Ym4XRKvSUK52pBko9jhTsqKwklB20r4dW8WNbQOEp89TA5uRp9wbRKCBsLWR96o9SRZpw38aZFS",
	"BXUGtJhJ5YSI4yqT02ftB6ch2PyM9ySRJYcz3s6PKDkJWU2VnNQ2I/twHDMUSZNJ5K6uY6PXA43zW4zZ",
	"RrpBsMHrgGhqCVXXQ3Ors4yG5hbI+ypcGeKEVk2H5jPP7zbBzq2dasdhTjVHvZhrCIZJaPuKkQldyA+E",
	"ZANtkgdIMomrzO1jV4oHzKCtY93ftpxe8rhkyrCQJwW+ovcToK6GE4CHOrgaDucxZ+p8B2nrJO4nbJrs",
	"+XC4jp231bYKOmFrr2fjPzW0agveZoLuRulys0WYjiPVhZELkinhJB4oCtYSeH+8MFi1tGOQ3nSR4yo8",
	"vRAbXECKBKHrDBa10scBp3voHeGccaP0EbrieIELgs6r3s+RISdaEchS06wJfHNlDHAd+B48TlIoOCRa",
	"ibSr99ibILwXy7Y8iTp3BOpLVNoj1dZ8ldKtXpaBPl/nBJvSrs1lSHvf3HjgmmQdM7ypvrEB9AU4Q2dn",
	"b4+NWUAZhb2pQzEsWbKxvj91KX9pvLAlld4p2+On8lk2SG9NsQ3tcY9s2+5p8cC+ta0nNowWrk+hR42e",
	"+/YBaRLurX2oQT0U653DwcxRb6JS3MdV657eYcxqPBU9VrW9sQ/Ip4GMrF90IlbXaP6uDuXtG+envbVv",
	"hqiepX+eJ8mGblS6rpjm8qGwVyjVChnNbhw/V3UxtkoMnNJpZgrNHhxCVaF7OHc7atNM/JpXQyXM76lv",
	"badjjSkJp3j9qi6x4bH+bA2KALritSZp9UalGvXjH6PSu6n3Eejxx2u3Roh2CQWFdAy1Qo+kelW9gFn4",
	"0vSrP44EykaHvH9QzElcmaJqe+z598FaXHTTMBw89VjQp1AwcAMsg/aSP3Rr/Vjveq2H4XWsb/pDWp0f",
	"K8Lt7f4wG8O3v/64xsYpXr+5JmKME6CfBx5gal9vlDiRKAMlpRmFXoUm/+lFFVQz8gXSU19Bql/qx+3R",
	"qhT3iRuFZhHdUSZI8zfOymJIuuZVtcE5ECXiETG6weId4zDMOh304QMT1iRDF3DDaOpWyoDUbazrUvgZ",
	"GlZXbJp3phaMS/RmaSEMHMH2jF2MBTpvqjGd1yKn3qoPtJ013eY4tztonUznUr3PkQ9C6yYjGWhMYo+7",
	"4lT93JSYMijThaa6RnOQ1tldhR7UN/MzrXd1MmJzQt87k34WP9gNpn7oZVpcj875npGFaiUPNddePGIw",
	"FfhMAFdL8CRuZyz5DOkHwCLQA71NAu7943FHmFJI/f5iIo7MKoYej7vM60ukY3u5oqC9cvrQ3BwMO8WR",
	"JCbCGsr/+pqcfrGJ+vWn5VLOoXHcAUU7YGjJ5eJgDHHTV3RPRm/ojt3KrQTh0fCdXP893H4O9UBjc9ye",
	"yux46OKt95KrkUs/+W7JDpjtOb7+4EshHx7jn0P3aCekc2d6sZcTI1RuBndmXZO1S7IxaIxmTuM8/Jyt",
	"pdt0urTqtj8ntf0gKTmRNyeqT7BFT3JCXxXkv+DmVWkK5umCSRvAqd5ZtmTSfy90y8Up+wy0YQDWb9bX",
	"Uf/+62nVywVgDvzHinF///W0KiKlRZN+2vSzkVJrDm4lhyPdZqA/45ZaSjudWR0rMk4sVjVZaIdMZ6GK",
	"jMRePZVE6oLFb54foTo4gl69fxvF0WXlnI0O9p7tHegKDwVQXJDoMHqxd7B3EOlCjRvNhX2sqLevWbd/",
	"Ud3n1ZBhwpftrMWS0IlPOqFBjSUQ1r45rd9ginSfC9zUb1J2edU3umL88ypjV0r5YVVxHmXlR++ZkPXl",
	"YlHfLrblskDII5bePFixnuFrzHdtZFuPaqvq1vMHrJfkS6/wVU8ydy5XZZbdNOQstFWI8z1TNupgaLB6",
	"9vuqUVPDa6rtM6c61Hjb702/tp7SVNvnLbmgXeg9ifDx092nOBJlnmN+Ex1GNaP0iqPKXvgYacBFn1SP",
	"FtClAL6o6rfsX9wsaiWpwvUA9JS0q2rQHN28saf7zvAXWF/okRE5XZVnCp+6kpkpQEjoGlWc+EpQOht5",
	"hiWm7FS1FnRxg+rKBIFAtLVOZ+LQCofHxmGnsNSTw6Aldvrk0WcZ0YbfDNTdmgpcd2p+a/Cg7m/QB91Z",
	"VSHN/aTIQKCzabJvC6upBXz14skS6KnC4syBwyQaBrS7EenzOArYZAW1p6aMmeqvTxNRjYLVqtuo1+Qg",
	"zBp6PYS5ciaFDHy3rI7178pi0NLsQonpnF0qJUHnbenInrxpxja3+mJk68HpxwRM+RJC16aGsYlM7+lp",
	"IO6zLcy4DbgfXLy99FQ8dkFiCPII+LDVaqfavnTqzE61/WHHuDPM6cKsL8gun+3b6lRi/9bUqO+Azcf0",
	"qipfCMtsW33fUMcw8IXQcbuvxrp6FtL22QATajfJAAcwsvTVu4pIfalZcpYtigxTMGTZc3ikjHmdHLSo",
	"uDV3R9lPDajpFKXnTDIV2Fwe7ugkmi7D+DsowL7qkp7jSEeyraGl2aekJk1IBqmG7vMHrLQ8Z17VdqpT",
	"T3Yq93Yhy3a35YwrDTHeMKvZf+N7bFwi7jcxlx1uxZ+rSMVjbsgqPhSyEz3S/c1qBYn+SIIhkf4Sjrih",
	"yYYzSr7sHKDhB/PXANAPNSyhSzft6H0QrNp7ZwO648hxbu+1hbDd3qvbkOKRTvSnx+mcXbqnv+HKbg76",
	"eI6SPS2HHBw8ghzylZW+63+UIwCGtrTENxx6JQ6miBX4t9I6vfR9EixmIrQlesZM1I4XpORrOBOBwkU1",
	"XLArCikSG8zT/3OmgyaXWfsiYwnOLG800JUZYSKmCx0xtdSxgcIuix9W4NRiROGgqSw+5AGtI/DzRvF+",
	"SzhAyHU+oxv6RvWhrfD29jteO/XIeup+Tnvn7VfPCrwm1MSIdS87logvQtq+uKfDYyCZ4OOnoXyAXsCJ",
	"CGli6nWV9Gpj2B+MeDN/7LtfYx7H90lTHXQ7nIvHQFKvJGowmjo1UL9BqVX0GaaAdFux+W4aSkf1JYnt",
	"kPQIQNK12mdiJ9W3kCsxtBs87EYx2xV2LEWGoGMqMY7hxdR8jHbI7U5VSQ/Lf3LrRYqa/4Zq9YLdVvrR",
	"fv0JjP3buhjQ3T6vK5ENrblO9zup3rLVy+Zul6YE0U73S7vEWvCeqaorfds1DYgsKW3oytk2zedUzM6p",
	"EzEtiLr3aRSNBcJZplUBc3W1nVZngmiQMaq/Yx3rapi1d4um9fXhVWY+BN/Dqc612+XW7CekBoNLr04v",
	"fe8Ro6SD/PeoaM0MPfHReCTM3pD94b0W/dLoTyCIXpVz/YqSGbdFhvXsd5IU3ai5ybd1ssEGBIB+XqfX",
	"Vl/MduowVvHyGF3ijKRYVoF084VE9WrjKfHv/Sa7bL4/T3/ee6fH0jZQqhO/HCz9MU8kf56YBkuFjFEE",
	"ukH0AkvzfemOsFI/a6CcVh+F3zqqtAth17/19sjCznOFbQqgtkLC7mXdU7FRDQ2nJWY3bDSmgDuYtZ73",
	"+0F3hwKuW/gxWEHSO93SYu+P7wvLaz7OVrUeEAi7CDN5PgAdJMaeTWSd6VKxLvG+GnHzVIy5V2mLfrPE",
	"04yodh+kW2YobhVmnZnLqFM2v1Jc/Z5YsXH0ELg4364ZN/6d+Ehmv/Pl6P91R+g719pvfiY0IxRiVNIM",
	"hKhfVaYBowijFFLrSkiyUkjgf7Y+hBXJJHCdYSsA82RjMm0TlpU51VU8lKlxSTD6DDcCJDJxpmq6hNEB",
	"k6Na+Xxg2zeXtg5VAMSbd8waZr7DuJz3RnBsrnnlMcJz/pqkW0To6ml/2+4txUQ6qG72e/31qPae37e7",
	"dHrz62KAdtP3t7bepnIDhFfVdEwAg9AVM4F3U6ZtfB8eV5PZIf4GP+oVDMHe6r9Wh2BvokGIuG2K8t0F",
	"HAmm/m1TDcqkn9gqibawgDEuUa92LgecxojQFK7tO+0P2gwj5dQtHLid7N69MdWqJBxuR7WK8nzTeusq",
	"SLPRu6+a7ydVKc5J8abLGSFa1+gMLZsUAtO6hNNXj9d+salw6OK1qXz8DbfRYaSJ2CqTJ7aEcFP8z4vh",
	"1xtIPuuvhOl6cniLQoChEH5TVfDbHsMBCilePxrUO3UXJyNDitTd4oeaPUAT+ObQmLtF7BcztXj1knTL",
	"HbPWJQcnpb5nZKeqounE6LYXrNRf6CqAL/SuIkIyfhM7Bgm7BG4OCf1GyxSds8dMucTd77Fls9QZxiJe",
	"Lw1dtnqnsjBnvTTDXnZe0gbzI0mRToXLGT5zB3lm4t9kyHaWb4+QW0qOW4nXd/ud4rIhQsRTS7u6nFTZ",
	"SHgdI8ZT4JAiCld10dnYIzGCnVdt4dGu7PwIQqTAcjNf4MyVBO6bVu480tb21cmepRA7oDDFZ7/t7/n7",
	"u6uzdneWs/2H9n1d0/djVWm2Sh1VGLS/NFlxzo/GW976oepX/dip6lzdFelcV9c3R1C9jUUneU4LAAH8",
	"kiSA/v7rqfaU2eG610/uPt39bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
