// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminApiKeyAuthScopes        adminApiKeyAuthContextKey        = "AdminApiKeyAuth.Scopes"
	AdminJWTAuthScopes           adminJWTAuthContextKey           = "AdminJWTAuth.Scopes"
	ApiKeyAuthScopes             apiKeyAuthContextKey             = "ApiKeyAuth.Scopes"
	AuthProviderBearerAuthScopes authProviderBearerAuthContextKey = "AuthProviderBearerAuth.Scopes"
	AuthProviderTeamAuthScopes   authProviderTeamAuthContextKey   = "AuthProviderTeamAuth.Scopes"
)

// Defines values for BuildStatus.
const (
	Building BuildStatus = "building"
	Failed   BuildStatus = "failed"
	Success  BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case Building:
		return true
	case Failed:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for TagGroupsSort.
const (
	TagGroupsSortLatestAsc  TagGroupsSort = "latest_asc"
	TagGroupsSortLatestDesc TagGroupsSort = "latest_desc"
	TagGroupsSortNameAsc    TagGroupsSort = "name_asc"
	TagGroupsSortNameDesc   TagGroupsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the TagGroupsSort enum.
func (e TagGroupsSort) Valid() bool {
	switch e {
	case TagGroupsSortLatestAsc:
		return true
	case TagGroupsSortLatestDesc:
		return true
	case TagGroupsSortNameAsc:
		return true
	case TagGroupsSortNameDesc:
		return true
	default:
		return false
	}
}

// Defines values for TemplatesSort.
const (
	TemplatesSortCreatedAtAsc  TemplatesSort = "created_at_asc"
	TemplatesSortCreatedAtDesc TemplatesSort = "created_at_desc"
	TemplatesSortUpdatedAtAsc  TemplatesSort = "updated_at_asc"
	TemplatesSortUpdatedAtDesc TemplatesSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the TemplatesSort enum.
func (e TemplatesSort) Valid() bool {
	switch e {
	case TemplatesSortCreatedAtAsc:
		return true
	case TemplatesSortCreatedAtDesc:
		return true
	case TemplatesSortUpdatedAtAsc:
		return true
	case TemplatesSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesParamsSort.
const (
	GetTemplatesParamsSortCreatedAtAsc  GetTemplatesParamsSort = "created_at_asc"
	GetTemplatesParamsSortCreatedAtDesc GetTemplatesParamsSort = "created_at_desc"
	GetTemplatesParamsSortUpdatedAtAsc  GetTemplatesParamsSort = "updated_at_asc"
	GetTemplatesParamsSortUpdatedAtDesc GetTemplatesParamsSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesParamsSort enum.
func (e GetTemplatesParamsSort) Valid() bool {
	switch e {
	case GetTemplatesParamsSortCreatedAtAsc:
		return true
	case GetTemplatesParamsSortCreatedAtDesc:
		return true
	case GetTemplatesParamsSortUpdatedAtAsc:
		return true
	case GetTemplatesParamsSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesTemplateIDTagsGroupsParamsSort.
const (
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc  GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_desc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc    GetTemplatesTemplateIDTagsGroupsParamsSort = "name_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc   GetTemplatesTemplateIDTagsGroupsParamsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesTemplateIDTagsGroupsParamsSort enum.
func (e GetTemplatesTemplateIDTagsGroupsParamsSort) Valid() bool {
	switch e {
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc:
		return true
	default:
		return false
	}
}

// AddTeamMemberRequest defines model for AddTeamMemberRequest.
type AddTeamMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfile defines model for AdminAuthProviderProfile.
type AdminAuthProviderProfile struct {
	// Email Email address from the configured auth provider.
	Email *string `json:"email"`

	// UserId Internal E2B user identifier.
	UserId openapi_types.UUID `json:"userId"`
}

// AdminAuthProviderProfilesLookupEmailRequest defines model for AdminAuthProviderProfilesLookupEmailRequest.
type AdminAuthProviderProfilesLookupEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfilesResolveRequest defines model for AdminAuthProviderProfilesResolveRequest.
type AdminAuthProviderProfilesResolveRequest struct {
	UserIds []openapi_types.UUID `json:"userIds"`
}

// AdminAuthProviderProfilesResponse defines model for AdminAuthProviderProfilesResponse.
type AdminAuthProviderProfilesResponse struct {
	Profiles []AdminAuthProviderProfile `json:"profiles"`
}

// AdminAuthProviderUserBootstrapRequest defines model for AdminAuthProviderUserBootstrapRequest.
type AdminAuthProviderUserBootstrapRequest struct {
	OidcIssuer      string              `json:"oidc_issuer"`
	OidcUserEmail   openapi_types.Email `json:"oidc_user_email"`
	OidcUserId      string              `json:"oidc_user_id"`
	OidcUserName    *string             `json:"oidc_user_name,omitempty"`
	SignupIp        *string             `json:"signup_ip,omitempty"`
	SignupUserAgent *string             `json:"signup_user_agent,omitempty"`
}

// AdminTeamBootstrapRequest defines model for AdminTeamBootstrapRequest.
type AdminTeamBootstrapRequest struct {
	// Email Billing/contact email for the team.
	Email openapi_types.Email `json:"email"`

	// Name Team name.
	Name string `json:"name"`
}

// AdminTeamClusterRegistrationRequest defines model for AdminTeamClusterRegistrationRequest.
type AdminTeamClusterRegistrationRequest struct {
	AuthOrgId *string `json:"auth_org_id,omitempty"`

	// ClusterId Stable identifier for the new immutable cluster row.
	ClusterId   openapi_types.UUID `json:"cluster_id"`
	Endpoint    string             `json:"endpoint"`
	EndpointTls bool               `json:"endpoint_tls"`

	// ExpectedPreviousClusterId Current team cluster ID, or null when the team is expected to be unassigned.
	ExpectedPreviousClusterId *openapi_types.UUID `json:"expected_previous_cluster_id"`
	Name                      string              `json:"name"`
	SandboxProxyDomain        *string             `json:"sandbox_proxy_domain,omitempty"`
	Token                     string              `json:"token"`
}

// AdminTeamClusterRegistrationResponse defines model for AdminTeamClusterRegistrationResponse.
type AdminTeamClusterRegistrationResponse struct {
	// Changed False when an identical request was already committed.
	Changed           bool                `json:"changed"`
	ClusterId         openapi_types.UUID  `json:"cluster_id"`
	PreviousClusterId *openapi_types.UUID `json:"previous_cluster_id"`
	TeamId            openapi_types.UUID  `json:"team_id"`
}

// BuildInfo defines model for BuildInfo.
type BuildInfo struct {
	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Names Template names related to this build, if available.
	Names *[]string `json:"names,omitempty"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildStatus Build status mapped for dashboard clients.
type BuildStatus string

// BuildStatusItem defines model for BuildStatusItem.
type BuildStatusItem struct {
	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildsListResponse defines model for BuildsListResponse.
type BuildsListResponse struct {
	Data []ListedBuild `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// BuildsStatusesResponse defines model for BuildsStatusesResponse.
type BuildsStatusesResponse struct {
	// BuildStatuses List of build statuses
	BuildStatuses []BuildStatusItem `json:"buildStatuses"`
}

// CPUCount CPU cores for the sandbox
type CPUCount = int64

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// DefaultTemplate defines model for DefaultTemplate.
type DefaultTemplate struct {
	Aliases         []DefaultTemplateAlias `json:"aliases"`
	BuildCount      int32                  `json:"buildCount"`
	BuildId         openapi_types.UUID     `json:"buildId"`
	CreatedAt       time.Time              `json:"createdAt"`
	EnvdVersion     *string                `json:"envdVersion,omitempty"`
	Id              string                 `json:"id"`
	Public          bool                   `json:"public"`
	RamMb           int64                  `json:"ramMb"`
	SpawnCount      int64                  `json:"spawnCount"`
	TotalDiskSizeMb *int64                 `json:"totalDiskSizeMb"`
	Vcpu            int64                  `json:"vcpu"`
}

// DefaultTemplateAlias defines model for DefaultTemplateAlias.
type DefaultTemplateAlias struct {
	Alias     string  `json:"alias"`
	Namespace *string `json:"namespace,omitempty"`
}

// DefaultTemplatesResponse defines model for DefaultTemplatesResponse.
type DefaultTemplatesResponse struct {
	Templates []DefaultTemplate `json:"templates"`
}

// DiskSizeMB Disk size for the sandbox in MiB
type DiskSizeMB = int64

// Error defines model for Error.
type Error struct {
	// Code Error code.
	Code int32 `json:"code"`

	// Message Error message.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Message Human-readable health check result.
	Message string `json:"message"`
}

// ListedBuild defines model for ListedBuild.
type ListedBuild struct {
	// CpuCount CPU cores configured for the build.
	CpuCount int64 `json:"cpuCount"`

	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB configured for the build, if recorded.
	DiskSizeMB *int64 `json:"diskSizeMB"`

	// EnvdVersion envd version the build was created with, if recorded.
	EnvdVersion *string `json:"envdVersion"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// MemoryMB Memory in MiB configured for the build.
	MemoryMB int64 `json:"memoryMB"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`

	// Template Template alias when present, otherwise template ID.
	Template string `json:"template"`

	// TemplateId Identifier of the template.
	TemplateId string `json:"templateId"`
}

// ManagementMemberBatchEntry defines model for ManagementMemberBatchEntry.
type ManagementMemberBatchEntry struct {
	// Present Whether the user should be a member after this call. Presence is stated rather than implied by inclusion, so one request carries both additions and removals and the caller never has to order them.
	Present bool               `json:"present"`
	UserId  openapi_types.UUID `json:"user_id"`
}

// ManagementMemberBatchRequest Desired membership for the listed users, ignoring everyone unlisted. Entries are independent, so applying them in any order converges.
type ManagementMemberBatchRequest = []ManagementMemberBatchEntry

// ManagementMemberUpsertRequest defines model for ManagementMemberUpsertRequest.
type ManagementMemberUpsertRequest struct {
	AddedBy *openapi_types.UUID `json:"added_by,omitempty"`
}

// ManagementProject defines model for ManagementProject.
type ManagementProject struct {
	// Email Contact address recorded on the project.
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`

	// Slug Changing it renames the project, and nothing follows it. Template names embed the slug they were built under, so a renamed project keeps its existing template names and only new ones carry the new slug. A slug already held on this control plane is a 409, on a rename as much as on a create.
	Slug string `json:"slug"`
}

// ManagementProjectLimits A project's effective limits, already resolved by the caller. Every field is absolute: this side stores what it is given and performs no arithmetic of its own.
//
// The minimums below track the CHECK constraints on tiers, which is the contract for what a limit may be. project_limits stores the same values under looser constraints on purpose — it is a push target, and a floor that only rejects the impossible keeps a future decision about what is allowed a change to this schema rather than a migration.
type ManagementProjectLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrent_sandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrent_template_builds"`

	// DefaultFreeDiskSizeMb Free rootfs allowance. Must not exceed max_disk_size_mb; the two are stored together and rejected as a pair if they disagree.
	DefaultFreeDiskSizeMb int64 `json:"default_free_disk_size_mb"`
	DiskMb                int64 `json:"disk_mb"`
	EventsTtlDays         int32 `json:"events_ttl_days"`
	MaxDiskSizeMb         int64 `json:"max_disk_size_mb"`
	MaxRamMb              int64 `json:"max_ram_mb"`
	MaxSandboxLengthHours int32 `json:"max_sandbox_length_hours"`
	MaxVcpu               int32 `json:"max_vcpu"`
}

// ManagementProjectUpsertRequest The properties of a project this side stores. Every one is synchronized by the caller and sent on every push, so a reconcile is a complete statement of the project rather than a patch.
//
// A project's tier is not among them. It is assigned once, at creation, from this side's own default, and no push moves it — limits arrive separately and in full through upsertProjectLimits, which takes precedence over the tier anyway.
type ManagementProjectUpsertRequest struct {
	// Email Contact address recorded on the project.
	Email string `json:"email"`
	Name  string `json:"name"`

	// Slug Changing it renames the project, and nothing follows it. Template names embed the slug they were built under, so a renamed project keeps its existing template names and only new ones carry the new slug. A slug already held on this control plane is a 409, on a rename as much as on a create.
	Slug string `json:"slug"`
}

// MemoryMB Memory for the sandbox in MiB
type MemoryMB = int64

// SandboxRecord defines model for SandboxRecord.
type SandboxRecord struct {
	// Alias Alias of the template
	Alias *string `json:"alias,omitempty"`

	// CpuCount CPU cores for the sandbox
	CpuCount CPUCount `json:"cpuCount"`

	// DiskSizeMB Disk size for the sandbox in MiB
	DiskSizeMB DiskSizeMB `json:"diskSizeMB"`

	// Domain Base domain where the sandbox traffic is accessible
	Domain *string `json:"domain,omitempty"`

	// EventsRetentionExpired Whether the sandbox ended more than the team's events retention window ago, so its events data is no longer available
	EventsRetentionExpired bool `json:"eventsRetentionExpired"`

	// MemoryMB Memory for the sandbox in MiB
	MemoryMB MemoryMB `json:"memoryMB"`

	// RetentionExpired Whether the sandbox ended more than the fixed retention window ago, so its monitoring and logs data is no longer available
	RetentionExpired bool `json:"retentionExpired"`

	// SandboxID Identifier of the sandbox
	SandboxID string `json:"sandboxID"`

	// StartedAt Time when the sandbox was started
	StartedAt time.Time `json:"startedAt"`

	// StoppedAt Time when the sandbox was stopped
	StoppedAt *time.Time `json:"stoppedAt,omitempty"`

	// TemplateID Identifier of the template from which is the sandbox created
	TemplateID string `json:"templateID"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	AddedBy           *openapi_types.UUID `json:"addedBy,omitempty"`
	CreatedAt         *time.Time          `json:"createdAt"`
	Email             string              `json:"email"`
	Id                openapi_types.UUID  `json:"id"`
	IsDefault         bool                `json:"isDefault"`
	Name              *string             `json:"name,omitempty"`
	ProfilePictureUrl *string             `json:"profilePictureUrl,omitempty"`
	Providers         []string            `json:"providers"`
}

// TeamMembersResponse defines model for TeamMembersResponse.
type TeamMembersResponse struct {
	Members []TeamMember `json:"members"`
}

// TeamResolveResponse defines model for TeamResolveResponse.
type TeamResolveResponse struct {
	Id   openapi_types.UUID `json:"id"`
	Slug string             `json:"slug"`
}

// TeamTemplate defines model for TeamTemplate.
type TeamTemplate struct {
	Aliases    []string           `json:"aliases"`
	BuildCount int32              `json:"buildCount"`
	BuildID    openapi_types.UUID `json:"buildID"`
	CpuCount   int64              `json:"cpuCount"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  *struct {
		Email *string            `json:"email,omitempty"`
		Id    openapi_types.UUID `json:"id"`
	} `json:"createdBy"`
	DefaultDescription *string    `json:"defaultDescription,omitempty"`
	DiskSizeMB         *int64     `json:"diskSizeMB"`
	EnvdVersion        *string    `json:"envdVersion"`
	IsDefault          bool       `json:"isDefault"`
	LastSpawnedAt      *time.Time `json:"lastSpawnedAt"`
	MemoryMB           int64      `json:"memoryMB"`
	Names              []string   `json:"names"`
	Public             bool       `json:"public"`
	SpawnCount         int64      `json:"spawnCount"`
	TemplateID         string     `json:"templateID"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

// TeamTemplatesResponse defines model for TeamTemplatesResponse.
type TeamTemplatesResponse struct {
	Data []TeamTemplate `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateDetail Dashboard-shaped single-template read. Mirrors the infra-api `Template` schema fields the dashboard renders.
type TemplateDetail struct {
	// Aliases Aliases of the template.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Aliases []string `json:"aliases"`

	// BuildCount Number of times the template was built.
	BuildCount int32 `json:"buildCount"`

	// BuildID Identifier of the latest ready build for the template, or the zero UUID when none.
	BuildID string `json:"buildID"`

	// CpuCount vCPU count of the latest ready default build, or `null` when none.
	CpuCount *CPUCount `json:"cpuCount"`

	// CreatedAt Time when the template was created.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB of the latest ready default build, or `null` when none.
	DiskSizeMB *DiskSizeMB `json:"diskSizeMB"`

	// EnvdVersion envd version of the latest ready default build, or `null` when none.
	EnvdVersion *string `json:"envdVersion"`

	// LastSpawnedAt Time when the template was last used.
	LastSpawnedAt *time.Time `json:"lastSpawnedAt"`

	// MemoryMB Memory in MiB of the latest ready default build, or `null` when none.
	MemoryMB *MemoryMB `json:"memoryMB"`

	// Names Names of the template (namespace/alias format when namespaced).
	Names []string `json:"names"`

	// Public Whether the template is public or only accessible by the team.
	Public bool `json:"public"`

	// SpawnCount Number of times the template was used.
	SpawnCount int64 `json:"spawnCount"`

	// TemplateID Identifier of the template.
	TemplateID string `json:"templateID"`

	// UpdatedAt Time when the template was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// TemplateTagAssignment defines model for TemplateTagAssignment.
type TemplateTagAssignment struct {
	// AssignedAt Time when the tag was assigned to the build.
	AssignedAt time.Time `json:"assignedAt"`

	// AssignmentId Identifier of the tag assignment event.
	AssignmentId openapi_types.UUID `json:"assignmentId"`

	// BuildCreatedAt Time when the assigned build was created.
	BuildCreatedAt time.Time `json:"buildCreatedAt"`

	// BuildFinishedAt Time when the assigned build finished.
	BuildFinishedAt *time.Time `json:"buildFinishedAt"`

	// BuildId Identifier of the assigned build.
	BuildId openapi_types.UUID `json:"buildId"`
}

// TemplateTagAssignmentsResponse defines model for TemplateTagAssignmentsResponse.
type TemplateTagAssignmentsResponse struct {
	// Data Ready assignment events for the tag, sorted latest first.
	Data []TemplateTagAssignment `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateTagExistsResponse defines model for TemplateTagExistsResponse.
type TemplateTagExistsResponse struct {
	// Exists Whether the template tag has at least one ready assignment.
	Exists bool `json:"exists"`

	// NormalizedTag Normalized template tag name.
	NormalizedTag string `json:"normalizedTag"`
}

// TemplateTagGroup defines model for TemplateTagGroup.
type TemplateTagGroup struct {
	// Assignments Ready assignment events for this tag, sorted latest first.
	Assignments []TemplateTagAssignment `json:"assignments"`

	// HasMore Whether more ready assignment events exist beyond the requested assignment limit.
	HasMore bool `json:"hasMore"`

	// Tag Template tag name.
	Tag string `json:"tag"`
}

// TemplateTagGroupsResponse defines model for TemplateTagGroupsResponse.
type TemplateTagGroupsResponse struct {
	// NextCursor Cursor to pass as `tagsCursor` for the next page, or `null` if there is no next page.
	NextCursor *string            `json:"nextCursor"`
	Tags       []TemplateTagGroup `json:"tags"`
}

// TemplateTagsCountResponse defines model for TemplateTagsCountResponse.
type TemplateTagsCountResponse struct {
	// Total Total distinct ready tags for the template.
	Total int64 `json:"total"`
}

// UpdateTeamRequest defines model for UpdateTeamRequest.
type UpdateTeamRequest struct {
	Name              *string `json:"name,omitempty"`
	ProfilePictureUrl *string `json:"profilePictureUrl,omitempty"`
}

// UpdateTeamResponse defines model for UpdateTeamResponse.
type UpdateTeamResponse struct {
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl,omitempty"`
}

// UserTeam defines model for UserTeam.
type UserTeam struct {
	BlockedReason     *string            `json:"blockedReason"`
	CreatedAt         time.Time          `json:"createdAt"`
	Email             string             `json:"email"`
	Id                openapi_types.UUID `json:"id"`
	IsBanned          bool               `json:"isBanned"`
	IsBlocked         bool               `json:"isBlocked"`
	IsDefault         bool               `json:"isDefault"`
	Limits            UserTeamLimits     `json:"limits"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl"`
	Slug              string             `json:"slug"`
	Tier              string             `json:"tier"`
}

// UserTeamLimits defines model for UserTeamLimits.
type UserTeamLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrentSandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrentTemplateBuilds"`
	DiskMb                   int32 `json:"diskMb"`
	EventsTtlDays            int32 `json:"eventsTtlDays"`
	MaxLengthHours           int64 `json:"maxLengthHours"`
	MaxRamMb                 int32 `json:"maxRamMb"`
	MaxVcpu                  int32 `json:"maxVcpu"`
}

// UserTeamsResponse defines model for UserTeamsResponse.
type UserTeamsResponse struct {
	Teams []UserTeam `json:"teams"`
}

// BuildId defines model for build_id.
type BuildId = openapi_types.UUID

// BuildIdOrTemplate defines model for build_id_or_template.
type BuildIdOrTemplate = string

// BuildIds defines model for build_ids.
type BuildIds = []openapi_types.UUID

// BuildStatuses defines model for build_statuses.
type BuildStatuses = []BuildStatus

// BuildsCursor defines model for builds_cursor.
type BuildsCursor = string

// BuildsLimit defines model for builds_limit.
type BuildsLimit = int32

// SandboxID defines model for sandboxID.
type SandboxID = string

// Tag defines model for tag.
type Tag = string

// TagAssignmentLimit defines model for tag_assignment_limit.
type TagAssignmentLimit = int32

// TagAssignmentsCursor defines model for tag_assignments_cursor.
type TagAssignmentsCursor = string

// TagAssignmentsLimit defines model for tag_assignments_limit.
type TagAssignmentsLimit = int32

// TagGroupsCursor defines model for tag_groups_cursor.
type TagGroupsCursor = string

// TagGroupsLimit defines model for tag_groups_limit.
type TagGroupsLimit = int32

// TagGroupsSearch defines model for tag_groups_search.
type TagGroupsSearch = string

// TagGroupsSort defines model for tag_groups_sort.
type TagGroupsSort string

// TagPath defines model for tag_path.
type TagPath = string

// TeamID defines model for teamID.
type TeamID = openapi_types.UUID

// TeamSlug defines model for teamSlug.
type TeamSlug = string

// TemplateID defines model for templateID.
type TemplateID = string

// TemplatesCursor defines model for templates_cursor.
type TemplatesCursor = string

// TemplatesLimit defines model for templates_limit.
type TemplatesLimit = int32

// TemplatesPublic defines model for templates_public.
type TemplatesPublic = bool

// TemplatesSearch defines model for templates_search.
type TemplatesSearch = string

// TemplatesSort defines model for templates_sort.
type TemplatesSort string

// UserId defines model for userId.
type UserId = openapi_types.UUID

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N409 defines model for 409.
type N409 = Error

// N500 defines model for 500.
type N500 = Error

// N501 defines model for 501.
type N501 = Error

// N502 defines model for 502.
type N502 = Error

// adminApiKeyAuthContextKey is the context key for AdminApiKeyAuth security scheme
type adminApiKeyAuthContextKey string

// adminJWTAuthContextKey is the context key for AdminJWTAuth security scheme
type adminJWTAuthContextKey string

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// authProviderBearerAuthContextKey is the context key for AuthProviderBearerAuth security scheme
type authProviderBearerAuthContextKey string

// authProviderTeamAuthContextKey is the context key for AuthProviderTeamAuth security scheme
type authProviderTeamAuthContextKey string

// GetBuildsParams defines parameters for GetBuilds.
type GetBuildsParams struct {
	// BuildIdOrTemplate Optional filter by build identifier, template identifier, or template alias.
	BuildIdOrTemplate *BuildIdOrTemplate `form:"build_id_or_template,omitempty" json:"build_id_or_template,omitempty"`

	// Statuses Comma-separated list of build statuses to include.
	Statuses *BuildStatuses `form:"statuses,omitempty" json:"statuses,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *BuildsLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `created_at|build_id` format.
	Cursor *BuildsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetBuildsStatusesParams defines parameters for GetBuildsStatuses.
type GetBuildsStatusesParams struct {
	// BuildIds Comma-separated list of build IDs to get statuses for.
	BuildIds BuildIds `form:"build_ids" json:"build_ids"`
}

// GetTeamsResolveParams defines parameters for GetTeamsResolve.
type GetTeamsResolveParams struct {
	// Slug Team slug to resolve.
	Slug TeamSlug `form:"slug" json:"slug"`
}

// GetTemplatesParams defines parameters for GetTemplates.
type GetTemplatesParams struct {
	// Public Filter templates by visibility (true = public, false = internal).
	Public *TemplatesPublic `form:"public,omitempty" json:"public,omitempty"`

	// Search Case-insensitive substring match on template names, aliases, and template id.
	Search *TemplatesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort column and direction.
	Sort *GetTemplatesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *TemplatesLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `{sort}|{value}|{templateID}` format. Rejected if its sort does not match the request.
	Cursor *TemplatesCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetTemplatesParamsSort defines parameters for GetTemplates.
type GetTemplatesParamsSort string

// GetTemplatesTemplateIDTagsExistsParams defines parameters for GetTemplatesTemplateIDTagsExists.
type GetTemplatesTemplateIDTagsExistsParams struct {
	// Tag Template tag name to check.
	Tag Tag `form:"tag" json:"tag"`
}

// GetTemplatesTemplateIDTagsGroupsParams defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParams struct {
	// AssignmentLimit Maximum number of ready assignment rows to return per tag.
	AssignmentLimit *TagAssignmentLimit `form:"assignmentLimit,omitempty" json:"assignmentLimit,omitempty"`

	// TagsLimit Maximum number of distinct tags to return per page.
	TagsLimit *TagGroupsLimit `form:"tagsLimit,omitempty" json:"tagsLimit,omitempty"`

	// TagsCursor Cursor returned by the previous list response in `{sort}|{latest_assigned_at}|{tag}` format (sort-tagged, RFC3339Nano).
	TagsCursor *TagGroupsCursor `form:"tagsCursor,omitempty" json:"tagsCursor,omitempty"`

	// Search Case-insensitive substring filter on tag name. Allowed characters are `a-z`, `0-9`, `.`, `_`, `-`.
	Search *TagGroupsSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort order for the returned tag groups.
	Sort *GetTemplatesTemplateIDTagsGroupsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetTemplatesTemplateIDTagsGroupsParamsSort defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParamsSort string

// GetTemplatesTemplateIDTagsTagAssignmentsParams defines parameters for GetTemplatesTemplateIDTagsTagAssignments.
type GetTemplatesTemplateIDTagsTagAssignmentsParams struct {
	// Cursor Cursor returned by the previous list response in `assigned_at|assignment_id` format.
	Cursor *TagAssignmentsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of assignment rows to return per page.
	Limit *TagAssignmentsLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAdminTeamsBootstrapJSONRequestBody defines body for PostAdminTeamsBootstrap for application/json ContentType.
type PostAdminTeamsBootstrapJSONRequestBody = AdminTeamBootstrapRequest

// PutAdminTeamsTeamIDClusterJSONRequestBody defines body for PutAdminTeamsTeamIDCluster for application/json ContentType.
type PutAdminTeamsTeamIDClusterJSONRequestBody = AdminTeamClusterRegistrationRequest

// PostAdminUserProfilesByEmailJSONRequestBody defines body for PostAdminUserProfilesByEmail for application/json ContentType.
type PostAdminUserProfilesByEmailJSONRequestBody = AdminAuthProviderProfilesLookupEmailRequest

// PostAdminUserProfilesResolveJSONRequestBody defines body for PostAdminUserProfilesResolve for application/json ContentType.
type PostAdminUserProfilesResolveJSONRequestBody = AdminAuthProviderProfilesResolveRequest

// PostAdminUsersBootstrapJSONRequestBody defines body for PostAdminUsersBootstrap for application/json ContentType.
type PostAdminUsersBootstrapJSONRequestBody = AdminAuthProviderUserBootstrapRequest

// PostTeamsJSONRequestBody defines body for PostTeams for application/json ContentType.
type PostTeamsJSONRequestBody = CreateTeamRequest

// PatchTeamsTeamIDJSONRequestBody defines body for PatchTeamsTeamID for application/json ContentType.
type PatchTeamsTeamIDJSONRequestBody = UpdateTeamRequest

// PostTeamsTeamIDMembersJSONRequestBody defines body for PostTeamsTeamIDMembers for application/json ContentType.
type PostTeamsTeamIDMembersJSONRequestBody = AddTeamMemberRequest

// ManagementUpsertProjectJSONRequestBody defines body for ManagementUpsertProject for application/json ContentType.
type ManagementUpsertProjectJSONRequestBody = ManagementProjectUpsertRequest

// ManagementUpsertProjectLimitsJSONRequestBody defines body for ManagementUpsertProjectLimits for application/json ContentType.
type ManagementUpsertProjectLimitsJSONRequestBody = ManagementProjectLimits

// ManagementBatchSyncProjectMembersJSONRequestBody defines body for ManagementBatchSyncProjectMembers for application/json ContentType.
type ManagementBatchSyncProjectMembersJSONRequestBody = ManagementMemberBatchRequest

// ManagementUpsertProjectMemberJSONRequestBody defines body for ManagementUpsertProjectMember for application/json ContentType.
type ManagementUpsertProjectMemberJSONRequestBody = ManagementMemberUpsertRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bootstrap team
	// (POST /admin/teams/bootstrap)
	PostAdminTeamsBootstrap(c *gin.Context)
	// Register and assign an immutable cluster
	// (PUT /admin/teams/{teamID}/cluster)
	PutAdminTeamsTeamIDCluster(c *gin.Context, teamID TeamID)
	// Lookup user profiles by email
	// (POST /admin/user-profiles/by-email)
	PostAdminUserProfilesByEmail(c *gin.Context)
	// Resolve user profiles
	// (POST /admin/user-profiles/resolve)
	PostAdminUserProfilesResolve(c *gin.Context)
	// User profile
	// (GET /admin/user-profiles/{userId})
	GetAdminUserProfilesUserId(c *gin.Context, userId UserId)
	// Bootstrap auth provider user
	// (POST /admin/users/bootstrap)
	PostAdminUsersBootstrap(c *gin.Context)
	// Delete user
	// (DELETE /admin/users/{userId})
	DeleteAdminUsersUserId(c *gin.Context, userId UserId)
	// List team builds
	// (GET /builds)
	GetBuilds(c *gin.Context, params GetBuildsParams)
	// Build statuses
	// (GET /builds/statuses)
	GetBuildsStatuses(c *gin.Context, params GetBuildsStatusesParams)
	// Build details
	// (GET /builds/{build_id})
	GetBuildsBuildId(c *gin.Context, buildId BuildId)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Sandbox record
	// (GET /sandboxes/{sandboxID}/record)
	GetSandboxesSandboxIDRecord(c *gin.Context, sandboxID SandboxID)
	// List user teams
	// (GET /teams)
	GetTeams(c *gin.Context)
	// Create team
	// (POST /teams)
	PostTeams(c *gin.Context)
	// Resolve team identity
	// (GET /teams/resolve)
	GetTeamsResolve(c *gin.Context, params GetTeamsResolveParams)
	// Update team
	// (PATCH /teams/{teamID})
	PatchTeamsTeamID(c *gin.Context, teamID TeamID)
	// List team members
	// (GET /teams/{teamID}/members)
	GetTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Add team member
	// (POST /teams/{teamID}/members)
	PostTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Remove team member
	// (DELETE /teams/{teamID}/members/{userId})
	DeleteTeamsTeamIDMembersUserId(c *gin.Context, teamID TeamID, userId UserId)
	// List team templates
	// (GET /templates)
	GetTemplates(c *gin.Context, params GetTemplatesParams)
	// List default templates
	// (GET /templates/defaults)
	GetTemplatesDefaults(c *gin.Context)
	// Template
	// (GET /templates/{templateID})
	GetTemplatesTemplateID(c *gin.Context, templateID TemplateID)
	// Count template tags
	// (GET /templates/{templateID}/tags/count)
	GetTemplatesTemplateIDTagsCount(c *gin.Context, templateID TemplateID)
	// Check ready template tag existence
	// (GET /templates/{templateID}/tags/exists)
	GetTemplatesTemplateIDTagsExists(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsExistsParams)
	// List template tag groups
	// (GET /templates/{templateID}/tags/groups)
	GetTemplatesTemplateIDTagsGroups(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsGroupsParams)
	// List ready assignments for a single template tag
	// (GET /templates/{templateID}/tags/{tag}/assignments)
	GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context, templateID TemplateID, tag TagPath, params GetTemplatesTemplateIDTagsTagAssignmentsParams)
	// Delete a project and its control-plane state (v1).
	// (DELETE /v1/management/projects/{teamID})
	ManagementDeleteProject(c *gin.Context, teamID TeamID)
	// Create or reconcile a project (v1).
	// (PUT /v1/management/projects/{teamID})
	ManagementUpsertProject(c *gin.Context, teamID TeamID)
	// Reconcile effective limits for a project (v1).
	// (PUT /v1/management/projects/{teamID}/limits)
	ManagementUpsertProjectLimits(c *gin.Context, teamID TeamID)
	// Reconcile many project memberships in one call (v1).
	// (POST /v1/management/projects/{teamID}/members/batch)
	ManagementBatchSyncProjectMembers(c *gin.Context, teamID TeamID)
	// Remove a project member (v1).
	// (DELETE /v1/management/projects/{teamID}/members/{userId})
	ManagementDeleteProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Reconcile an opaque user UUID as a project member (v1).
	// (PUT /v1/management/projects/{teamID}/members/{userId})
	ManagementUpsertProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Purge shard-local membership and access-token state for an opaque user UUID (v1).
	// (DELETE /v1/management/users/{userId})
	ManagementPurgeUser(c *gin.Context, userId UserId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAdminTeamsBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminTeamsBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminTeamsBootstrap(c)
}

// PutAdminTeamsTeamIDCluster operation middleware
func (siw *ServerInterfaceWrapper) PutAdminTeamsTeamIDCluster(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutAdminTeamsTeamIDCluster(c, teamID)
}

// PostAdminUserProfilesByEmail operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesByEmail(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesByEmail(c)
}

// PostAdminUserProfilesResolve operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesResolve(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesResolve(c)
}

// GetAdminUserProfilesUserId operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUserProfilesUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUserProfilesUserId(c, userId)
}

// PostAdminUsersBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUsersBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUsersBootstrap(c)
}

// DeleteAdminUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminUsersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminUsersUserId(c, userId)
}

// GetBuilds operation middleware
func (siw *ServerInterfaceWrapper) GetBuilds(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsParams

	// ------------- Optional query parameter "build_id_or_template" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "build_id_or_template", c.Request.URL.Query(), &params.BuildIdOrTemplate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id_or_template: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "statuses", c.Request.URL.Query(), &params.Statuses, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statuses: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuilds(c, params)
}

// GetBuildsStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsStatuses(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsStatusesParams

	// ------------- Required query parameter "build_ids" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "build_ids", c.Request.URL.Query(), &params.BuildIds, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_ids: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsStatuses(c, params)
}

// GetBuildsBuildId operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsBuildId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "build_id" -------------
	var buildId BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "build_id", c.Param("build_id"), &buildId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsBuildId(c, buildId)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetSandboxesSandboxIDRecord operation middleware
func (siw *ServerInterfaceWrapper) GetSandboxesSandboxIDRecord(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "sandboxID" -------------
	var sandboxID SandboxID

	err = runtime.BindStyledParameterWithOptions("simple", "sandboxID", c.Param("sandboxID"), &sandboxID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sandboxID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSandboxesSandboxIDRecord(c, sandboxID)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeams(c)
}

// PostTeams operation middleware
func (siw *ServerInterfaceWrapper) PostTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeams(c)
}

// GetTeamsResolve operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsResolve(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamsResolveParams

	// ------------- Required query parameter "slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "slug", c.Request.URL.Query(), &params.Slug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsResolve(c, params)
}

// PatchTeamsTeamID operation middleware
func (siw *ServerInterfaceWrapper) PatchTeamsTeamID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTeamsTeamID(c, teamID)
}

// GetTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsTeamIDMembers(c, teamID)
}

// PostTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamsTeamIDMembers(c, teamID)
}

// DeleteTeamsTeamIDMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamsTeamIDMembersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTeamsTeamIDMembersUserId(c, teamID, userId)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesParams

	// ------------- Optional query parameter "public" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "public", c.Request.URL.Query(), &params.Public, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter public: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplates(c, params)
}

// GetTemplatesDefaults operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesDefaults(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesDefaults(c)
}

// GetTemplatesTemplateID operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateID(c, templateID)
}

// GetTemplatesTemplateIDTagsCount operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsCount(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsCount(c, templateID)
}

// GetTemplatesTemplateIDTagsExists operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsExists(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsExistsParams

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", c.Request.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsExists(c, templateID, params)
}

// GetTemplatesTemplateIDTagsGroups operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsGroups(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsGroupsParams

	// ------------- Optional query parameter "assignmentLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignmentLimit", c.Request.URL.Query(), &params.AssignmentLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter assignmentLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsLimit", c.Request.URL.Query(), &params.TagsLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsCursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsCursor", c.Request.URL.Query(), &params.TagsCursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsCursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsGroups(c, templateID, params)
}

// GetTemplatesTemplateIDTagsTagAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag TagPath

	err = runtime.BindStyledParameterWithOptions("simple", "tag", c.Param("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsTagAssignmentsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsTagAssignments(c, templateID, tag, params)
}

// ManagementDeleteProject operation middleware
func (siw *ServerInterfaceWrapper) ManagementDeleteProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementDeleteProject(c, teamID)
}

// ManagementUpsertProject operation middleware
func (siw *ServerInterfaceWrapper) ManagementUpsertProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementUpsertProject(c, teamID)
}

// ManagementUpsertProjectLimits operation middleware
func (siw *ServerInterfaceWrapper) ManagementUpsertProjectLimits(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementUpsertProjectLimits(c, teamID)
}

// ManagementBatchSyncProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ManagementBatchSyncProjectMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementBatchSyncProjectMembers(c, teamID)
}

// ManagementDeleteProjectMember operation middleware
func (siw *ServerInterfaceWrapper) ManagementDeleteProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementDeleteProjectMember(c, teamID, userId)
}

// ManagementUpsertProjectMember operation middleware
func (siw *ServerInterfaceWrapper) ManagementUpsertProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementUpsertProjectMember(c, teamID, userId)
}

// ManagementPurgeUser operation middleware
func (siw *ServerInterfaceWrapper) ManagementPurgeUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ManagementPurgeUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/admin/teams/bootstrap", wrapper.PostAdminTeamsBootstrap)
	router.PUT(options.BaseURL+"/admin/teams/:teamID/cluster", wrapper.PutAdminTeamsTeamIDCluster)
	router.POST(options.BaseURL+"/admin/user-profiles/by-email", wrapper.PostAdminUserProfilesByEmail)
	router.POST(options.BaseURL+"/admin/user-profiles/resolve", wrapper.PostAdminUserProfilesResolve)
	router.GET(options.BaseURL+"/admin/user-profiles/:userId", wrapper.GetAdminUserProfilesUserId)
	router.POST(options.BaseURL+"/admin/users/bootstrap", wrapper.PostAdminUsersBootstrap)
	router.DELETE(options.BaseURL+"/admin/users/:userId", wrapper.DeleteAdminUsersUserId)
	router.GET(options.BaseURL+"/builds", wrapper.GetBuilds)
	router.GET(options.BaseURL+"/builds/statuses", wrapper.GetBuildsStatuses)
	router.GET(options.BaseURL+"/builds/:build_id", wrapper.GetBuildsBuildId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/sandboxes/:sandboxID/record", wrapper.GetSandboxesSandboxIDRecord)
	router.GET(options.BaseURL+"/teams", wrapper.GetTeams)
	router.POST(options.BaseURL+"/teams", wrapper.PostTeams)
	router.GET(options.BaseURL+"/teams/resolve", wrapper.GetTeamsResolve)
	router.PATCH(options.BaseURL+"/teams/:teamID", wrapper.PatchTeamsTeamID)
	router.GET(options.BaseURL+"/teams/:teamID/members", wrapper.GetTeamsTeamIDMembers)
	router.POST(options.BaseURL+"/teams/:teamID/members", wrapper.PostTeamsTeamIDMembers)
	router.DELETE(options.BaseURL+"/teams/:teamID/members/:userId", wrapper.DeleteTeamsTeamIDMembersUserId)
	router.GET(options.BaseURL+"/templates", wrapper.GetTemplates)
	router.GET(options.BaseURL+"/templates/defaults", wrapper.GetTemplatesDefaults)
	router.GET(options.BaseURL+"/templates/:templateID", wrapper.GetTemplatesTemplateID)
	router.GET(options.BaseURL+"/templates/:templateID/tags/count", wrapper.GetTemplatesTemplateIDTagsCount)
	router.GET(options.BaseURL+"/templates/:templateID/tags/exists", wrapper.GetTemplatesTemplateIDTagsExists)
	router.GET(options.BaseURL+"/templates/:templateID/tags/groups", wrapper.GetTemplatesTemplateIDTagsGroups)
	router.GET(options.BaseURL+"/templates/:templateID/tags/:tag/assignments", wrapper.GetTemplatesTemplateIDTagsTagAssignments)
	router.DELETE(options.BaseURL+"/v1/management/projects/:teamID", wrapper.ManagementDeleteProject)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID", wrapper.ManagementUpsertProject)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID/limits", wrapper.ManagementUpsertProjectLimits)
	router.POST(options.BaseURL+"/v1/management/projects/:teamID/members/batch", wrapper.ManagementBatchSyncProjectMembers)
	router.DELETE(options.BaseURL+"/v1/management/projects/:teamID/members/:userId", wrapper.ManagementDeleteProjectMember)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID/members/:userId", wrapper.ManagementUpsertProjectMember)
	router.DELETE(options.BaseURL+"/v1/management/users/:userId", wrapper.ManagementPurgeUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rchy39eeroGb/VXG2hkPq5lorlQ8iJcdKLEclUfFWKdoRpvvMNKJuoA2gSY4ZVu1D7BPuk/wLB0A3",
	"+t4z5NCSoy+6TON68MPBueHgehaJLBccuFazp9eznEqagQaJ/1sVLI2XLDb/jkFFkuWaCT57OnsZA9ds",
	"zUASsSY6AYJlF7P5jJnvOdXJbD7jNIPZ06qd+UzCLwWTEM+ealnAfKaiBDJqOlgLmVE9ezorCiypt7mp",
	"q7RkfDO7uZmXzSyFXGrI8pRqaA/t7/gPmpI1SzVIstrasRFWjnlOfPXaj0JWv9OUUVVO55cC5LY9n9pA",
	"wrn0j121B3wmsoweKTC01xCTlCltqGpH/fK5IlqQDWiiNNWFAkXWQpqhwVWeihhmT9c0VTA8VDVIe6Yh",
	"UxMWYT7L6NVLW/jByUn5nUpJTacFZ78U4AqYTm7mM6W3qSljmp6VlPBz2ZUcJQ20IIxHaRHDVFKUXXbO",
	"/L8krGdPZ//juNoQx7aYOj41Xb/F6mYGtUn3zVAto0IqITsmiL8TCbqQHGIDULOBcgkXTBTKTliCygVX",
	"QBgnHyMJhhRLqv/t1/MjsUvVB1HX+QRQqmXKMqbb43xFr1hWZIQX2crucySWobwdO8lBkpxuoG8QtuFw",
	"DDGsaZHq2dMnJ/MKbIzrRw9nCC7To8NWxrj7X0lyxjVsQOLgFeXxSly9fD6FO7nCPfypampok7Tpp+mm",
	"3fm5ZyGabojpwBAsSiD61Ecm08xQxxnjPwLf6CQkRX0YS6oU2/AMuJ6+nBJovCVVTSLFZXN5Nd30Dbuq",
	"+GP/On87tMwPn4yucn1ud7mpbKt2VwXUu6Ot1Rz35EUZXo7fbLeZ+WykKPK7XIJrJaS++fe12S5KL4MV",
	"ufn3taabG78U5BtT8kjTzQbiOXnz/dmjR4+++4ly8ceBTaXOpq6Um9nkRYqZ0oxH2myPXZbIFB/YLGY/",
	"3NkyKaAySjqWiSo4YlwBV0yzCyCqWFlyeIlJ8JJ3LcizNBWXEJMooZJGRjIkVAL5SI9+/TgnH0+OvjN/",
	"LcwfS/PH0ce+ybsB1TgbvfKc7dvHc8OVNUhT9f+8p0e/nhx9t1geffif/zWbD6+bAUd7om+F1ETIGKRB",
	"EWKxxKaZn63cO1rTZucqzRxcTW9G9OBmOd43fi0hHbkmw39imQ99k8KzafxY6TnLbn2YAM2mnammZN8g",
	"bCO3E/dNI2/TovOIpRlRabGxW0+J9KJ3y5liux7rjtRTyWBL95KibGy/URyC4V7QtADDY8vBlax2Qd7A",
	"vyAykjczEp8ipg6JBSjChSYZ1VHiNtMvBahbHpPlJL9MIbQaf16sUha1J/C95allQbNKF0yxFUuZ3pJv",
	"DBDIn4mtPieov5A/E9OJ5DTtPd9cfx3kXQmRAuWN8e1xHNilNqeB5z2mbzW3yjH+g8ehKr0D5x+CwgA7",
	"j0RaZBz7jZmEyHzbg4NXClWTiwdfLMNuFy3yuF4k+KGfsxcK5MtJlhRTsoeZuEZuw1dvTGXLElDvfXxy",
	"Yv6KBNfAkew0z1MWUTO+438pM8jroP0hPfmFlELaPuqTPKWxZxdGQX588uDwfT4rdGJIa1slYMuZzh8d",
	"vvPvhVyxOAZue3x8+B5/EpqsRcFj2+N3h+/xTPB1yiJc0Sf3gaK3IC9AViv55D5g9PccpEUQswcgy/IU",
	"jH4GsR3Ew8MP4l2utDRCj5v7jd/xuIWfxbGRiF6BOSLfuG329HqWS5GD1MxudMgoS2scwv7Sxawq9vLe",
	"lap4mlgZ8cBM/VmcMW622WspLlgM8rUUa5bCQN/1ab0wPxMaxxKUImspMmSAkeBrtikkxIQWOiG5a94w",
	"RV6kKV2ZPizjaxkoe/msO1DJi4enyGID069peFweDYlSMuLdqaN+FOJTkePcP4PFUm+s/Nw7FDtVdSsz",
	"cca4/+8Em3EnrdXOs8Izrj2f3JWYbP3thXnLFNwYeNnTpJG/UyBPhdBKS5r3roZgcbRkShUgR7W5uS1t",
	"6LecDKiwkvX8TO7DCinX43tUsQ0v8iXLOyTB8is2STeOqQ7DPqRKYwJtIvSuhmGi4yvQw8tOWZoyvjk2",
	"BwGNNMFipeHB68rj1PdE7NB4vdY/psKHlMHmRtmUaf4sLZQ258eGGQKYjntpYNjyUsiNQ8jogke27U5X",
	"4lttqgbcuCQah0vCsqywBVwbRIrLCfzaSPRxLphFzwiEfdGlTlWXIoX+JdSJl165Xg5N6ayQErjGVS/H",
	"/fI5ehgNrchlArzEhREsfPtGr10BKbi3hXZNdZTcHkMj03Zuj2UuxdV2GYuMMj5pObX4BHyKMSlEYkCw",
	"EXrOS9T6JWwskR/B7njuOxSihPINdCzl96iP43pR7kAa0dRrM+SSKkJT60mJRJYxre2itTFUR8wofnuQ",
	"tjMYDMSm9dlYMF9xXl+67hXzBOxaEnSfvuRr0UF3q10/69D3sRbBAkb61iwDpWmWE8a9AyBw1JRTM6r4",
	"kSncRdM140wlg/0JI96P9TgnbE18Y73dT9qnasDUi9+JhJQ61qATpqwjHEdALyjDHtBc4GWZdjfd4wj8",
	"1+jZ3s0Jbiu9AqXoBrr2DUsLCSSzBewOsnUMv/u4piyF+OOcCJ2AvGQKyEczzo8ThPwmYykxVFvgcl7N",
	"sfZC9G1Jhy5kuMFnNM8hxjMqpipZCSpjEqXM0GoRGJJwlcxw5zM7VzOOIopAqQ4DUW0ERhZub5XPDLs7",
	"RgWNsrsvHIQ4qRJwHTAcRZ/6kSndf0LFVE8PWDFNQYzNdgWscLjSZ8NOBS1ITpWyTMeIYlfa+xPw4ENZ",
	"xhLL4MnQD6yFxJb1FvndqIiTrI2vn1xvXThPP8lWFVi62OyPnYFFISediETcr2PKYH0wXdM6e/3uTBS8",
	"Y3ufvX5HIiFt5FcYzzKr+y++fTwb9ljMZ2fILI181Cvcl9Jj5Zx9+OTJHmpH1ySfWxv8eRC+11AtrG9h",
	"MtQbDT4z1bswj/Qv6dvy+rQphRVeTpPVamLMNFEE+EX8D5CKiWkyt+W3bSmxdDu1BU5Js1er5mwRI+3Z",
	"qpxe8k7y9FTQQtP0OVOf3rJfoaebnkkFrVxEeTGpwy5266FSrZWfs2u4Pcp5TVoofWgBOGqkmIBgC7hu",
	"GHdLY0aoy2k0xVTSmLVtdMKgBphi6Wbbd4eNcrqqh86R+sU4bfM5840o9is0+ZyRYl6x00F2d9KFL2tR",
	"b6sdGCvaMkebwsR8W8zmU1hE1id42Jbc58WopoXDqZrrItsPQFOd9C9r71B+KDLKj4yCilaUBNux8YhE",
	"gipSPT6+oYGFokabznkxeqQF1n6/6m2psZ8P3bMGGU+Cr4Vr79RQBJcQCRlD9zzHOWfj/KiPxHwkF/Zr",
	"1S0aKxy9yCXTSWsco6fQ71wJySATctu1tq/wy9jCTsTsl6brVMEZA8YKPJxst7kEBVyHfZVRIi+fL2YD",
	"HUwLkQhjriboZcEdjaCfXgPBvN+kUDK0ACs1plDfmF0M8xXldIMOZOuwPaU6Sl5wLbddviokZJskPydg",
	"SFvGixCViCKNyQoIJRm2S+gaA48SpkhE03RBXmNrEeppZsYQE0ldM5SjY5vZMDK8WWFmMCdKEMHLYC8S",
	"USkZKLISOiE0jpkZkMKAHAmZuKCp/Q/6cWmagiQcLkCShKIyaeMxdQJZt5E08Dvt7pEtDZRItMnEDzSh",
	"BkMHZZp3BFUJy8vtnuKxh7RXc8I2XGDIlJnq1tCr4LbEgpilNRSjRkHmMeTAY9wcShCa5+nW1DMEMcyF",
	"8q0jUST4BcgNqMVUjXQAWA2P7MPHbf2oWftdrkDqfg9QHEO8XG0nhnL2r8NrKfBHlJnTv69nT99Pnaar",
	"Wh/pzbw51H3QxLos2R+6Bo7h3B3WhWcktwX+oAis1xBhcB0GI2IEnXUZuODVMnbTbpkFeWFwRNYM0tjs",
	"VrpSIi00PLXbWbEYiNIoPl0mVBOmTakNuwAbG5eDNPNFcwyVTCcZaBbZ6ElFxCVf/JP/k58nQJz4rMgK",
	"UnFJtKTRJxzJ2Q8vzv5mUKi0pIybauZER7hfJixKTI8uWsPU0rg1cDTUTpNkdEtWsPCEsCGeyg/civcZ",
	"EAxGVaTgBvapEMqiP+w3L2QuFJD//3//n5srJXmhEqKp3IC2gYiUrFOB25NqInhqqGv6tV2xLBdKMSMD",
	"fwLITQvrQpsTM4aIoaBEV6LQjqCKUBf4Ton1bZT2dwvEGuukJGMb62NaIAeqKxs8sg7BpVNnQHXaIIYt",
	"N0Ez/hBb2gtcezTmQiGXawmwNMfX0sity2zVIVhIACKF0GtHE8ojWJBXhdIYDwVXERgeSa9qDf3JHtSX",
	"AhkfrnlMtNjYc8ueFy7OmOJyUiadJXFLYqboRgIsdtf4cAxZtz1imCZwgTd1tE6XMd3uQ9UmDfYYhGlC",
	"0mz/yt6pm6KpbpmIQu47lS7jzGjVlmrbAf6BkQY914hRLezgTmiv4hDWO1bsw5TDqnU2NkRiDML3LAAv",
	"dXke2OLfntUbmcF82fIokYKzX5tnAm4ZI9cYfohiBnJAK0agEscjloLljU4JAyvm4WUyJzn7cdS5V25E",
	"BTwTwmPLcHsf9Ugz4cSUBXlp+aOLUCCCRzAnVJea9tyH8rmp/gGPHOLWwTJrLiwDz8QFKMPTDWt3B4QR",
	"MS+A+CvA6RZrME7WRZoSnUhRbBJS4CLUTmF/Mmn6CZTRQiKIUeAVF05WxilRvr2k2zaj7onsOXMRPT5O",
	"0SvMxOnWjmALC6fpJvP5fpb2ub3S0h6mOaWMLMk0kWBdx8HwPNl1gje9hOHkhvAL0nA3G+nPyu/2ho3h",
	"x5cgrYar7TFdos5UiUtQ2YPVLCFc4Q25TePqAI4Bj2YOlwbzChWKbRnuY7pckGe2ay8kJUYKQmIzZcUN",
	"kZI8pdyh/fHJd3Pz3Q/IHChZESXmb/zZqnONBfr20V6RVO4+UX9A1asxG8Iets0HD/9XF5N+a1t4g4Ac",
	"sEE3JFNU1BuadKdXI7DeDUnkpeOqZR8bNCtXJU29MvqoeXNAAbEfySU6GUPSaUnXaxYhDNC1buS7KfYM",
	"e0q8AQ3cdPTiKrfLPKRn+06N/haTTOBYaBXHZQR9bJZI3y65ZDwWl4RuBG4Z3Bq2TEw1dQ7TVPCNYUs+",
	"mqNTMQ5NU4PqkS+H8L2r+a3ZFcTD88oEZ9pqwWaXp2Kz+yT3udPfE0wge4zC5yyDKv7Oz/mSoknEVJps",
	"ClZa5PnunWClvS2e+91NtAdyTW3zg3KmrgnRYME9xjBhQkXrSeaxFiZ7N2MXc63uOfSYJE63ewXJjTtw",
	"x1mKlx56rNSjxmemnvsLal3e3MnR1S7s/DWLjHr7TtbDvgvJpszG37mouwnbcBxyBLLqgkQ4u4YPtuxo",
	"eL3VkO8LC0x2aAYgGpuCb7pvbOXlib6xTVx7L9JNCTIyRfvGs1tcxchy7h008Xxa0EQgXuzq6JvGoV0V",
	"yxOakO+R/Sf6nO7AnFhqps9DLj5hBHUZ6/a+w/EpD3OmlCr9NqeX/HYMNJRwJuChDJ6dDuehYJndA2Bq",
	"J3H7Hpq9FDwdrkPnrd9Wk07YMqqlio+xtKoz3mqA4UZprmaNMI1AmRBGIUjGmJO6oyjHGsP7/YU5+qk9",
	"B91pl3juw4+PVEJziIlifJPCUSn0Ge15QV4xKYV0RnC+lvSI5ox89K1/9PZsdDbYYlVgszTKgFRtW0lw",
	"nMSQS4hQiHSz79A3QXXmy9jzJGpcfS5zQ2DEQV3yNUI3Wi4mxvQEJ9iYdG1zvLg0WjbCorrvZbu3SQUT",
	"IL+CFOTdu5fPrVrABYfF2KE4zR9Wad8fmpS/sFE2RWX+qw3ZHT8+JqVCem2IdWgPR9zU9Z7aGrha+0ba",
	"TKNFaFNoUaMVnnOHNJkejXNXnXZQrHUOT14cU5MU6jahOOHpPdGRW1oqWktVj7a5w3XquXHzExonm0rz",
	"N2Wo5rENbnHJyGwX/lv8x904WV+imNAUU+VUUS4zjJkhGk4rO5f3D/i7pWMyzY5MswWHqaLQLYJ3GmLT",
	"jvi1VadymN9S3tpPxhoSEs7p5lmZObBD+3POmgl0pRt7qdG7d5xo1I5vG+TeVRrDiRFddBOmPkST0KSQ",
	"PUutqUdSOatWQOT0qWHV7wcCIQe7vH3QY3AxYYyq9b53T3NRW8UwzD7AU2sJ2hSaDNwJmkF9ym+aKUyd",
	"db2Uw+hmjgnMIPbnx5pJl7Rsmo7Rtb9+v8rGOd28uGJqaCXQt6cmHmBmXyeGnWiSguHSNpiwvmrdpxc3",
	"UE3ZrxCfd+XZ/an8XO/NZ0kYSZRiJ9HsZYQ0f5GiyPu4a+aTqO8CUabuEaMJVa+EhP6lQ6eP7Bkwkoys",
	"YCtcfKeDLUbwlIXRh9+9oNPSJY+vnU1xGRK9mtqUBRzA9g67mCrysUoy+zHIWuG26h1tZ6TbLsbtBlpH",
	"r+uY1nfhDwplk4EbRkLTDnPFufm5ypxrUYb5c5tK8ySpszkL7LRr5O9Q7mrceMwYfx0M+sH8Lu5A9rhe",
	"xtn14Jhv6VnwM7mrsbb8Eb1XPd8pkGYKHRdzUxF9gvgNUDXRAr3PBcvb++NOKecQd9uLmTq1s+j7PGwy",
	"L6OGh/ayp6CLMb7r1ex1O81nmlkP69T1L+NisGLl9WsPK6RcQON5AxR1h6EjV4iDIcRVMdl9kbhvBwNx",
	"h4JvPSM87Q+97Q5Kbd+R7Slsj9tznT7vi0LtDNe0fOmHrnjPHrU9o1dvuq4I9/fxj76I0BHu3BjevHMl",
	"BqhcdR6MuiRrk2RD0Bi8GUuz6edsyd3Gr8OaZttjMtsPokIyvX1r2gSXyzFj/FnO/gbbZ4XNA455YBOg",
	"Me4slwn2fx9hyaNzTIRUDQFrlnmQ/vrzuW9lBVSC/N4v3F9/Pve5cZE14deqnURrlBymjeT1yyPTa9co",
	"ggR3p9hHz3isWWup3XTGBxY0bJZhZIimyBEadBpDNMvAXGoizTS+4/Li4SkpnSvk2euXs/nswht3ZyeL",
	"B4sTTHyXA6c5mz2dPVqcLE5mmL8+wVU8pob6x7j0xyufUg4hJ7oihq3ybMMjMSBC2VtVNj+YkY8oJ9jm",
	"Ea3S2hq93rdNLoX8tE5tbjThc5a+jGdPZ6+F0mVWLFUmuHNZhEHpUxFv7yyHaX8mvZv6znAW2Voy4od3",
	"mEa2KzyjK6mszcmzLtJ0W5EzR62SZgubTfekr7Ny9MemUJXaeKzsgyBp7nDZJ7Zdl2Z2rOzDGl9BE3yL",
	"o7z/cPNhPlNFllG5nT2dlQuFM555feP9DAE3+2BarAH62qb3vzl2GcAQ10UHrJ9pkbGIGsoyrkBqA2kO",
	"l2EuP3t1B3U5jAN3xhEkPjlPoEqNV+a1rzLq4W+onFZHB4khT8U2s0q2FBlGf19KhvHIQKPEXktdkDeQ",
	"A9U2YDFI7VamcSsvPTJlPme5MKj8kyldxjeHMzG6Hd51zETM1sza+Bp7sQi24jmS0eWpQ/ZRPb7W4zup",
	"ihy7NxbMWh50Hw/khbznHT0ptV9Xomq/RlgeMK9wCTqw3qPO5H5BYj+8ThEflB24NOFjZR8HCb7Hyn63",
	"G5vZmXW8cRQN6ImUbCbtHGQqhQJ55HPlHq+2R6Xm5g/LnvPMiGA+3+/p9oVTOQ62GSbmcv4tNsVgBuSx",
	"Qw+zxtvHHgxH8yvxmRx9O2PSLom9Fe/nQlZbUmbcnQhEdzV3Rxw6ieO+cdhI4v3FYbC8B/2lo88tRB1+",
	"O6Du2mY7vzHj20AH6v4CbdC989nod5MgXBJ7K0F85uzJEehLhcW7AA6jaOhRGQe4z/1odaPZ6r80Dc++",
	"tPNlIqrS2mpvZOCcAoQ561MLYSGficEIt13pT8zvRmdDbrba2hQvLl+Jk5f1turb3oydE5eLBT8zsDlz",
	"Gd/YK6g2XGaBw/DJ3OvQtv1W4L5z9va4Iwt9CBJLkHvAxxco8tvFacIsZGRVUoq+A6y06u62oJ3Pbt/M",
	"J9YrE7xOreHfpJte3j15d9ADtSNX8Lhw5R4IzOmGcWs3xFYOjO1HU8o+uiVe61CdX/eanN9/6LMatzQI",
	"ptzbDWVWCY9z90MI9OPwKfNhxL+tcgzvh3x1H9hqJVaejK9GJuWv4Oo6t5vZpoegde0X/mYcXKdlcN5+",
	"2LoHaOEbEDuiKcbbL55VHQYhuxzDnyOaHI36wGRzvg4hyGaXnR1w/Rv5aztA8EOYmVaViLB0LCcclsJP",
	"x2VaoePr8lr6zbEsc2L0zbl0PL/1tVwejV03UHUZ/qA7qJ7sY/Iu8vf8f0f76Na7xpHS6SvBtqlSVNmd",
	"U4YEOBA1IzsNjTErGooL9hJF3UFrNSdIBceH4ueYd7dMdMTj8iLLOqWbtir0F9DoKjrk1myHRkwGF84O",
	"p764R9W4d/07xLhqhB1K8XzAtlKR/e6tKe1HGL4Ay4lPHP0ZucX3RYalf9PdHZpKrKM7cAH0MAD8XgZq",
	"+Cfpg4xA3kgyJxc0ZbF1N5dZezF9lc0x0b/3K5fC7g5ifD//oMfSPlAqrf0Bln6fJ1K3c8C++ueQMYhA",
	"H2qBdmCq7QPuDWZlfg7iCT63QIJ2/PU9M7uOYOoxgLq7eofndfekx95aYrI0HOeYZWhQkJOnTwAPMOtS",
	"/NwOugdkcM0URJMFJNzpjhaL3ys4KntZVq7jzqLWHQLhEO6vjhfWJ7GxByOuBkxaFhLvs2E3X4oy9yyu",
	"0W8n9tTjButyR7VBuqdbykN1fkAHFvrpPlNc/ZZYeYN0mQSX4JWsYeU/8Kqk7kXBQP4vGyLfhNp+9TPj",
	"KeMwJwVPQanao9CYuzaG2JkSXCzdH50NYc1SDRLdqgqojBLrXo1EWmQc75MaVeOCUfIJtgo0sd4pP1yX",
	"qr7jVPYz3x3YrubSZUSYAPGqjp3DjnWE1LvVmOzRq6rch1OvOzvWHn69cthfXXsjoooOcF5xgPLlujoX",
	"OHb7dpwd+LdhDBtob3bcuDoBJv1Nb+vkYHwtbAytTSEyvDOf+8EcEJG9DwpOBmVr9vdpItwBOh0AaQ19",
	"EkauqxQyNxOODZutrcpdIC55kPPf3WWw1yBamd4k0HiOrwlduTr157X6sXMeprnZj78fXuGq5b2brmvV",
	"rpB/dRd2oPs8yPa+E56PTfHjyKeSGmWBeB2f8DLH1NRr/1OAW6Yg+OwR3E6WMB3MdGMz931FcrcJH7Ma",
	"holf1J6grtLZdKL6LIHoE75raB8u2iO1zVRQv/A5afZH9QTBlm7uDfyNTEKjHiZD6mY6H1we4BH8pxlG",
	"DrFp3Ku/yII7ibznHtpgWp3Rk6Gj5yBzkG3EysgrUeArFDnII9xnTGkht/NA1bFv+piDBGvUlNxddp1N",
	"CXT4XbesprqDGko3S0uXvep43XWnSjto4kElVMXvia80sjjtYI0PkGcH/pWr3JVO3SLtnrzkWtPNzXEj",
	"pdoUttKRQdIKmZWuRTdz+7wqxITDZZlqbd7BQyYbyurspJ7P8B7YSk51sjsL2pU3hDUdJ7qnzd6VHXIn",
	"MToAhU259nXH38WOb0q6zb0WMIQBTnDx4Dgrn1c8dg/J1eMe+q8nRSmVELvXX7m6xH2NO/nJyQO884vv",
	"JNaejFsQ9Odg1ofy4boMKPKRKKUsC5+tU3OiOM1VIrSakwuRFpn5TRacm2JlvKB/85pJ/9QplZqtaYSP",
	"/dr3Dh1hFMgLFgGJKDc0jBKMH7Reg4xoEdPtgpzhm4/KP+vNBaa1AF69g1fyI1JwzVL76q19qbbDfFg9",
	"YWm9Wf7V5SmeJVfWviXpXiOGUjH9HFKjPJhS9kHPZacyR1LPTacKJfgKpS6fIDyyTxBasnxz8QDzgHuc",
	"18ocVRC3rvB9fdsuy0rf2r4Ln8Q8UOzi2PPb9xvb035HvONoeOGTtZSPn/rXUm1CD+elv78B+R1Vpp4+",
	"6Il0iGuDh9t1LjZTyOBN22oL7rDNJpwux1UaxnvZkj/6NIb3sjF91sgpO7KD7b9oPFpv3/EO3if+bG7G",
	"fg6wfVOCtfnYvxOLDoRgH8iy8sGh+wNZ9L1lvSrST8SoGWQFCeOx1e/s7QUmIdL4qi3lR6KwbzD7Z1pz",
	"kEd2gESKAh2gKM5EorSW2kRLRgyqhJ4oKfgnklK5AUkU6EF55tRM/O2WRw71VQTZYTeZ7Qd73+ns69pp",
	"KKWmDFNpuwVNWG5T8rinOdxkvu65zj2XUb4NhHlPQUUYR5xFRsQ+0M6bEkLWI36/8iFI4xh5VcHifiTw",
	"Lw8MGNpFGzC4D8F8p0i+XeSFAB+HZ2UtOf5md1zmEr4Cs5dLUU5ETn8p3OUffA2OqltBts2ohtK79IHu",
	"dSE38E5NZEWm4JGNVlEJlfF/nGEAyWXnfpSKiKbhoY22KDRFHmEyY0cdl8O3tf4HZE8l07kp35B47182",
	"8BfEDe9qPAUi5Cd816xh5iixoxo3XNHe5o1af/35HKU110vvbEy/rkx15zb40cbi1n7wdsObDzf/HQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
