// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminApiKeyAuthScopes        adminApiKeyAuthContextKey        = "AdminApiKeyAuth.Scopes"
	AdminJWTAuthScopes           adminJWTAuthContextKey           = "AdminJWTAuth.Scopes"
	ApiKeyAuthScopes             apiKeyAuthContextKey             = "ApiKeyAuth.Scopes"
	AuthProviderBearerAuthScopes authProviderBearerAuthContextKey = "AuthProviderBearerAuth.Scopes"
	AuthProviderTeamAuthScopes   authProviderTeamAuthContextKey   = "AuthProviderTeamAuth.Scopes"
)

// Defines values for BuildStatus.
const (
	Building BuildStatus = "building"
	Failed   BuildStatus = "failed"
	Success  BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case Building:
		return true
	case Failed:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// Defines values for TagGroupsSort.
const (
	TagGroupsSortLatestAsc  TagGroupsSort = "latest_asc"
	TagGroupsSortLatestDesc TagGroupsSort = "latest_desc"
	TagGroupsSortNameAsc    TagGroupsSort = "name_asc"
	TagGroupsSortNameDesc   TagGroupsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the TagGroupsSort enum.
func (e TagGroupsSort) Valid() bool {
	switch e {
	case TagGroupsSortLatestAsc:
		return true
	case TagGroupsSortLatestDesc:
		return true
	case TagGroupsSortNameAsc:
		return true
	case TagGroupsSortNameDesc:
		return true
	default:
		return false
	}
}

// Defines values for TemplatesSort.
const (
	TemplatesSortCreatedAtAsc  TemplatesSort = "created_at_asc"
	TemplatesSortCreatedAtDesc TemplatesSort = "created_at_desc"
	TemplatesSortUpdatedAtAsc  TemplatesSort = "updated_at_asc"
	TemplatesSortUpdatedAtDesc TemplatesSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the TemplatesSort enum.
func (e TemplatesSort) Valid() bool {
	switch e {
	case TemplatesSortCreatedAtAsc:
		return true
	case TemplatesSortCreatedAtDesc:
		return true
	case TemplatesSortUpdatedAtAsc:
		return true
	case TemplatesSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesParamsSort.
const (
	GetTemplatesParamsSortCreatedAtAsc  GetTemplatesParamsSort = "created_at_asc"
	GetTemplatesParamsSortCreatedAtDesc GetTemplatesParamsSort = "created_at_desc"
	GetTemplatesParamsSortUpdatedAtAsc  GetTemplatesParamsSort = "updated_at_asc"
	GetTemplatesParamsSortUpdatedAtDesc GetTemplatesParamsSort = "updated_at_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesParamsSort enum.
func (e GetTemplatesParamsSort) Valid() bool {
	switch e {
	case GetTemplatesParamsSortCreatedAtAsc:
		return true
	case GetTemplatesParamsSortCreatedAtDesc:
		return true
	case GetTemplatesParamsSortUpdatedAtAsc:
		return true
	case GetTemplatesParamsSortUpdatedAtDesc:
		return true
	default:
		return false
	}
}

// Defines values for GetTemplatesTemplateIDTagsGroupsParamsSort.
const (
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc  GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc GetTemplatesTemplateIDTagsGroupsParamsSort = "latest_desc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc    GetTemplatesTemplateIDTagsGroupsParamsSort = "name_asc"
	GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc   GetTemplatesTemplateIDTagsGroupsParamsSort = "name_desc"
)

// Valid indicates whether the value is a known member of the GetTemplatesTemplateIDTagsGroupsParamsSort enum.
func (e GetTemplatesTemplateIDTagsGroupsParamsSort) Valid() bool {
	switch e {
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortLatestDesc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameAsc:
		return true
	case GetTemplatesTemplateIDTagsGroupsParamsSortNameDesc:
		return true
	default:
		return false
	}
}

// AddTeamMemberRequest defines model for AddTeamMemberRequest.
type AddTeamMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfile defines model for AdminAuthProviderProfile.
type AdminAuthProviderProfile struct {
	// Email Email address from the configured auth provider.
	Email *string `json:"email"`

	// UserId Internal E2B user identifier.
	UserId openapi_types.UUID `json:"userId"`
}

// AdminAuthProviderProfilesLookupEmailRequest defines model for AdminAuthProviderProfilesLookupEmailRequest.
type AdminAuthProviderProfilesLookupEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuthProviderProfilesResolveRequest defines model for AdminAuthProviderProfilesResolveRequest.
type AdminAuthProviderProfilesResolveRequest struct {
	UserIds []openapi_types.UUID `json:"userIds"`
}

// AdminAuthProviderProfilesResponse defines model for AdminAuthProviderProfilesResponse.
type AdminAuthProviderProfilesResponse struct {
	Profiles []AdminAuthProviderProfile `json:"profiles"`
}

// AdminAuthProviderUserBootstrapRequest defines model for AdminAuthProviderUserBootstrapRequest.
type AdminAuthProviderUserBootstrapRequest struct {
	OidcIssuer      string              `json:"oidc_issuer"`
	OidcUserEmail   openapi_types.Email `json:"oidc_user_email"`
	OidcUserId      string              `json:"oidc_user_id"`
	OidcUserName    *string             `json:"oidc_user_name,omitempty"`
	SignupIp        *string             `json:"signup_ip,omitempty"`
	SignupUserAgent *string             `json:"signup_user_agent,omitempty"`
}

// AdminControlPlaneMemberBatchEntry defines model for AdminControlPlaneMemberBatchEntry.
type AdminControlPlaneMemberBatchEntry struct {
	// Present Whether the user should be a member after this call. Presence is stated rather than implied by inclusion, so one request carries both additions and removals and the caller never has to order them.
	Present bool               `json:"present"`
	UserId  openapi_types.UUID `json:"user_id"`
}

// AdminControlPlaneMemberBatchRequest Desired membership for the listed users, ignoring everyone unlisted. Entries are independent, so applying them in any order converges.
type AdminControlPlaneMemberBatchRequest = []AdminControlPlaneMemberBatchEntry

// AdminControlPlaneMemberUpsertRequest defines model for AdminControlPlaneMemberUpsertRequest.
type AdminControlPlaneMemberUpsertRequest struct {
	AddedBy *openapi_types.UUID `json:"added_by,omitempty"`
}

// AdminControlPlaneProject defines model for AdminControlPlaneProject.
type AdminControlPlaneProject struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// ProjectType The caller's name for the project's tier. Recorded, not interpreted: limits arrive separately and in full through upsertProjectLimits, so nothing here derives behaviour from this value.
	// Deliberately unconstrained. The caller owns the vocabulary and the catalog behind it, and enumerating it here would make adding a tier a cross-repo change to a field this side only stores.
	ProjectType AdminControlPlaneProjectType `json:"project_type"`
	Slug        string                       `json:"slug"`
}

// AdminControlPlaneProjectLimits defines model for AdminControlPlaneProjectLimits.
type AdminControlPlaneProjectLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrent_sandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrent_template_builds"`
	DiskMb                   int64 `json:"disk_mb"`
	EventsTtlDays            int32 `json:"events_ttl_days"`
	MaxRamMb                 int64 `json:"max_ram_mb"`
	MaxSandboxLengthHours    int32 `json:"max_sandbox_length_hours"`
	MaxVcpu                  int32 `json:"max_vcpu"`
}

// AdminControlPlaneProjectType The caller's name for the project's tier. Recorded, not interpreted: limits arrive separately and in full through upsertProjectLimits, so nothing here derives behaviour from this value.
// Deliberately unconstrained. The caller owns the vocabulary and the catalog behind it, and enumerating it here would make adding a tier a cross-repo change to a field this side only stores.
type AdminControlPlaneProjectType = string

// AdminControlPlaneProjectUpsertRequest defines model for AdminControlPlaneProjectUpsertRequest.
type AdminControlPlaneProjectUpsertRequest struct {
	Name string `json:"name"`

	// ProjectType The caller's name for the project's tier. Recorded, not interpreted: limits arrive separately and in full through upsertProjectLimits, so nothing here derives behaviour from this value.
	// Deliberately unconstrained. The caller owns the vocabulary and the catalog behind it, and enumerating it here would make adding a tier a cross-repo change to a field this side only stores.
	ProjectType AdminControlPlaneProjectType `json:"project_type"`
	Slug        string                       `json:"slug"`
}

// AdminTeamBootstrapRequest defines model for AdminTeamBootstrapRequest.
type AdminTeamBootstrapRequest struct {
	// Email Billing/contact email for the team.
	Email openapi_types.Email `json:"email"`

	// Name Team name.
	Name string `json:"name"`
}

// BuildInfo defines model for BuildInfo.
type BuildInfo struct {
	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Names Template names related to this build, if available.
	Names *[]string `json:"names,omitempty"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildStatus Build status mapped for dashboard clients.
type BuildStatus string

// BuildStatusItem defines model for BuildStatusItem.
type BuildStatusItem struct {
	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`
}

// BuildsListResponse defines model for BuildsListResponse.
type BuildsListResponse struct {
	Data []ListedBuild `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// BuildsStatusesResponse defines model for BuildsStatusesResponse.
type BuildsStatusesResponse struct {
	// BuildStatuses List of build statuses
	BuildStatuses []BuildStatusItem `json:"buildStatuses"`
}

// CPUCount CPU cores for the sandbox
type CPUCount = int64

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// DefaultTemplate defines model for DefaultTemplate.
type DefaultTemplate struct {
	Aliases         []DefaultTemplateAlias `json:"aliases"`
	BuildCount      int32                  `json:"buildCount"`
	BuildId         openapi_types.UUID     `json:"buildId"`
	CreatedAt       time.Time              `json:"createdAt"`
	EnvdVersion     *string                `json:"envdVersion,omitempty"`
	Id              string                 `json:"id"`
	Public          bool                   `json:"public"`
	RamMb           int64                  `json:"ramMb"`
	SpawnCount      int64                  `json:"spawnCount"`
	TotalDiskSizeMb *int64                 `json:"totalDiskSizeMb"`
	Vcpu            int64                  `json:"vcpu"`
}

// DefaultTemplateAlias defines model for DefaultTemplateAlias.
type DefaultTemplateAlias struct {
	Alias     string  `json:"alias"`
	Namespace *string `json:"namespace,omitempty"`
}

// DefaultTemplatesResponse defines model for DefaultTemplatesResponse.
type DefaultTemplatesResponse struct {
	Templates []DefaultTemplate `json:"templates"`
}

// DiskSizeMB Disk size for the sandbox in MiB
type DiskSizeMB = int64

// Error defines model for Error.
type Error struct {
	// Code Error code.
	Code int32 `json:"code"`

	// Message Error message.
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Message Human-readable health check result.
	Message string `json:"message"`
}

// ListedBuild defines model for ListedBuild.
type ListedBuild struct {
	// CpuCount CPU cores configured for the build.
	CpuCount int64 `json:"cpuCount"`

	// CreatedAt Build creation timestamp in RFC3339 format.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB configured for the build, if recorded.
	DiskSizeMB *int64 `json:"diskSizeMB"`

	// EnvdVersion envd version the build was created with, if recorded.
	EnvdVersion *string `json:"envdVersion"`

	// FinishedAt Build completion timestamp in RFC3339 format, if finished.
	FinishedAt *time.Time `json:"finishedAt"`

	// Id Identifier of the build.
	Id openapi_types.UUID `json:"id"`

	// MemoryMB Memory in MiB configured for the build.
	MemoryMB int64 `json:"memoryMB"`

	// Status Build status mapped for dashboard clients.
	Status BuildStatus `json:"status"`

	// StatusMessage Failure message when status is `failed`, otherwise `null`.
	StatusMessage *string `json:"statusMessage"`

	// Template Template alias when present, otherwise template ID.
	Template string `json:"template"`

	// TemplateId Identifier of the template.
	TemplateId string `json:"templateId"`
}

// MemoryMB Memory for the sandbox in MiB
type MemoryMB = int64

// SandboxRecord defines model for SandboxRecord.
type SandboxRecord struct {
	// Alias Alias of the template
	Alias *string `json:"alias,omitempty"`

	// CpuCount CPU cores for the sandbox
	CpuCount CPUCount `json:"cpuCount"`

	// DiskSizeMB Disk size for the sandbox in MiB
	DiskSizeMB DiskSizeMB `json:"diskSizeMB"`

	// Domain Base domain where the sandbox traffic is accessible
	Domain *string `json:"domain,omitempty"`

	// EventsRetentionExpired Whether the sandbox ended more than the team's events retention window ago, so its events data is no longer available
	EventsRetentionExpired bool `json:"eventsRetentionExpired"`

	// MemoryMB Memory for the sandbox in MiB
	MemoryMB MemoryMB `json:"memoryMB"`

	// RetentionExpired Whether the sandbox ended more than the fixed retention window ago, so its monitoring and logs data is no longer available
	RetentionExpired bool `json:"retentionExpired"`

	// SandboxID Identifier of the sandbox
	SandboxID string `json:"sandboxID"`

	// StartedAt Time when the sandbox was started
	StartedAt time.Time `json:"startedAt"`

	// StoppedAt Time when the sandbox was stopped
	StoppedAt *time.Time `json:"stoppedAt,omitempty"`

	// TemplateID Identifier of the template from which is the sandbox created
	TemplateID string `json:"templateID"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	AddedBy           *openapi_types.UUID `json:"addedBy,omitempty"`
	CreatedAt         *time.Time          `json:"createdAt"`
	Email             string              `json:"email"`
	Id                openapi_types.UUID  `json:"id"`
	IsDefault         bool                `json:"isDefault"`
	Name              *string             `json:"name,omitempty"`
	ProfilePictureUrl *string             `json:"profilePictureUrl,omitempty"`
	Providers         []string            `json:"providers"`
}

// TeamMembersResponse defines model for TeamMembersResponse.
type TeamMembersResponse struct {
	Members []TeamMember `json:"members"`
}

// TeamResolveResponse defines model for TeamResolveResponse.
type TeamResolveResponse struct {
	Id   openapi_types.UUID `json:"id"`
	Slug string             `json:"slug"`
}

// TeamTemplate defines model for TeamTemplate.
type TeamTemplate struct {
	Aliases    []string           `json:"aliases"`
	BuildCount int32              `json:"buildCount"`
	BuildID    openapi_types.UUID `json:"buildID"`
	CpuCount   int64              `json:"cpuCount"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  *struct {
		Email *string            `json:"email,omitempty"`
		Id    openapi_types.UUID `json:"id"`
	} `json:"createdBy"`
	DefaultDescription *string    `json:"defaultDescription,omitempty"`
	DiskSizeMB         *int64     `json:"diskSizeMB"`
	EnvdVersion        *string    `json:"envdVersion"`
	IsDefault          bool       `json:"isDefault"`
	LastSpawnedAt      *time.Time `json:"lastSpawnedAt"`
	MemoryMB           int64      `json:"memoryMB"`
	Names              []string   `json:"names"`
	Public             bool       `json:"public"`
	SpawnCount         int64      `json:"spawnCount"`
	TemplateID         string     `json:"templateID"`
	UpdatedAt          time.Time  `json:"updatedAt"`
}

// TeamTemplatesResponse defines model for TeamTemplatesResponse.
type TeamTemplatesResponse struct {
	Data []TeamTemplate `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateDetail Dashboard-shaped single-template read. Mirrors the infra-api `Template` schema fields the dashboard renders.
type TemplateDetail struct {
	// Aliases Aliases of the template.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Aliases []string `json:"aliases"`

	// BuildCount Number of times the template was built.
	BuildCount int32 `json:"buildCount"`

	// BuildID Identifier of the latest ready build for the template, or the zero UUID when none.
	BuildID string `json:"buildID"`

	// CpuCount vCPU count of the latest ready default build, or `null` when none.
	CpuCount *CPUCount `json:"cpuCount"`

	// CreatedAt Time when the template was created.
	CreatedAt time.Time `json:"createdAt"`

	// DiskSizeMB Disk size in MiB of the latest ready default build, or `null` when none.
	DiskSizeMB *DiskSizeMB `json:"diskSizeMB"`

	// EnvdVersion envd version of the latest ready default build, or `null` when none.
	EnvdVersion *string `json:"envdVersion"`

	// LastSpawnedAt Time when the template was last used.
	LastSpawnedAt *time.Time `json:"lastSpawnedAt"`

	// MemoryMB Memory in MiB of the latest ready default build, or `null` when none.
	MemoryMB *MemoryMB `json:"memoryMB"`

	// Names Names of the template (namespace/alias format when namespaced).
	Names []string `json:"names"`

	// Public Whether the template is public or only accessible by the team.
	Public bool `json:"public"`

	// SpawnCount Number of times the template was used.
	SpawnCount int64 `json:"spawnCount"`

	// TemplateID Identifier of the template.
	TemplateID string `json:"templateID"`

	// UpdatedAt Time when the template was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// TemplateTagAssignment defines model for TemplateTagAssignment.
type TemplateTagAssignment struct {
	// AssignedAt Time when the tag was assigned to the build.
	AssignedAt time.Time `json:"assignedAt"`

	// AssignmentId Identifier of the tag assignment event.
	AssignmentId openapi_types.UUID `json:"assignmentId"`

	// BuildCreatedAt Time when the assigned build was created.
	BuildCreatedAt time.Time `json:"buildCreatedAt"`

	// BuildFinishedAt Time when the assigned build finished.
	BuildFinishedAt *time.Time `json:"buildFinishedAt"`

	// BuildId Identifier of the assigned build.
	BuildId openapi_types.UUID `json:"buildId"`
}

// TemplateTagAssignmentsResponse defines model for TemplateTagAssignmentsResponse.
type TemplateTagAssignmentsResponse struct {
	// Data Ready assignment events for the tag, sorted latest first.
	Data []TemplateTagAssignment `json:"data"`

	// NextCursor Cursor to pass to the next list request, or `null` if there is no next page.
	NextCursor *string `json:"nextCursor"`
}

// TemplateTagExistsResponse defines model for TemplateTagExistsResponse.
type TemplateTagExistsResponse struct {
	// Exists Whether the template tag has at least one ready assignment.
	Exists bool `json:"exists"`

	// NormalizedTag Normalized template tag name.
	NormalizedTag string `json:"normalizedTag"`
}

// TemplateTagGroup defines model for TemplateTagGroup.
type TemplateTagGroup struct {
	// Assignments Ready assignment events for this tag, sorted latest first.
	Assignments []TemplateTagAssignment `json:"assignments"`

	// HasMore Whether more ready assignment events exist beyond the requested assignment limit.
	HasMore bool `json:"hasMore"`

	// Tag Template tag name.
	Tag string `json:"tag"`
}

// TemplateTagGroupsResponse defines model for TemplateTagGroupsResponse.
type TemplateTagGroupsResponse struct {
	// NextCursor Cursor to pass as `tagsCursor` for the next page, or `null` if there is no next page.
	NextCursor *string            `json:"nextCursor"`
	Tags       []TemplateTagGroup `json:"tags"`
}

// TemplateTagsCountResponse defines model for TemplateTagsCountResponse.
type TemplateTagsCountResponse struct {
	// Total Total distinct ready tags for the template.
	Total int64 `json:"total"`
}

// UpdateTeamRequest defines model for UpdateTeamRequest.
type UpdateTeamRequest struct {
	Name              *string `json:"name,omitempty"`
	ProfilePictureUrl *string `json:"profilePictureUrl,omitempty"`
}

// UpdateTeamResponse defines model for UpdateTeamResponse.
type UpdateTeamResponse struct {
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl,omitempty"`
}

// UserTeam defines model for UserTeam.
type UserTeam struct {
	BlockedReason     *string            `json:"blockedReason"`
	CreatedAt         time.Time          `json:"createdAt"`
	Email             string             `json:"email"`
	Id                openapi_types.UUID `json:"id"`
	IsBanned          bool               `json:"isBanned"`
	IsBlocked         bool               `json:"isBlocked"`
	IsDefault         bool               `json:"isDefault"`
	Limits            UserTeamLimits     `json:"limits"`
	Name              string             `json:"name"`
	ProfilePictureUrl *string            `json:"profilePictureUrl"`
	Slug              string             `json:"slug"`
	Tier              string             `json:"tier"`
}

// UserTeamLimits defines model for UserTeamLimits.
type UserTeamLimits struct {
	ConcurrentSandboxes      int32 `json:"concurrentSandboxes"`
	ConcurrentTemplateBuilds int32 `json:"concurrentTemplateBuilds"`
	DiskMb                   int32 `json:"diskMb"`
	EventsTtlDays            int32 `json:"eventsTtlDays"`
	MaxLengthHours           int64 `json:"maxLengthHours"`
	MaxRamMb                 int32 `json:"maxRamMb"`
	MaxVcpu                  int32 `json:"maxVcpu"`
}

// UserTeamsResponse defines model for UserTeamsResponse.
type UserTeamsResponse struct {
	Teams []UserTeam `json:"teams"`
}

// BuildId defines model for build_id.
type BuildId = openapi_types.UUID

// BuildIdOrTemplate defines model for build_id_or_template.
type BuildIdOrTemplate = string

// BuildIds defines model for build_ids.
type BuildIds = []openapi_types.UUID

// BuildStatuses defines model for build_statuses.
type BuildStatuses = []BuildStatus

// BuildsCursor defines model for builds_cursor.
type BuildsCursor = string

// BuildsLimit defines model for builds_limit.
type BuildsLimit = int32

// SandboxID defines model for sandboxID.
type SandboxID = string

// Tag defines model for tag.
type Tag = string

// TagAssignmentLimit defines model for tag_assignment_limit.
type TagAssignmentLimit = int32

// TagAssignmentsCursor defines model for tag_assignments_cursor.
type TagAssignmentsCursor = string

// TagAssignmentsLimit defines model for tag_assignments_limit.
type TagAssignmentsLimit = int32

// TagGroupsCursor defines model for tag_groups_cursor.
type TagGroupsCursor = string

// TagGroupsLimit defines model for tag_groups_limit.
type TagGroupsLimit = int32

// TagGroupsSearch defines model for tag_groups_search.
type TagGroupsSearch = string

// TagGroupsSort defines model for tag_groups_sort.
type TagGroupsSort string

// TagPath defines model for tag_path.
type TagPath = string

// TeamID defines model for teamID.
type TeamID = openapi_types.UUID

// TeamSlug defines model for teamSlug.
type TeamSlug = string

// TemplateID defines model for templateID.
type TemplateID = string

// TemplatesCursor defines model for templates_cursor.
type TemplatesCursor = string

// TemplatesLimit defines model for templates_limit.
type TemplatesLimit = int32

// TemplatesPublic defines model for templates_public.
type TemplatesPublic = bool

// TemplatesSearch defines model for templates_search.
type TemplatesSearch = string

// TemplatesSort defines model for templates_sort.
type TemplatesSort string

// UserId defines model for userId.
type UserId = openapi_types.UUID

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N409 defines model for 409.
type N409 = Error

// N500 defines model for 500.
type N500 = Error

// N501 defines model for 501.
type N501 = Error

// N502 defines model for 502.
type N502 = Error

// adminApiKeyAuthContextKey is the context key for AdminApiKeyAuth security scheme
type adminApiKeyAuthContextKey string

// adminJWTAuthContextKey is the context key for AdminJWTAuth security scheme
type adminJWTAuthContextKey string

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// authProviderBearerAuthContextKey is the context key for AuthProviderBearerAuth security scheme
type authProviderBearerAuthContextKey string

// authProviderTeamAuthContextKey is the context key for AuthProviderTeamAuth security scheme
type authProviderTeamAuthContextKey string

// GetBuildsParams defines parameters for GetBuilds.
type GetBuildsParams struct {
	// BuildIdOrTemplate Optional filter by build identifier, template identifier, or template alias.
	BuildIdOrTemplate *BuildIdOrTemplate `form:"build_id_or_template,omitempty" json:"build_id_or_template,omitempty"`

	// Statuses Comma-separated list of build statuses to include.
	Statuses *BuildStatuses `form:"statuses,omitempty" json:"statuses,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *BuildsLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `created_at|build_id` format.
	Cursor *BuildsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetBuildsStatusesParams defines parameters for GetBuildsStatuses.
type GetBuildsStatusesParams struct {
	// BuildIds Comma-separated list of build IDs to get statuses for.
	BuildIds BuildIds `form:"build_ids" json:"build_ids"`
}

// GetTeamsResolveParams defines parameters for GetTeamsResolve.
type GetTeamsResolveParams struct {
	// Slug Team slug to resolve.
	Slug TeamSlug `form:"slug" json:"slug"`
}

// GetTemplatesParams defines parameters for GetTemplates.
type GetTemplatesParams struct {
	// Public Filter templates by visibility (true = public, false = internal).
	Public *TemplatesPublic `form:"public,omitempty" json:"public,omitempty"`

	// Search Case-insensitive substring match on template names, aliases, and template id.
	Search *TemplatesSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort column and direction.
	Sort *GetTemplatesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit Maximum number of items to return per page.
	Limit *TemplatesLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Cursor returned by the previous list response in `{sort}|{value}|{templateID}` format. Rejected if its sort does not match the request.
	Cursor *TemplatesCursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetTemplatesParamsSort defines parameters for GetTemplates.
type GetTemplatesParamsSort string

// GetTemplatesTemplateIDTagsExistsParams defines parameters for GetTemplatesTemplateIDTagsExists.
type GetTemplatesTemplateIDTagsExistsParams struct {
	// Tag Template tag name to check.
	Tag Tag `form:"tag" json:"tag"`
}

// GetTemplatesTemplateIDTagsGroupsParams defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParams struct {
	// AssignmentLimit Maximum number of ready assignment rows to return per tag.
	AssignmentLimit *TagAssignmentLimit `form:"assignmentLimit,omitempty" json:"assignmentLimit,omitempty"`

	// TagsLimit Maximum number of distinct tags to return per page.
	TagsLimit *TagGroupsLimit `form:"tagsLimit,omitempty" json:"tagsLimit,omitempty"`

	// TagsCursor Cursor returned by the previous list response in `{sort}|{latest_assigned_at}|{tag}` format (sort-tagged, RFC3339Nano).
	TagsCursor *TagGroupsCursor `form:"tagsCursor,omitempty" json:"tagsCursor,omitempty"`

	// Search Case-insensitive substring filter on tag name. Allowed characters are `a-z`, `0-9`, `.`, `_`, `-`.
	Search *TagGroupsSearch `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort order for the returned tag groups.
	Sort *GetTemplatesTemplateIDTagsGroupsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// GetTemplatesTemplateIDTagsGroupsParamsSort defines parameters for GetTemplatesTemplateIDTagsGroups.
type GetTemplatesTemplateIDTagsGroupsParamsSort string

// GetTemplatesTemplateIDTagsTagAssignmentsParams defines parameters for GetTemplatesTemplateIDTagsTagAssignments.
type GetTemplatesTemplateIDTagsTagAssignmentsParams struct {
	// Cursor Cursor returned by the previous list response in `assigned_at|assignment_id` format.
	Cursor *TagAssignmentsCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of assignment rows to return per page.
	Limit *TagAssignmentsLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostAdminTeamsBootstrapJSONRequestBody defines body for PostAdminTeamsBootstrap for application/json ContentType.
type PostAdminTeamsBootstrapJSONRequestBody = AdminTeamBootstrapRequest

// PostAdminUserProfilesByEmailJSONRequestBody defines body for PostAdminUserProfilesByEmail for application/json ContentType.
type PostAdminUserProfilesByEmailJSONRequestBody = AdminAuthProviderProfilesLookupEmailRequest

// PostAdminUserProfilesResolveJSONRequestBody defines body for PostAdminUserProfilesResolve for application/json ContentType.
type PostAdminUserProfilesResolveJSONRequestBody = AdminAuthProviderProfilesResolveRequest

// PostAdminUsersBootstrapJSONRequestBody defines body for PostAdminUsersBootstrap for application/json ContentType.
type PostAdminUsersBootstrapJSONRequestBody = AdminAuthProviderUserBootstrapRequest

// PostTeamsJSONRequestBody defines body for PostTeams for application/json ContentType.
type PostTeamsJSONRequestBody = CreateTeamRequest

// PatchTeamsTeamIDJSONRequestBody defines body for PatchTeamsTeamID for application/json ContentType.
type PatchTeamsTeamIDJSONRequestBody = UpdateTeamRequest

// PostTeamsTeamIDMembersJSONRequestBody defines body for PostTeamsTeamIDMembers for application/json ContentType.
type PostTeamsTeamIDMembersJSONRequestBody = AddTeamMemberRequest

// UpsertProjectJSONRequestBody defines body for UpsertProject for application/json ContentType.
type UpsertProjectJSONRequestBody = AdminControlPlaneProjectUpsertRequest

// UpsertProjectLimitsJSONRequestBody defines body for UpsertProjectLimits for application/json ContentType.
type UpsertProjectLimitsJSONRequestBody = AdminControlPlaneProjectLimits

// BatchSyncProjectMembersJSONRequestBody defines body for BatchSyncProjectMembers for application/json ContentType.
type BatchSyncProjectMembersJSONRequestBody = AdminControlPlaneMemberBatchRequest

// UpsertProjectMemberJSONRequestBody defines body for UpsertProjectMember for application/json ContentType.
type UpsertProjectMemberJSONRequestBody = AdminControlPlaneMemberUpsertRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bootstrap team
	// (POST /admin/teams/bootstrap)
	PostAdminTeamsBootstrap(c *gin.Context)
	// Lookup user profiles by email
	// (POST /admin/user-profiles/by-email)
	PostAdminUserProfilesByEmail(c *gin.Context)
	// Resolve user profiles
	// (POST /admin/user-profiles/resolve)
	PostAdminUserProfilesResolve(c *gin.Context)
	// User profile
	// (GET /admin/user-profiles/{userId})
	GetAdminUserProfilesUserId(c *gin.Context, userId UserId)
	// Bootstrap auth provider user
	// (POST /admin/users/bootstrap)
	PostAdminUsersBootstrap(c *gin.Context)
	// Delete user
	// (DELETE /admin/users/{userId})
	DeleteAdminUsersUserId(c *gin.Context, userId UserId)
	// List team builds
	// (GET /builds)
	GetBuilds(c *gin.Context, params GetBuildsParams)
	// Build statuses
	// (GET /builds/statuses)
	GetBuildsStatuses(c *gin.Context, params GetBuildsStatusesParams)
	// Build details
	// (GET /builds/{build_id})
	GetBuildsBuildId(c *gin.Context, buildId BuildId)
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Sandbox record
	// (GET /sandboxes/{sandboxID}/record)
	GetSandboxesSandboxIDRecord(c *gin.Context, sandboxID SandboxID)
	// List user teams
	// (GET /teams)
	GetTeams(c *gin.Context)
	// Create team
	// (POST /teams)
	PostTeams(c *gin.Context)
	// Resolve team identity
	// (GET /teams/resolve)
	GetTeamsResolve(c *gin.Context, params GetTeamsResolveParams)
	// Update team
	// (PATCH /teams/{teamID})
	PatchTeamsTeamID(c *gin.Context, teamID TeamID)
	// List team members
	// (GET /teams/{teamID}/members)
	GetTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Add team member
	// (POST /teams/{teamID}/members)
	PostTeamsTeamIDMembers(c *gin.Context, teamID TeamID)
	// Remove team member
	// (DELETE /teams/{teamID}/members/{userId})
	DeleteTeamsTeamIDMembersUserId(c *gin.Context, teamID TeamID, userId UserId)
	// List team templates
	// (GET /templates)
	GetTemplates(c *gin.Context, params GetTemplatesParams)
	// List default templates
	// (GET /templates/defaults)
	GetTemplatesDefaults(c *gin.Context)
	// Template
	// (GET /templates/{templateID})
	GetTemplatesTemplateID(c *gin.Context, templateID TemplateID)
	// Count template tags
	// (GET /templates/{templateID}/tags/count)
	GetTemplatesTemplateIDTagsCount(c *gin.Context, templateID TemplateID)
	// Check ready template tag existence
	// (GET /templates/{templateID}/tags/exists)
	GetTemplatesTemplateIDTagsExists(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsExistsParams)
	// List template tag groups
	// (GET /templates/{templateID}/tags/groups)
	GetTemplatesTemplateIDTagsGroups(c *gin.Context, templateID TemplateID, params GetTemplatesTemplateIDTagsGroupsParams)
	// List ready assignments for a single template tag
	// (GET /templates/{templateID}/tags/{tag}/assignments)
	GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context, templateID TemplateID, tag TagPath, params GetTemplatesTemplateIDTagsTagAssignmentsParams)
	// Delete a project and its control-plane state (v1).
	// (DELETE /v1/management/projects/{teamID})
	DeleteProject(c *gin.Context, teamID TeamID)
	// Create or reconcile a project (v1).
	// (PUT /v1/management/projects/{teamID})
	UpsertProject(c *gin.Context, teamID TeamID)
	// Reconcile effective limits for a project (v1).
	// (PUT /v1/management/projects/{teamID}/limits)
	UpsertProjectLimits(c *gin.Context, teamID TeamID)
	// Reconcile many project memberships in one call (v1).
	// (POST /v1/management/projects/{teamID}/members/batch)
	BatchSyncProjectMembers(c *gin.Context, teamID TeamID)
	// Remove a project member (v1).
	// (DELETE /v1/management/projects/{teamID}/members/{userId})
	DeleteProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Reconcile an opaque user UUID as a project member (v1).
	// (PUT /v1/management/projects/{teamID}/members/{userId})
	UpsertProjectMember(c *gin.Context, teamID TeamID, userId UserId)
	// Purge shard-local membership and access-token state for an opaque user UUID (v1).
	// (DELETE /v1/management/users/{userId})
	PurgeUser(c *gin.Context, userId UserId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAdminTeamsBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminTeamsBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminTeamsBootstrap(c)
}

// PostAdminUserProfilesByEmail operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesByEmail(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesByEmail(c)
}

// PostAdminUserProfilesResolve operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserProfilesResolve(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUserProfilesResolve(c)
}

// GetAdminUserProfilesUserId operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUserProfilesUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminUserProfilesUserId(c, userId)
}

// PostAdminUsersBootstrap operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUsersBootstrap(c *gin.Context) {

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAdminUsersBootstrap(c)
}

// DeleteAdminUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminUsersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminUsersUserId(c, userId)
}

// GetBuilds operation middleware
func (siw *ServerInterfaceWrapper) GetBuilds(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsParams

	// ------------- Optional query parameter "build_id_or_template" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "build_id_or_template", c.Request.URL.Query(), &params.BuildIdOrTemplate, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id_or_template: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "statuses", c.Request.URL.Query(), &params.Statuses, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter statuses: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuilds(c, params)
}

// GetBuildsStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsStatuses(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBuildsStatusesParams

	// ------------- Required query parameter "build_ids" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, true, "build_ids", c.Request.URL.Query(), &params.BuildIds, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_ids: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsStatuses(c, params)
}

// GetBuildsBuildId operation middleware
func (siw *ServerInterfaceWrapper) GetBuildsBuildId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "build_id" -------------
	var buildId BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "build_id", c.Param("build_id"), &buildId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter build_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBuildsBuildId(c, buildId)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetSandboxesSandboxIDRecord operation middleware
func (siw *ServerInterfaceWrapper) GetSandboxesSandboxIDRecord(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "sandboxID" -------------
	var sandboxID SandboxID

	err = runtime.BindStyledParameterWithOptions("simple", "sandboxID", c.Param("sandboxID"), &sandboxID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sandboxID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSandboxesSandboxIDRecord(c, sandboxID)
}

// GetTeams operation middleware
func (siw *ServerInterfaceWrapper) GetTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeams(c)
}

// PostTeams operation middleware
func (siw *ServerInterfaceWrapper) PostTeams(c *gin.Context) {

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeams(c)
}

// GetTeamsResolve operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsResolve(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamsResolveParams

	// ------------- Required query parameter "slug" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "slug", c.Request.URL.Query(), &params.Slug, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsResolve(c, params)
}

// PatchTeamsTeamID operation middleware
func (siw *ServerInterfaceWrapper) PatchTeamsTeamID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchTeamsTeamID(c, teamID)
}

// GetTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) GetTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamsTeamIDMembers(c, teamID)
}

// PostTeamsTeamIDMembers operation middleware
func (siw *ServerInterfaceWrapper) PostTeamsTeamIDMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamsTeamIDMembers(c, teamID)
}

// DeleteTeamsTeamIDMembersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeamsTeamIDMembersUserId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTeamsTeamIDMembersUserId(c, teamID, userId)
}

// GetTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetTemplates(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesParams

	// ------------- Optional query parameter "public" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "public", c.Request.URL.Query(), &params.Public, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter public: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplates(c, params)
}

// GetTemplatesDefaults operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesDefaults(c *gin.Context) {

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesDefaults(c)
}

// GetTemplatesTemplateID operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateID(c, templateID)
}

// GetTemplatesTemplateIDTagsCount operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsCount(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsCount(c, templateID)
}

// GetTemplatesTemplateIDTagsExists operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsExists(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsExistsParams

	// ------------- Required query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tag", c.Request.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsExists(c, templateID, params)
}

// GetTemplatesTemplateIDTagsGroups operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsGroups(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsGroupsParams

	// ------------- Optional query parameter "assignmentLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignmentLimit", c.Request.URL.Query(), &params.AssignmentLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter assignmentLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsLimit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsLimit", c.Request.URL.Query(), &params.TagsLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsLimit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tagsCursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tagsCursor", c.Request.URL.Query(), &params.TagsCursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tagsCursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsGroups(c, templateID, params)
}

// GetTemplatesTemplateIDTagsTagAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatesTemplateIDTagsTagAssignments(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "templateID" -------------
	var templateID TemplateID

	err = runtime.BindStyledParameterWithOptions("simple", "templateID", c.Param("templateID"), &templateID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag TagPath

	err = runtime.BindStyledParameterWithOptions("simple", "tag", c.Param("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	c.Set(string(AuthProviderBearerAuthScopes), []string{})

	c.Set(string(AuthProviderTeamAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatesTemplateIDTagsTagAssignmentsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", c.Request.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursor: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatesTemplateIDTagsTagAssignments(c, templateID, tag, params)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProject(c, teamID)
}

// UpsertProject operation middleware
func (siw *ServerInterfaceWrapper) UpsertProject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProject(c, teamID)
}

// UpsertProjectLimits operation middleware
func (siw *ServerInterfaceWrapper) UpsertProjectLimits(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProjectLimits(c, teamID)
}

// BatchSyncProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) BatchSyncProjectMembers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BatchSyncProjectMembers(c, teamID)
}

// DeleteProjectMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProjectMember(c, teamID, userId)
}

// UpsertProjectMember operation middleware
func (siw *ServerInterfaceWrapper) UpsertProjectMember(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "teamID" -------------
	var teamID TeamID

	err = runtime.BindStyledParameterWithOptions("simple", "teamID", c.Param("teamID"), &teamID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamID: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertProjectMember(c, teamID, userId)
}

// PurgeUser operation middleware
func (siw *ServerInterfaceWrapper) PurgeUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(AdminJWTAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PurgeUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/admin/teams/bootstrap", wrapper.PostAdminTeamsBootstrap)
	router.POST(options.BaseURL+"/admin/user-profiles/by-email", wrapper.PostAdminUserProfilesByEmail)
	router.POST(options.BaseURL+"/admin/user-profiles/resolve", wrapper.PostAdminUserProfilesResolve)
	router.GET(options.BaseURL+"/admin/user-profiles/:userId", wrapper.GetAdminUserProfilesUserId)
	router.POST(options.BaseURL+"/admin/users/bootstrap", wrapper.PostAdminUsersBootstrap)
	router.DELETE(options.BaseURL+"/admin/users/:userId", wrapper.DeleteAdminUsersUserId)
	router.GET(options.BaseURL+"/builds", wrapper.GetBuilds)
	router.GET(options.BaseURL+"/builds/statuses", wrapper.GetBuildsStatuses)
	router.GET(options.BaseURL+"/builds/:build_id", wrapper.GetBuildsBuildId)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/sandboxes/:sandboxID/record", wrapper.GetSandboxesSandboxIDRecord)
	router.GET(options.BaseURL+"/teams", wrapper.GetTeams)
	router.POST(options.BaseURL+"/teams", wrapper.PostTeams)
	router.GET(options.BaseURL+"/teams/resolve", wrapper.GetTeamsResolve)
	router.PATCH(options.BaseURL+"/teams/:teamID", wrapper.PatchTeamsTeamID)
	router.GET(options.BaseURL+"/teams/:teamID/members", wrapper.GetTeamsTeamIDMembers)
	router.POST(options.BaseURL+"/teams/:teamID/members", wrapper.PostTeamsTeamIDMembers)
	router.DELETE(options.BaseURL+"/teams/:teamID/members/:userId", wrapper.DeleteTeamsTeamIDMembersUserId)
	router.GET(options.BaseURL+"/templates", wrapper.GetTemplates)
	router.GET(options.BaseURL+"/templates/defaults", wrapper.GetTemplatesDefaults)
	router.GET(options.BaseURL+"/templates/:templateID", wrapper.GetTemplatesTemplateID)
	router.GET(options.BaseURL+"/templates/:templateID/tags/count", wrapper.GetTemplatesTemplateIDTagsCount)
	router.GET(options.BaseURL+"/templates/:templateID/tags/exists", wrapper.GetTemplatesTemplateIDTagsExists)
	router.GET(options.BaseURL+"/templates/:templateID/tags/groups", wrapper.GetTemplatesTemplateIDTagsGroups)
	router.GET(options.BaseURL+"/templates/:templateID/tags/:tag/assignments", wrapper.GetTemplatesTemplateIDTagsTagAssignments)
	router.DELETE(options.BaseURL+"/v1/management/projects/:teamID", wrapper.DeleteProject)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID", wrapper.UpsertProject)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID/limits", wrapper.UpsertProjectLimits)
	router.POST(options.BaseURL+"/v1/management/projects/:teamID/members/batch", wrapper.BatchSyncProjectMembers)
	router.DELETE(options.BaseURL+"/v1/management/projects/:teamID/members/:userId", wrapper.DeleteProjectMember)
	router.PUT(options.BaseURL+"/v1/management/projects/:teamID/members/:userId", wrapper.UpsertProjectMember)
	router.DELETE(options.BaseURL+"/v1/management/users/:userId", wrapper.PurgeUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17c9s4kv8qKN1W7eyVZDuP2bpx1f4Rx5md7CWzqdjZuapcTobIloQ1CXAAULbi9Xe/woMkSIIkKEue",
	"ZDb/zMQiCDS6f2j0A2jeTSKWZowClWJyejfJMMcpSOD6r0VOknhOYvXvGETESSYJo5PTyesYqCRLAhyx",
	"JZJrQLrt0WQ6Iep5huV6Mp1QnMLktOpnOuHwa044xJNTyXOYTkS0hhSrAZaMp1hOTid5rlvKbabeFZIT",
	"uprc30/LbuaMzyWkWYIltEn7u/4HTtCSJBI4WmwNbYiUNE9R8XrtR8ar33FCsCin82sOfNueT40Qdy7d",
	"tIs2wS9ZmuKZAMV7CTFKiJCKq4bq1+cCSYZWIJGQWOYCBFoyrkiD2yxhMUxOlzgR0E+q6OU9kZCKACFM",
	"Jym+fW0aPzk5KZ9jzrEaNKfk1xxsAzXI/XQi5DZRbVTXk5ITxVzGsqPkgWSI0CjJYwhlRTmkd+Z/4LCc",
	"nE7+47haEMemmTg+U0Nf6NfVDGqT7pqhmEc5F4x7Jqh/RxxkzinECqBqAWUcNoTlwkyYg8gYFYAIRVcR",
	"B8WKOZb/KuR5hYyouiBqBw8ApZgnJCWyTedbfEvSPEU0TxdmnWtmKc4b2lEGHGV4BV1EmI5dGmJY4jyR",
	"k9PvT6YV2AiVz55ONLjUiBZbKaH2r5LlhEpYAdfEC0zjBbt9fR6inWzjDv1UddW3SNr8k3jVHvyyUCES",
	"r5AaQDEsWkN03cUm1U3fwCmhb4Cu5NplRZ2MORaCrGgKVIaLkwOOt6h6E3F20xSvxKsusqsX33TL+c99",
	"Yn76/aCU63Pb56IyvZpV5XBvT0urSXewUPrF8ZutNjWfFWd5tk8R3AnG5f2/7tRyEXLuSOT+X3cSr+4L",
	"UaDvVMuZxKsVxFP0/seXz549++FnTNmfehaVeBkqKTuzYCHFREhCI6mWxxgRqeY9i0Wth72JSQDm0doj",
	"JixgRqgAKogkG0AiXxh2FBYTo6XuOkIvkoTdQIyiNeY4UpYhwhzQFZ59vpqiq5PZD+p/R+o/c/Wf2VXX",
	"5C1BNc2GbwvN9ufnU6WVJXD16v99xLPPJ7MfjuazT//5h8m0X24KHO2JXjAuEeMxcIUijcUSm2p+5uVO",
	"alWfXilNLFzVaMr0oEocHxu/lpCObJfuP3WbT12T0nvT8LbSsZc9eDMBnIbtqaplFxGmk4eZ+6qTiyT3",
	"brE4RSLJV2bpCZZsOpecajZ2W7esDmWDad3JirKz3ag4hMLd4CQHpWNL4kpVe4Tewz8hUpY3URafQOod",
	"FDMQiDKJUiyjtV1Mv+YgHrhNlpP8Oo3Qiv4sXyQkak/gR6NTy4ZKShsiyIIkRG7RdwoI6C/IvD5F2n9B",
	"f0FqEE5x0rm/2fE87F0wlgCmDfp22A6MqNVuUOgeNbaYGudY/4PGris9QvP3QaFHnUcsyVOqx40Jh0g9",
	"20GDVw5VU4s7T4zCbjfNs7jexPmhW7PnAvjroEiKatmhTGwnD9Gr9+ploxK03/v85ET9L2JUAtVsx1mW",
	"kAgr+o7/KRSRd07/fX7yK84ZN2PUJ3mG40JdKAf5+cmTw4/5IpdrxVrTKwLTTg3+7PCD/8j4gsQxUDPi",
	"88OP+DOTaMlyGpsRfzj8iC8ZXSYk0hL9/jFQdAF8A7yS5PePAaO/Z8ANgojZAEmaJaD8M4gNEU8PT8SH",
	"TEiujB479/tixesl/CKOlUX0FtQW+d4us9O7ScZZBlwSs9AhxSSpaQjzi09ZVerlo21V6TS2UOaBmvqL",
	"OCVULbN3nG1IDPwdZ0uSQM/Y9Wm9Uj8jHMcchEBLzlKtACNGl2SVc4gRzuUaZbZ7pRRpniR4ocYwiq8V",
	"oOzUs3ZDRa+enmkV64R+VcfD9qjLlFIRj+eOeMPYdZ7puX8BwhLvjf3cSYqZqnhQmDgltPgzIGbs5bUY",
	"PSu9x7Xnk9kWwdHfTpi3QsENwsuRgij/IICfMSaF5DjrlAYjcTQnQuTAB725qWmt+DcPBpT7ksn8BI9h",
	"jJS74TUqyIrm2ZxkHkuwfKq7xCurVPth73KlMYE2Ezql8ZJRyVnyLsEUjDI9UxbwKyr51ocjEJa4uqb5",
	"ZQ1yDby05ZBYszyJ0QIQRqnuF+GldgrWRKAIJ8kReqd7i0DtMkLqxAfHthtM9aZDjIunsx6CMDpFgiFG",
	"S0cMRZhzojwMJtdKqxJFkNDGMoeUbXBi/tA6FicJcERB7ahrrB0qEyuRa9BufdObMKrVYmK8tjSyKJg2",
	"VgbOeqgz+xyEGsXyVaxJVgZ7lPsLsRaBmCKyokx7NWrGW8W2nJoWR0hJWDEOc+Umx5ABVXuDZrDazbfq",
	"PcUX5URjurWcihjdAF+BiSEFq5JemDV059Pn7XRTRycfMgFcdioOHMcQzxfbwNjLoHDecaafqa6T5O/L",
	"yenHkXO3PdTpvp82Cd8FcCT2IOxTzzR0UFa0uRYxGuWcA5VzmySC+gZYRg164gRTt5vCzZ2b5NsOncVE",
	"XM/TRfPNPz8ffBM2OhchZTKP8XaXsVN8O+c43W149bLl4jzRO8p8zXK+Kx2bKMtHv9oAile+PZQ6I9eY",
	"UUmlV9htEXwasdYudcNWMLTU5n8UJt9YKMDMvPZHgaQyctF7iJTiiqfGj1EGccZBQnyKdJBMKUCuQ0A2",
	"+Z5s9X5BKFrmSYLkmrN8tUa5XrG1laNVJWVyrTTlGjigGFRXAi1gjTeE5byw74lAOvx49L/0HBKyADtS",
	"TiNGlfFDqNLJ1bQQu6FCT2jDIrzIE8y3zj4mccJWahiiSJUmKAU0T7XfRleISEPRjd6FU3wNenOkK4Q1",
	"YxBGEWdCzDhkDEVrTFc6Z4vRkkASG5IFiQExmmyRkIwblQ+3WPmCapPEAuabJwZ7fcZSmBJsqaHCsnLy",
	"JU+//35wNAuAubTA2UU9a9Apq8xG4t2UzbPpYDrBXWx6FtMiIl8jrnMZKMd22Cru8C/PSJIQujpWzjmO",
	"JNLNyuVR5C+GLeKC/Z4sRJGJ2YEP3daoPm/ymi6ZZ0My4cgXHlNIv4V0A8IokiQFIXGaqfVrM6ZOZruc",
	"dYwlzFRj38yXhBKx7h2PqTUwNOIUkSUqOuscftBx0PHnntyYfo44JNqAlsysXa18NQV4g4keoWaxtYfx",
	"0+Ec+NFHgcadGjIvvQUh8MqDph8xSXIOKDUN0M0aqD3tpHyCqyUmCcRXU8SUV3BDBKArRedVQFSkuemV",
	"GKoJuJxXk9ZOiF6UfPAhwxKf4iyDWK+6GIv1gmEeoyghildHTuRdS0mRO52YuSo68igCITwR9RoFylxu",
	"L5UvDLsjj1EOhli+chDqSZWA88BwEH3iDRGyO84TYxl+wu+N9gR1t74TfhRu5cv+LKxkKMNCGKUDSL1R",
	"JGD1pqWPlxpmKTxJbZLokLJpW6Qwx3FRT7JGXze7Luz5x26WLSqw+NTsG+9JzFDft7leh6JndWJ803r5",
	"7sNLlvtCMC/ffUCRMtPKzd5a85PpWKflpVaWaq/fr3Xmswl8kzw3SctL57xzw7E3ydhgqDc6fKFe92Fe",
	"87/kb8vJanNKv/A6DooP18yYMFME6Cb+B3BBTEYlUN+2beIyT98OcHGcvvU7tu3ZigzfUC97Ol6QTOLk",
	"nIjrC/IZOobpmJTTi8/p9Q7oU7cFVCpZFXO2HbepnNashfLQgQOOGisCEGwA54ex3xpTRl2Go5DYcmPW",
	"ptMAonqUYnkuYdcVNqjpqhG8lBbCOPNEP4m4RoJ8hqaeU1bMW3LWq+5OfPgyKUhPHCz2mAu6MVLPjibT",
	"EBWRdhkepif7+GgwvqfJqbrzse0nwIlcd4u1k5Sf8hTTGQccK5yhte7HHOBGHESeyGH6+ghzTY02n7N8",
	"cEtz0qOF1NtWY7ceemQPMg6Cr4Fr59S0Cc5t+Mo7z2HN2dg/6pSoh2hjnlbDohsskOUXuiFy3aJjcBf6",
	"nTshKaSMb32yfaufDAk2ELNfm69TnWbrCVbozckMa9Ni7ljlsbrX50eTngHCzpS5h1QD/DLnUpszTmeA",
	"YNodUigVmoOVmlKoL0yfwnw7hLEd9r4nT//Lh7ML04MJlPfYKI2TZlqQDU57rV5Hu/cBuXRsWvqz1+yo",
	"Wqr3WIqJR9OdYQHIPFTY41BjneR4uSSRWgBYh16IAnkA3k1e4z1IhTxGX91mBlB9yfFiUKAxxChlmhZM",
	"y+DsHwUy3SJe9ItuCI3ZDcIrplMORJZtlCtsHeqE0RXwKtrnzWa7qquPrSX89ELZ1/yW5Bbi/nmljBJp",
	"ctaYxihhq/GT3OWSXEewiXcYDZcktcrTnbPaOe1LwaaCkCzLxg+iX9p5R9ztsL9JZt2sSbRW4nCJsqpw",
	"UNHWLga4NxArXgepzxYmOxejT7lWBwc7jgyceU8MDLJ12MEfVilFUqfDihk0Tog4L058+7z94ONK9hzX",
	"OxLJnMMHXj9HlXMSMpviEGPdjWzDsc9RJNWJQ3d2DR+9HKhf3qLPN9INgh1eB0RDUyi67qKtPI3YRVug",
	"7It0ZUgQWjXtomdc3G1AnDsH1c7DgmqOeTHWEQzT0PYVoxOakO9IyQb6JHs44DMtbnicu1o8gIK6jfVw",
	"33J4yv2aKcFCXmT4hj5MgboWTgAeyuRqOJz7gqnjA6S1nbh9sNvcsgmHa99+WyyroB22jHpW8VPDq7ri",
	"rQh0F0pTmjXGNAKpLoxckAwpJ7GnLFhN4f3+0mDF1M5Beo+LnBfp6ZlY4wxiJAhdJTArjT4OOD5Cbwnn",
	"jBujj9AlxzOcEXRV9H6FDDvN6SHTrEp8c+UMcJ347txOYsg4RNqItLP3+JsgvBdQd9yJGneJysuWOiJV",
	"t3yV0a1eloExX2cHG7KuzaVpW5fCROCqwzpmeFOlZw3oM3CGPnx4fW7cAsooHA1timEHVSvv+1OT8xsT",
	"hc2p9JJst58iZlkhvUZiHdr9Edm631OTgX1r10hsGC/cmEKLG63w7R55Eh6t3degHo619uFg4ag3US4e",
	"Eqp1d+8wYVWRipao6tHYPcqp40TWz/ogVtNp/q5M5R2b4Ket7mGGKJ7FfxqnybpuXruhmOqSsrBXrdUM",
	"9XnOKs5VXKAvDgYO2TQjlWYLDqGm0AOCuw2zaSR+zauhGua3tLd2s7H6jIRLvHpRluLxeH+2Vk0AX/FK",
	"s7R4ozCN2vmPXu1d1QUKjPjjlVtLSIeEglI6hluhW1I5q1bCLHxq+tUfexJlvUM+PCnmHFwZ4mp97PH3",
	"RmtSdI9hOHhqiaDNoWDgBngG9Sm/b9YEs9H10g7Dq6muCAJxsX8sCbdVQMJ8DN/6+v06G5d49eqWiD5J",
	"gH4euIGpdb1W6kSiBJSWNjcA61Lz715UQTUhnyG+9BWu+7l8XB+tOOI+cPPYTKI5ygBr/spZnnVp17So",
	"SjoGokQ8IkbXWLxlHLpFp5M+vINgzTK0gC2zl1ksbCF2G+urOX6BhtUfHJadqRnlMr2aWogAe7A9YhVj",
	"ga6qqm1Xpcopl+qelrPm25jgdgOtg8e5VO9j9IPQtknPCTQmsSdccal+rkrRGZTpgnRNpznI6mzOQg/q",
	"o/yDtrsaJ2JTQt85RD+Z7u0GUzv1Mqyue2l+YGahmMm+aG3lIzqPAn8QwNUUPAe3ExZdQ/wesAiMQO9y",
	"APfh+bgzTCnE/ngxEWdmFl2P+0Pm5QXevrVccNBe9923NDvTTtOJJCbDGir/8pqcfrHK+rXJcjnn8Hja",
	"AEU9YWjZ5eKgD3HD16Mvem9H992ILhThWfd9aP8d6PYZ6o7GZru9lMl516Vn7wVjo5d+8t1Q7nDbU3z7",
	"3neEvHuMf3TdYR7Qzg3ypl5J9HC5GtyhumRrk2V90Og9OY3T8H221G7Dx6VVt22a1PKDKOdEbi9Un2CL",
	"I6WEvsjIf8P2RW4Ka+rCamvAsV5ZtrTa/8x0y9kluwZaCQDrN8vrqH/75bLoZQGYA/+xENzffrksis1p",
	"1aSfVv2spdSWQxgl717P1Kg+KpyKMWd6jA56TFhrLu10hglzOlZiGCBRNZnpgE6DRCUGYq+uSiL19ehX",
	"T89QmVxBL969nkwnmyK4Ozk5enJ0oivJZEBxRiank2dHJ0cnE10Qdq2leIwV94+16I8XxX1gDTnmKwti",
	"nGdT7kQfiBCmFIqO7Wn7CFOk+5zhqk6c8uuLvtEN49fLhN0o44kVRcBex5PTyTsmZHk5WZS3k21ZPhDy",
	"jMXbvRUF674GfV9fGTYiW6vu93SPddl8xzN8VdrMnc1lniTbip2Z9ipxemTK0510DVZSf6waVbUCh9o+",
	"carQ9bf93vRr67YNtX1a0ys6BN/SKB8/3X+aTkSepphvJ6eTUlB6xpPC3/g40YCbfFI9WkDnAvisqBN1",
	"vNjOSiOrwHUH9JS2LGpdnW1fWevgYPgLrGP2yIgcrv41hE9dMdEUOiV0hQpJfCEoHY08IxJTdaqYC1ps",
	"UVnZIBCItqbySBxa5fDYOGwUsPvqMGiZHX/16LOCqMNvBOruTKW/e0XfCjyo+yu0QfehqMTofrqoI1Fa",
	"NTm2BRzVBL549WQZ9LXC4oMDh0E0dFh3PdrncQywwUqNX5sxZqpMf52IqgysWn1YPScHYdZRbCHM1TMx",
	"JOC7pXWuf1ceg9Zmi60poWgLAdrasXJbjW1uBU6RrXWoHxMw5U8IXZmyVCazfaTJQNznW5hxK3DvXb09",
	"91RWd0FiGPII+LBVsYfaPnfqWQ+1/eHAuDPCacLMVWRVUb+uDawMwIwTqPeTc/fTwPfKWh2hbxTfYwhv",
	"bz/3cNAN1VP2Zdi4sh/HyPCKUOPi614OjO1nIW2fPRCvdahO7zqjQx8/dQV4Wh4EEdIEScqShQXO7Q8u",
	"0I/dz/j1I/6iKhezG/LFY2CrVSMnGF+NojjfwOXbt5uFg/qgdVcI/n4YXGflOZrdsPUI0NLl/EaiKdYH",
	"1QtVdRiEjNmGv0Q0WR51gcmU7+hDkCkUMjmg/BulSDwg+MktMiJKRBg+lhN2W+lHx2XN2uO78gbp/TEv",
	"r693zbnMEV0Ub9kr72MXUHVv9aArqH4vP3gVFVdyf0fr6MGrxrLS+ivOsqnqH5uVU2bvLIiah7AUjwXC",
	"SaLNBXPeuZ5LMZ4TJIzqjyROdQmVstQwjcsz58vEfGW0hVOdYDnk0mxnMYPBpWenp370iK5xp/w9ZlxF",
	"occpnvbEViq27z+a0q6n9xVETooaQF9QBmtXZBj+NzNTbqjEJFmdFECHAtDPy5xq8TlGp3hHESSZog1O",
	"SGyqcZdfxSCi/BxG99qvUgrj9qXy25EH3ZZ2gVIZ7Xew9PvckfzJAQ2WAhm9CLwzXxHV5n+Gpfl4YUNZ",
	"qZ81UC6LL46Ox0lpvOxf2bWPSj6ysvOcexwCqL1Wc3hd90h+7IMtJsPDYY1Z4PXYKZ/RZYA7mLXVOB4G",
	"3QMquGa1kGADSa90y4uj3ys4qnhZWspxtKm1RyAcIv3l+bpgkBp7MpBq0PWFXOZ9Merma3HmXsQ1/o1S",
	"Tx1pMF86qg3SHdNSBVSnB0xg6TzdF4qr3xIr7zVfguDiFDzud/6drEpii8M79n/1zevvXG+/+pnQhFCY",
	"opwmIET5qnINGEUYxRDbUEKU5EIC/5ONISz1R7V1WtV8W9qkV+3XoQXj2tXYEIyuYStAIpOdKsi1H432",
	"7MrFzMcDu/Ed8ACIt77NPe4dxuW4N4Izeq0vzx/cxmgXstkhr1eS/S21N2CqSAfnlQYoi5DXtcCxXbfD",
	"6qD46KJSA+3FrheuXAPhxaVMk+QgdMn06rW3/ftX5nlBzAER2VkbPhiUrdk/ZohwBHQ8AGmRHoSRu6ra",
	"w33AtmEKK1XXjNkNNR831Z90MzdWjAOKWkWZOOB4qj/TeWvfqVdK7sbOpVuRYjf9fniHq1aiKtzXqt32",
	"/JYu9KD70inMPArPx6r5cVRUfRlUgfrmLKJlOZjQG7ohwC1vC3/xCG7faw4HM16ZIlvfkOwP4esCZG6N",
	"BrEjqKvKE15Uv1xDdK1L1OtiBniHKhShoH5VlI/YHdUBhi1ePRr4G0U/BjNMitXNyhtaPEAj+HcLjBxi",
	"0dgPuGgV7GXyjmtopStgDO4MnpGdIh+mE2MjL1iuC8ZnwGd6nREhGd9OHVeHbYCbjUS/UXNyx6w6U73j",
	"8KtuXk11hBuKV3PDl53eKXzXUS+N8MSdl7Qr/kh6pVFwZUQ03kGeIfybVtmXT91i7Y665E7i1f1xo/pR",
	"iFrxFHszRmbla+HVFDEeA4cYUbgpqyJNPTokOFBWVyf10mOPoFYyLNfjVdBY3eC+aTXRIy12XyG3UWa0",
	"AwpTHenbit/Him9aus215iiEHk2weXKcYopXoLo4tt9Dr5976M/L2E+0T0JyJLatPn2tq2bhhYDSxfoS",
	"7uM/CWn7pOPaTlmYo+PODkaWvzrUSKT+jJ7kLJllCaZg2fLd5okuPltI7Ibxa12TdlZc8nlAcjbLPTlg",
	"8+F/V5AHusDo+bS/Gfu3vDftIcqn37QvZe/naxlyiBiNSAKxxq9NNT86XcWaKiueHlS7HuIK3OHWnT1n",
	"yHglLGcRDi+0AAV5XBX9OuCifFOUynrMpVkUKAtZkx5l/2q5hEiSDZSnrTkgsaXRmjNKPh8cqofY3A8H",
	"1fclQKHJN7Ot7xe1xfmLRXGmcXfwemsfXeri0sk1UtYxWsCa0Ni4JebQPeEQSf3dRExnLJdi6nwIMAM+",
	"MwQiznKdt2O5/kppGeTTqwABjtZH6CVOEuACReucXqME8xVwJEB6snhnaroXWxpZiFfHnR5lYZnhNBGj",
	"djzf6toA3+pMJ8TFsa81yUwZGVv53c7p2zrzrrMU0225qioOCkSoBlmEk2TPqy38tFMNn0G29dsKA49j",
	"WH99ktdnj3BD5ge0t0edMBs2AhwwPJquapnn9+OxaD8s/A2MXjWEKWIZ/jW3N1L014Sw2AWmbU3UV2qk",
	"cQw45yv4IAJ1jWo4M+clxBrz+N/OodfsMnOfJSzCibsF63NEOhg205UvLXdswceWsPevf0qtcl/WGf9Y",
	"VL8ubiYr5WR/qS5dOj+aw5i1H4rAkfqxUWm+ILkR0NATQCXSRONupo75CuAbEgH62y+X2mCzwzW5cP/p",
	"/v8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
