name: "Run Integration Tests"
description: "Executes integration tests."

runs:
  using: "composite"
  steps:
    - name: Run Infra Tests
      run: |
        # Monitor logs of the services
        tail -f /logs/orchestrator.log &
        tail -f /logs/api.log &
        
        # Run the integration tests
        make test-infra
      shell: bash