name: "Run Integration Tests"
description: "Executes integration tests."

runs:
  using: "composite"
  steps:
    - name: Run Integration Tests
      env:
        TESTS_E2B_API_KEY: "e2b_5ec17bd3933af21f80dc10bba686691c4fcd7057"
        TESTS_API_SERVER_URL: "http://localhost:3000"
      run: |
        # Monitor logs of the services
        ls -l ~/logs
        tail -f ~/logs/orchestrator.log -n 0 &
        tail -f ~/logs/api.log -n 0 &
        
        # Run the integration tests
        make test-integration
      shell: bash