name: Build staging images

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-images:
    name: Build images
    uses: ./.github/workflows/build-and-upload-image.yml
    with:
      commit_sha: ${{ github.sha }}
      environment: staging
      image_names: api;client-proxy;dashboard-api;docker-reverse-proxy;clean-nfs-cache;orchestrator;template-manager;envd;clickhouse-migrator;nomad-nodepool-apm
