name: Build and upload images

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-images:
    name: Build images (${{ matrix.environment }})
    strategy:
      fail-fast: false
      matrix:
        environment:
          - staging
          - foxtrot
          - juliett
    uses: ./.github/workflows/build-and-upload-image.yml
    with:
      commit_sha: ${{ github.sha }}
      environment: ${{ matrix.environment }}
