name: Build and Upload Image

on:
  workflow_call:
    inputs:
      commit_sha:
        description: "Specific commit SHA to checkout"
        required: true
        type: string
      tracking_id:
        description: "Unique tracking ID used for identifying the workflow run"
        required: false
        type: string
      environment:
        description: "Target environment for image upload, e.g. staging"
        required: true
        type: string
      image_names:
        description: "Name of the images to build and upload, e.g. api, template-manager, separated by ;"
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: build-images-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and upload image to the ${{ inputs.environment }} environment
    runs-on: ci-builder
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.commit_sha }}
          persist-credentials: false

      - name: Pull deployment secrets into temporary file
        uses: Infisical/secrets-action@v1.0.15
        with:
          method: "oidc"
          identity-id: ${{ vars.INFISICAL_MACHINE_IDENTITY_ID }}
          project-slug: "infra-deployment"
          env-slug: ${{ inputs.environment }}
          export-type: "file"
          file-output-path: "/.env.infisical"

      - name: Load deployment environment
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "${ENVIRONMENT}" > .last_used_env
          cat .env.infisical | sed "s/='\(.*\)'$/=\1/g" > ".env.${ENVIRONMENT}"

          set -a
          . ".env.${ENVIRONMENT}"
          set +a

          echo "GCP_REGION=${GCP_REGION}" >> "$GITHUB_ENV"
          echo "GCP_PROJECT_ID=${GCP_PROJECT_ID}" >> "$GITHUB_ENV"
          echo "GH_WORKLOAD_IDENTITY_PROVIDER=${GH_WORKLOAD_IDENTITY_PROVIDER}" >> "$GITHUB_ENV"

      - name: Load runtime environment
        uses: Infisical/secrets-action@v1.0.15
        with:
          method: "oidc"
          identity-id: ${{ vars.INFISICAL_MACHINE_IDENTITY_ID }}
          project-slug: "infra-deployment-env"
          env-slug: ${{ inputs.environment }}
          export-type: "env"

      - name: Setup Service Account
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ env.GH_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Docker
        env:
          GCP_REGION: ${{ env.GCP_REGION }}
        run: |
          gcloud auth configure-docker "${GCP_REGION}-docker.pkg.dev" --quiet
          ACCESS_TOKEN="$(gcloud auth print-access-token)"
          DOCKER_AUTH_BASE64="$(echo -n "{\"username\":\"oauth2accesstoken\",\"password\":\"$ACCESS_TOKEN\"}" | base64 -w 0)"

          echo "::add-mask::$DOCKER_AUTH_BASE64"
          echo "DOCKER_AUTH_BASE64=${DOCKER_AUTH_BASE64}" >> "$GITHUB_ENV"

      - name: Build and upload images
        env:
          AUTO_CONFIRM_DEPLOY: true
        run: |
          IFS=';' read -ra IMAGES <<< "${{ inputs.image_names }}"

          for image_name in "${IMAGES[@]}"; do
            image_name="$(echo "$image_name" | xargs)"

            if [ -n "$image_name" ]; then
              echo "::group::Building and uploading image: $image_name"
              make "build-and-upload/$image_name"
              echo "::endgroup::"
            fi
          done
