name: Periodic Tests

on:
  schedule:
    # every hour on hour 38
    # 38 to avoid peak traffic
    - cron: '38 * * * *'
  workflow_dispatch:
  # only run on changes to cheap-test dir 
  push:
    paths:
      - 'cheap-test/**'
      - '.github/workflows/cheap-test.yml'



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  changes:
    name: Repository changes
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        e2b-domain:
          # - "e2b-robert.dev"
          - "e2b-foxtrot.dev"
        test-command:
          - command: "cheap-test/run-code.ts"
            name: "Run Code Tests"
          - command: "index.ts"
            name: "build and delete template"
            dir: "cheap-test/build-template/"
          - command: "cheap-test/snapshot-and-resume.ts"
            name: "snapshot and resume"
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Install node for npx
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # workaround for not being able to use secrets in matrix
      - name: Set API Key
        id: set-api-key
        run: |
          if [ "${{ matrix.e2b-domain }}" == "e2b-robert.dev" ]; then
            echo "api_key=${{ secrets.E2B_API_KEY_ROBERT }}" >> $GITHUB_OUTPUT
          else
            echo "api_key=${{ secrets.E2B_API_KEY }}" >> $GITHUB_OUTPUT
          fi

      - name: ${{ matrix.test-command.name }}
        run: deno run --allow-all ${{ matrix.test-command.command }}
        working-directory: ${{ matrix.test-command.dir }}
        env:
          E2B_API_KEY: ${{ steps.set-api-key.outputs.api_key }}
          E2B_DOMAIN: ${{ matrix.e2b-domain }}

# commented in dev
      # - name: Release Failed - Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   if: failure()
      #   env:
      #     SLACK_COLOR: "#ff0000"
      #     SLACK_MESSAGE: ":here-we-go-again: :bob-the-destroyer: We need :fix-parrot: ASAP :pray:"
      #     SLACK_TITLE: "Health check failed"
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
