name: Deploy Staging Infra

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Specific commit SHA to checkout'
        required: true
        type: string
      tracking_id:
        description: 'Unique tracking ID used for identifying the workflow run'
        required: false
        type: string

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Infra to the staging environment
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Setup environment
        uses: ./.github/actions/deploy-setup-staging
        with:
          postgres_connection_string: ${{ secrets.STAGING_POSTGRES_CONNECTION_STRING }}

      - name: Build and upload
        run: |
          make build-and-upload

      - name: Copy public builds
        run: |
          make copy-public-builds

      - name: Migrate database
        run: |
          make migrate

      - name: Deploy infrastructure
        run: |
          make plan-without-jobs
          make apply
        
