name: FC Kernels

on:
  push:
    branches:
      - kernel-with-fuse

jobs:
  publish:
    name: Upload kernels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build kernels
        working-directory: ./packages/fc-kernels
        run: make build

      - name: Install dependencies
        working-directory: ./packages/fc-kernels
        run: sudo apt update && sudo apt install libelf-dev

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: "./packages/fc-kernels/builds"
