name: govulncheck

on: [workflow_call]

permissions:
  contents: read

jobs:
  detect-modules:
    runs-on: ubuntu-24.04
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v5
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> "$GITHUB_OUTPUT"

  govulncheck:
    needs: detect-modules
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.work
          work-dir: ${{ matrix.module }}
