name: Lint

on:
  workflow_call:
    inputs:
      run-lint:
        type: boolean
        description: "Whether to run package linting"
        required: false
        default: true

permissions:
  contents: read

jobs:
  detect-modules:
    if: ${{ inputs.run-lint == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v5
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: detect-modules
    if: ${{ inputs.run-lint == true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: ./.github/actions/go-setup-cache
        with:
          cache-dependency-paths: |
            go.work
            ${{ matrix.modules }}/go.mod
            ${{ matrix.modules }}/go.sum

      - name: Parse .tool-versions
        uses: wistia/parse-tool-versions@v2.1.1

      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: "v${{ env.GOLANGCI_LINT }}"
          working-directory: ${{ matrix.modules }}

          # disable, as it randomly fails with the following error:
          # The command is terminated due to an error: [../../.golangci.yml] validate: compile schema: failing loading "https://golangci-lint.run/jsonschema/golangci.v2.11.jsonschema.json": Get "https://golangci-lint.run/jsonschema/golangci.v2.11.jsonschema.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
          verify: 'false'

  lint:
    needs:
      - detect-modules
      - golangci-lint
    if: ${{ always() }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Aggregate lint result
        run: |
          if [[ "${{ inputs.run-lint }}" != "true" ]]; then
            echo "lint skipped because lint inputs did not change"
            exit 0
          fi

          if [[ "${{ needs.detect-modules.result }}" != "success" ]]; then
            echo "detect modules result: ${{ needs.detect-modules.result }}"
            exit 1
          fi

          if [[ "${{ needs.golangci-lint.result }}" != "success" ]]; then
            echo "golangci-lint result: ${{ needs.golangci-lint.result }}"
            exit 1
          fi

          echo "lint succeeded"
