name: Periodic Tests Staging

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    inputs:
      dev:
        description: 'Only testing the workflow'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'tests/periodic-test/**'
      - '.github/workflows/periodic-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  checks:
    name: Check
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        e2b-domain: ["e2b-staging.dev"]
        include:
          - e2b-domain: "e2b-staging.dev"
            api_key: E2B_API_KEY
            access_token: E2B_ACCESS_TOKEN
        test-config:
          - test_command: "tests/periodic-test/run-code.ts"
            test_name: "run code in sandbox"
            test_dir: "."
          - test_command: "index.ts"
            test_name: "template builds && time is synchronized"
            test_dir: "tests/periodic-test/time-is-synchronized/"
          - test_command: "tests/periodic-test/snapshot-and-resume.ts"
            test_name: "pause and resume sandbox"
            test_dir: "."
          - test_command: "tests/periodic-test/internet-works.ts"
            test_name: "internet connectivity inside of sandbox"
            test_dir: "."
          # - command: "tests/periodic-test/cli-logs.ts"
          #   name: "cli logs"
    steps:
      - name: Run test
        uses: ./.github/workflows/periodic-test-job.yml
        with:
          dev: ${{ inputs.dev }}
          e2b-domain: ${{ matrix.e2b-domain }}
          api_key: ${{ matrix.api_key }}
          access_token: ${{ matrix.access_token }}
          slack_channel: monitoring-infra-staging
          test_name: ${{ matrix.test-config.test_name }}
          test_command: ${{ matrix.test-config.test_command }}
          test_dir: ${{ matrix.test-config.test_dir }}