name: Post PR to Slack

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

permissions:
  contents: read

jobs:
  notify:
    uses: e2b-dev/.github/.github/workflows/pr-slack-notify.yml@main
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    with:
      channel_id: ${{ vars.SLACK_CHANNEL_ID }}
      review_group: ${{ vars.SLACK_REVIEW_GROUP }}
