// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3W/bOBL/VwjePdwBTux0c/fgtzQpdo0m26BJewcURkCLY4sbidSSVBIj8P9+4Ie+",
	"KVvO17aHPsWRyJnhzG8+xUcciTQTHLhWePqIJahMcAX2n+PJxPyJBNfAtflJsixhEdFM8PEfSnDzTEUx",
	"pMT8+ruEJZ7iv40rmmP3Vo0/SCkk3mw2I0xBRZJlhgie4veEIgl/5qA03ozw8eTo9Xme5DoGrj1VBG6d",
	"YX78+sx/FxotRc6p4fivt1DxFcg7kMUxNyNPz9r4fc4Sei5WH7iWa/MgkyIDqZmDwJJBQu0vQikz9Ehy",
	"2VjR0my5CrmtaCkk0jGgRKwQWCYjrNcZ4ClWWjK+MmrwD8TiD4gsDBK4g2TXgc/F6tyu24xwCkqRFXQl",
	"Ohcr5F+iQs0hCVgKSpM061K4Ll4hsewcZSlkSjSeYko0HBgqXeqbETYIZxIonn6rsarELk48KjQ+34zw",
	"aZIrDfJ3QaFrGS4ozM660prVaHYWOqMCecci+E0o3bMvk+yOaECxUBoRSiUohQinyG9FmZB6C+kZV5rw",
	"KCjYlSfB/JrtQl5pIjXQEx22B7qPgVtjGD2ge6KQhBUz6gI60Cx1XjpXu9BWs4bfUFG4tpQH77fLq91f",
	"QSrmPL15Uv+iwJ1fvuUkfsOpSFMW0NyVyGVk3IACuhtIuwVeD7uQxTvn6RErYOOmItuGaSK35RkzvhQv",
	"6R1DILwbuXk2CLfKaeDtAftmkPv6ncAszzqwagGpUmrL6NpERC9/5NZb6+ERBp6nRtwYSKJjkw+oJIyb",
	"E41wzovH84D62uGgw/e0xgpp5xcFPyGjGJSWRAu5jfqn2roXSyNSJG4v05AORWFdks8igVrWJ1KS9c/8",
	"9Je4e3Hoypeemlp2EXrbPGIx1M0jDrrzsINYWHbdkGRkwRKm10UMaDhfj0+OsIY0S4xxF6bChrCbupK9",
	"45SRd9WmJHaxTd51ADGuf3lXqZtxDSuQW0tix3WXhTyjgopRWllwbw+SinC6EA813VBY5CYkMpOsR/ie",
	"SGNV15CE9HLlKJyLVbigt9U3umc6RmU1beNAwrgRuqlO+zBIx7z5DrsCK/C8oYcn92c/e61Sq77Dqnqu",
	"Wq9VaVp99jOQrrYTZ4dg53ulZR7pXAI1MquuLwzKlm2DB7Kkoe7YL0meaDz9Nu80/I6KFWR/zl2mLaV6",
	"sjVt1DR4AVqyKBDTsvwmEjkPpfY8XYA0Gju9/KKGBTdDLldAb7IoQPH08gvKLQwzkBFw7e1d0F0mgtSg",
	"ya0Ahixl6vZGC00CMe7aPEZmBVIZsZUCWqw1tCX+93FQYkvaiNyl/EUBfTrhFNLtIqeQCrl+AtUt0j6J",
	"5j6OnzocDS2VStI3OWcPAaE5e6jlCsaRgkhwOkjyLUGlxbcFzFEN9nVD1dTbwFwdJfNAqPY+Buo/TMfO",
	"01TX1VSxalteGBALvCt35okXxFrJs0GzM4W0MEZjEpmSR2lvPYU7Z2ipshI1eFxXvp0xFYk7kOuqtv3s",
	"J8bdsz+p0Ec6JhqpWOQJRQtAMeE0AYoWa4vFYj7dXx0/aQDU1kVoBFI7SEhD177KLMa4eySv3uxhabkk",
	"psqkNjSNNOfJAzJJlUKsNqNcMr2+MtScoCcZ+wjrk1zHtuU0AsZATEE9wpykhvZ/D04uZwcfoTZaJnaX",
	"G4YzPyHSTJsCH3949x59oCtAJ5czPMJ3RW+EJ4dHhxMjs8iAk4zhKf7lcHI4MQUl0bEVZ+x6evNzBYHM",
	"85t9jaIYoltsKUk7y5/R8uWpf9f41vLOfQhoEvMot+2jyqMIlFrmiTnVZlRIMk5JFPsCd6dEdhrvNyBV",
	"dEW9Ql540i8mq5ZkuXTVwTBZ/QaUSfGw3ibqtaf8fFHvjsYFYoIyWuioMoa45OHa1KZ0X49mrt0JSfQi",
	"X3zaY9DQt5/yfMkaSdC55EDdUKIue/XlLcSvPMDYLKo+W21faxZVOi0j/Tit8pZXcFtvZZq7KNNIRiRJ",
	"QYNUePqtUzwAScsoLu65qpfetjixcePPHGwf4cOGBpLacUMVkbTMYVRTfqe56HQ8TOl2LvxHSh7Q0WTy",
	"zx6+fu0Ns8VHP/My3va1cEVMnb8ixIIVx2CclSZwvXpheYu2yRC0TV4RmVW6sZCqJ5pvc6NUlacpMV03",
	"/hV0q7JxkTRPNMuSJtQ0Mf1Zo7Tp+sCj/zk724yLhm67M5y7pqvlBxZfJjl14LU/sl/LR+x4jvFVrfyu",
	"mnvVLr1K7DCOUpYkrKrTg85kiOO6PJ1qPmWcpXmKp5NQZd8J75y+lqzA6UtKekEezGrEy/Z5m4w9MiXM",
	"j1JLqcrK8GgymQR68f2EPGMSIl37ArRNxkN05pjbhmIp5D2RfYLTgnBD+GLgWO1dkOjW/uzOGd8icDZq",
	"8sFxs5a+3BDnh4uYNjFW7UPzNE8IkoOLhoElw1WZsAt8vVAU3aMyecW6xMZcG8RMbLLDj2fH0UGxcx+e",
	"O+Nhh+NzHXafSWg1/WiVW/vVPj920WOseaDAdOiNyofUMLzNl12bdECLCc7YdB6qt7eyLKtrAqjct6PR",
	"Cg2KFH4psJAk+bS06hrYjOHN/MmwIUnSuGWg/kowlKZt23Gnicf2IoSdQgU/518QeVt9tU9IBAoJ7hpT",
	"olDtGsUQW59ZZi5igtLvBV2/XCLfOYTcNMdaJlhvhswhGgCwAdgUSVYF5flfMWr426671h5/R6C6ZUnS",
	"j6mPLEnKOxcDkWP2/D8Bx2roJ2jqoKlfzNhaQLbs9SvoT42tb1F89F3celY+aWrg+ykuWpdpGo1Bv52L",
	"mzVqbK/WqPGj/TtglNL5WjJooOKp71+QZxIioqvloRq4fn5392n/EY071HNbhhmn8FBeWyhmNoviY1Dv",
	"7MPdwokBFYL0VPtiuVTQM2p4/pzh55Dphx0yhWzvuPrXuyQePh56xmyqdptt2HCpR7DiFtKwGqK6dvWq",
	"w6r+z8h7jayKCFBFjR+w7b0OHKLKS2XyMfloUz5/LENFJ28ZIDSHSqanm2/+FwAA//8nBXCaezcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
